import type { InsertBeQuestion } from "@shared/schema";

interface QuestionDef {
  level: string;
  skillType: string;
  topic: string;
  question: string;
  options: string[];
  correctAnswer: string;
  passage?: string;
  difficulty: number;
  discrimination: number;
}

function q(level: string, skillType: string, topic: string, question: string, options: string[], correctAnswer: string, passage?: string): QuestionDef {
  const difficultyMap: Record<string, number> = { A0: -250, A1: -150, A2: -50, B1: 50, B2: 150, C1: 250 };
  return {
    level, skillType, topic, question, options, correctAnswer, passage,
    difficulty: difficultyMap[level] ?? 0,
    discrimination: 100,
  };
}

const grammarQuestions: QuestionDef[] = [
  q("A0", "grammar", "daily_life", "I ___ a student.", ["am", "is", "are", "be"], "am"),
  q("A0", "grammar", "travel", "She ___ from Italy.", ["is", "am", "are", "be"], "is"),
  q("A0", "grammar", "food", "They ___ hungry.", ["are", "is", "am", "be"], "are"),
  q("A0", "grammar", "health", "He ___ a doctor.", ["is", "am", "are", "be"], "is"),
  q("A0", "grammar", "education", "We ___ in the classroom.", ["are", "is", "am", "be"], "are"),
  q("A0", "grammar", "technology", "It ___ a good phone.", ["is", "am", "are", "be"], "is"),
  q("A0", "grammar", "entertainment", "I ___ not tired.", ["am", "is", "are", "be"], "am"),
  q("A0", "grammar", "sports", "The park ___ big.", ["is", "am", "are", "be"], "is"),
  q("A0", "grammar", "environment", "You ___ my friend.", ["are", "is", "am", "be"], "are"),
  q("A0", "grammar", "culture", "This ___ my book.", ["is", "am", "are", "be"], "is"),

  q("A1", "grammar", "daily_life", "She ___ to school every day.", ["goes", "go", "going", "gone"], "goes"),
  q("A1", "grammar", "travel", "We ___ a holiday next month.", ["have", "has", "having", "had"], "have"),
  q("A1", "grammar", "food", "The restaurant ___ at 7 PM.", ["opens", "open", "opening", "opened"], "opens"),
  q("A1", "grammar", "health", "I ___ exercise every morning.", ["do", "does", "doing", "did"], "do"),
  q("A1", "grammar", "education", "The lesson ___ at 9 AM.", ["starts", "start", "starting", "started"], "starts"),
  q("A1", "grammar", "technology", "He ___ his phone every day.", ["uses", "use", "using", "used"], "uses"),
  q("A1", "grammar", "entertainment", "They ___ a film tonight.", ["watch", "watches", "watching", "watched"], "watch"),
  q("A1", "grammar", "sports", "She ___ football on Saturdays.", ["plays", "play", "playing", "played"], "plays"),
  q("A1", "grammar", "environment", "It ___ a lot in England.", ["rains", "rain", "raining", "rained"], "rains"),
  q("A1", "grammar", "culture", "We ___ to visit the museum.", ["want", "wants", "wanting", "wanted"], "want"),

  q("A2", "grammar", "daily_life", "I ___ a letter to my friend yesterday.", ["wrote", "write", "writed", "writing"], "wrote"),
  q("A2", "grammar", "travel", "We ___ about the trip last week.", ["talked", "talk", "talking", "talks"], "talked"),
  q("A2", "grammar", "food", "The cake ___ made by my grandmother.", ["was", "is", "were", "been"], "was"),
  q("A2", "grammar", "health", "She ___ feeling ill since Monday.", ["has been", "is been", "was been", "have been"], "has been"),
  q("A2", "grammar", "education", "The homework ___ finished by tomorrow.", ["will be", "is", "are been", "was"], "will be"),
  q("A2", "grammar", "technology", "If you ___ the button, the screen will change.", ["press", "pressed", "pressing", "will press"], "press"),
  q("A2", "grammar", "entertainment", "The concert ___ held last Saturday.", ["was", "is", "were", "been"], "was"),
  q("A2", "grammar", "sports", "I ___ the race before it started raining.", ["finished", "finish", "finishing", "finishes"], "finished"),
  q("A2", "grammar", "environment", "He ___ studying the environment since 2020.", ["has been", "is been", "was been", "had been"], "has been"),
  q("A2", "grammar", "culture", "They ___ the exhibition last month.", ["visited", "visit", "visiting", "visits"], "visited"),

  q("B1", "grammar", "daily_life", "If we ___ earlier, we could have caught the train.", ["had left", "left", "would leave", "have left"], "had left"),
  q("B1", "grammar", "travel", "The plane ___ by the time we arrived at the airport.", ["had departed", "was departing", "has departed", "departs"], "had departed"),
  q("B1", "grammar", "food", "She told me that she ___ the recipe the previous day.", ["had tried", "tried", "tries", "has tried"], "had tried"),
  q("B1", "grammar", "health", "All patients ___ to wait in the reception area.", ["are required", "is required", "requiring", "have requiring"], "are required"),
  q("B1", "grammar", "education", "The book, ___ was published in 1990, is still popular.", ["which", "who", "what", "where"], "which"),
  q("B1", "grammar", "technology", "The app ___ unless additional features are added.", ["will not be updated", "not updates", "isn't updating", "doesn't update"], "will not be updated"),
  q("B1", "grammar", "entertainment", "Having ___ the film, we discussed it over dinner.", ["watched", "watch", "watching", "been watched"], "watched"),
  q("B1", "grammar", "sports", "The match should ___ by 5 PM.", ["be finished", "finish", "finished", "be finishing"], "be finished"),
  q("B1", "grammar", "environment", "Neither the government ___ the industries took action.", ["nor", "or", "and", "but"], "nor"),
  q("B1", "grammar", "culture", "We insisted that the museum ___ open longer hours.", ["keep", "keeps", "kept", "keeping"], "keep"),

  q("B2", "grammar", "daily_life", "Had the neighbours ___ us sooner, we could have helped.", ["warned", "warn", "warning", "been warned"], "warned"),
  q("B2", "grammar", "travel", "The explorer, ___ journeys are legendary, published a new book.", ["whose", "who's", "which", "whom"], "whose"),
  q("B2", "grammar", "food", "Not until we tasted the dish ___ we realise how spicy it was.", ["did", "do", "have", "had"], "did"),
  q("B2", "grammar", "health", "The guidelines require that each person ___ a medical check-up.", ["undergo", "undergoes", "undergoing", "underwent"], "undergo"),
  q("B2", "grammar", "education", "Were the students ___ on time, the exam would have started.", ["to arrive", "arriving", "arrived", "arrives"], "to arrive"),
  q("B2", "grammar", "technology", "So rapid ___ the development of AI that society struggled to adapt.", ["was", "is", "were", "has been"], "was"),
  q("B2", "grammar", "entertainment", "The show proved ___ popular than anyone had expected.", ["far more", "much", "very more", "so much"], "far more"),
  q("B2", "grammar", "sports", "Only after careful analysis ___ the judges announce the winner.", ["did", "does", "has", "will"], "did"),
  q("B2", "grammar", "environment", "The proposal, ___ merits notwithstanding, was rejected by the council.", ["its", "it's", "whose", "which"], "its"),
  q("B2", "grammar", "culture", "Little ___ the visitors know about the history of the building.", ["did", "do", "have", "were"], "did"),

  q("C1", "grammar", "daily_life", "Scarcely ___ the news been announced when people began to react.", ["had", "has", "was", "did"], "had"),
  q("C1", "grammar", "travel", "The journey, ___ challenging in parts, was ultimately rewarding.", ["albeit", "although it", "despite", "however"], "albeit"),
  q("C1", "grammar", "food", "So convinced ___ the chef of the recipe's quality that he entered it in the competition.", ["was", "were", "is", "has been"], "was"),
  q("C1", "grammar", "health", "It is imperative that the government ___ its public health initiatives.", ["strengthen", "strengthens", "strengthened", "strengthening"], "strengthen"),
  q("C1", "grammar", "education", "Not only ___ the funding been cut, but courses had also been cancelled.", ["had", "has", "was", "did"], "had"),
  q("C1", "grammar", "technology", "The invention, ___ it to succeed, would fundamentally change communication.", ["were", "was", "should", "if"], "were"),
  q("C1", "grammar", "entertainment", "Under no circumstances ___ personal recordings be shared online.", ["should", "shall", "would", "could"], "should"),
  q("C1", "grammar", "sports", "The match, the outcome of ___ remains disputed, was replayed.", ["which", "that", "what", "whom"], "which"),
  q("C1", "grammar", "environment", "Notwithstanding the concerns ___ by several scientists, the project proceeded.", ["raised", "raising", "to raise", "having raised"], "raised"),
  q("C1", "grammar", "culture", "Had the community been ___ to compromise, the conflict would have ended sooner.", ["willing", "willing be", "willingly", "willed"], "willing"),
];

const vocabularyQuestions: QuestionDef[] = [
  q("A0", "vocabulary", "daily_life", "A 'house' is a place where people ___.", ["live", "work", "swim", "fly"], "live"),
  q("A0", "vocabulary", "travel", "A 'passport' is needed to ___ to another country.", ["travel", "eat", "sleep", "read"], "travel"),
  q("A0", "vocabulary", "food", "A 'kitchen' is a room where you ___.", ["cook food", "sleep", "swim", "drive"], "cook food"),
  q("A0", "vocabulary", "health", "A 'hospital' is a place for ___ people.", ["sick", "happy", "fast", "tall"], "sick"),
  q("A0", "vocabulary", "education", "A 'school' is a place where children ___.", ["learn", "cook", "sleep", "drive"], "learn"),
  q("A0", "vocabulary", "technology", "A 'computer' is used to ___.", ["work and play", "cook food", "grow plants", "drive cars"], "work and play"),
  q("A0", "vocabulary", "entertainment", "A 'cinema' is a place where you watch ___.", ["films", "sports", "birds", "clouds"], "films"),
  q("A0", "vocabulary", "sports", "A 'ball' is used in many ___.", ["sports", "kitchens", "hospitals", "libraries"], "sports"),
  q("A0", "vocabulary", "environment", "A 'tree' is a big ___.", ["plant", "animal", "rock", "cloud"], "plant"),
  q("A0", "vocabulary", "culture", "'Music' is something you ___ to.", ["listen", "eat", "wear", "drink"], "listen"),

  q("A1", "vocabulary", "daily_life", "I need to ___ the bus to get to work.", ["catch", "cook", "build", "grow"], "catch"),
  q("A1", "vocabulary", "travel", "We need to ___ a hotel room for our holiday.", ["book", "bake", "plant", "swim"], "book"),
  q("A1", "vocabulary", "food", "The soup tastes too ___. It needs more salt.", ["bland", "loud", "bright", "heavy"], "bland"),
  q("A1", "vocabulary", "health", "She went to the ___ because she had a bad cough.", ["doctor", "teacher", "waiter", "driver"], "doctor"),
  q("A1", "vocabulary", "education", "The teacher asked the students to ___ the exercise.", ["complete", "compete", "complain", "compare"], "complete"),
  q("A1", "vocabulary", "technology", "You need a ___ to connect to the internet.", ["password", "passport", "postcard", "package"], "password"),
  q("A1", "vocabulary", "entertainment", "The ___ was very funny and everyone laughed.", ["comedy", "tragedy", "drama", "mystery"], "comedy"),
  q("A1", "vocabulary", "sports", "The ___ scored the winning goal in the last minute.", ["striker", "singer", "driver", "painter"], "striker"),
  q("A1", "vocabulary", "environment", "We should ___ plastic bags to help the environment.", ["recycle", "receive", "recover", "remove"], "recycle"),
  q("A1", "vocabulary", "culture", "The ___ is open from 10 AM to 6 PM.", ["museum", "bathroom", "bedroom", "classroom"], "museum"),

  q("A2", "vocabulary", "daily_life", "I would like to ___ a complaint about the noise.", ["make", "take", "get", "put"], "make"),
  q("A2", "vocabulary", "travel", "The flight was ___ due to bad weather.", ["delayed", "deleted", "designed", "delivered"], "delayed"),
  q("A2", "vocabulary", "food", "This restaurant is famous for its ___ cuisine.", ["traditional", "transitional", "transparent", "temporary"], "traditional"),
  q("A2", "vocabulary", "health", "The doctor ___ some medicine for my cold.", ["prescribed", "presented", "preserved", "prevented"], "prescribed"),
  q("A2", "vocabulary", "education", "We need to ___ for the exam next week.", ["revise", "reverse", "revolve", "reveal"], "revise"),
  q("A2", "vocabulary", "technology", "You can ___ the file to your computer.", ["download", "downgrade", "downsize", "downplay"], "download"),
  q("A2", "vocabulary", "entertainment", "The book was so ___ that I could not stop reading.", ["gripping", "grabbing", "grinding", "grooming"], "gripping"),
  q("A2", "vocabulary", "sports", "The team ___ their opponents 3-1 in the final.", ["defeated", "defended", "defined", "delayed"], "defeated"),
  q("A2", "vocabulary", "environment", "Air ___ is a major problem in big cities.", ["pollution", "position", "portion", "potion"], "pollution"),
  q("A2", "vocabulary", "culture", "The ___ attracted thousands of visitors from around the world.", ["festival", "factory", "facility", "faculty"], "festival"),

  q("B1", "vocabulary", "daily_life", "She has a very ___ personality and makes friends easily.", ["outgoing", "outgoing", "outstanding", "outrageous"], "outgoing"),
  q("B1", "vocabulary", "travel", "The views from the mountain top were absolutely ___.", ["breathtaking", "breathless", "breaching", "breaking"], "breathtaking"),
  q("B1", "vocabulary", "food", "The chef uses only ___ grown ingredients in his dishes.", ["locally", "loudly", "loosely", "lonely"], "locally"),
  q("B1", "vocabulary", "health", "Regular exercise helps to ___ stress and anxiety.", ["relieve", "receive", "retrieve", "release"], "relieve"),
  q("B1", "vocabulary", "education", "The university offers a wide ___ of courses.", ["range", "rank", "rate", "ratio"], "range"),
  q("B1", "vocabulary", "technology", "The company plans to ___ a new version of the software.", ["launch", "latch", "lean", "leak"], "launch"),
  q("B1", "vocabulary", "entertainment", "The film received ___ reviews from critics.", ["mixed", "fixed", "pixelated", "maxed"], "mixed"),
  q("B1", "vocabulary", "sports", "The athlete showed incredible ___ throughout the competition.", ["determination", "destination", "decoration", "delegation"], "determination"),
  q("B1", "vocabulary", "environment", "The government introduced new laws to ___ wildlife.", ["protect", "project", "prospect", "protest"], "protect"),
  q("B1", "vocabulary", "culture", "The painting is considered a ___ of Renaissance art.", ["masterpiece", "manuscript", "manifesto", "marathon"], "masterpiece"),

  q("B2", "vocabulary", "daily_life", "The new regulations have ___ impact on daily routines.", ["a profound", "a profuse", "a prolonged", "a provocative"], "a profound"),
  q("B2", "vocabulary", "travel", "The isolated village is ___ only by a narrow mountain road.", ["accessible", "assessable", "acceptable", "achievable"], "accessible"),
  q("B2", "vocabulary", "food", "The dish incorporates a ___ blend of Eastern and Western flavours.", ["subtle", "suburban", "subsequent", "submarine"], "subtle"),
  q("B2", "vocabulary", "health", "Obesity is increasingly ___ in modern society.", ["prevalent", "preventive", "predictive", "premature"], "prevalent"),
  q("B2", "vocabulary", "education", "The research ___ previous findings about learning styles.", ["corroborates", "contradicts", "constitutes", "consolidates"], "corroborates"),
  q("B2", "vocabulary", "technology", "The app was designed to ___ the user experience.", ["enhance", "enforce", "endure", "enlarge"], "enhance"),
  q("B2", "vocabulary", "entertainment", "Her ___ performance earned her a standing ovation.", ["compelling", "competing", "complying", "comparing"], "compelling"),
  q("B2", "vocabulary", "sports", "The team showed remarkable ___ after falling behind in the first half.", ["resilience", "resemblance", "residence", "resistance"], "resilience"),
  q("B2", "vocabulary", "environment", "Deforestation has led to ___ consequences for biodiversity.", ["devastating", "decorative", "deliberate", "delightful"], "devastating"),
  q("B2", "vocabulary", "culture", "The exhibition ___ the evolution of modern art over the past century.", ["traces", "tracks", "trails", "trades"], "traces"),

  q("C1", "vocabulary", "daily_life", "The council's decision to close the library was met with ___ opposition.", ["vehement", "venerable", "versatile", "vulnerable"], "vehement"),
  q("C1", "vocabulary", "travel", "The region's ___ coastline attracts photographers from around the world.", ["rugged", "ragged", "rigged", "ridged"], "rugged"),
  q("C1", "vocabulary", "food", "The food critic described the meal as ___.", ["exquisite", "exhaustive", "exclusive", "excessive"], "exquisite"),
  q("C1", "vocabulary", "health", "The research highlights the ___ relationship between diet and mental health.", ["intricate", "intrinsic", "intrepid", "intra"], "intricate"),
  q("C1", "vocabulary", "education", "The professor's lecture was both ___ and thought-provoking.", ["erudite", "erratic", "erroneous", "erosive"], "erudite"),
  q("C1", "vocabulary", "technology", "Market ___ has rendered traditional forecasting models obsolete.", ["volatility", "validity", "visibility", "viability"], "volatility"),
  q("C1", "vocabulary", "entertainment", "The playwright's ___ wit shone through every scene.", ["sardonic", "sanguine", "sedentary", "sporadic"], "sardonic"),
  q("C1", "vocabulary", "sports", "The athlete's ___ in the face of adversity inspired millions.", ["tenacity", "tendency", "tangibility", "transparency"], "tenacity"),
  q("C1", "vocabulary", "environment", "The ___ effects of climate change are becoming increasingly apparent.", ["deleterious", "deliberate", "delightful", "democratic"], "deleterious"),
  q("C1", "vocabulary", "culture", "The composer's ___ use of silence was as powerful as the music itself.", ["judicious", "jubilant", "juvenile", "judicial"], "judicious"),
];

const useOfEnglishQuestions: QuestionDef[] = [
  q("A0", "use_of_english", "daily_life", "'Good morning' is a way to say ___.", ["hello", "goodbye", "thank you", "sorry"], "hello"),
  q("A0", "use_of_english", "travel", "When someone says 'Thank you', you say ___.", ["You're welcome", "I'm sorry", "Goodbye", "Good night"], "You're welcome"),
  q("A0", "use_of_english", "food", "'How much?' asks about the ___.", ["price", "time", "colour", "name"], "price"),
  q("A0", "use_of_english", "health", "'How are you?' asks about your ___.", ["health", "job", "age", "country"], "health"),
  q("A0", "use_of_english", "education", "'Where is it?' asks about a ___.", ["place", "time", "person", "reason"], "place"),
  q("A0", "use_of_english", "technology", "To say the time '3:00', we say ___.", ["three o'clock", "three hours", "o'clock three", "clock three"], "three o'clock"),
  q("A0", "use_of_english", "entertainment", "'I like it' means you think it is ___.", ["good", "bad", "ugly", "wrong"], "good"),
  q("A0", "use_of_english", "sports", "In English, Monday is a ___.", ["day", "month", "year", "number"], "day"),
  q("A0", "use_of_english", "environment", "'Please' is used when you ___ something.", ["ask for", "give away", "throw away", "take away"], "ask for"),
  q("A0", "use_of_english", "culture", "'Yes or no?' is a ___.", ["question", "answer", "name", "number"], "question"),

  q("A1", "use_of_english", "daily_life", "Which is the correct way to end a friendly letter?", ["Best wishes", "See you later", "Bye bye", "Talk soon"], "Best wishes"),
  q("A1", "use_of_english", "travel", "'Excuse me, where is the station?' is a way to ___.", ["ask for directions", "order food", "buy clothes", "introduce yourself"], "ask for directions"),
  q("A1", "use_of_english", "food", "'Can I have the bill, please?' is used at the end of a ___.", ["meal", "lesson", "game", "film"], "meal"),
  q("A1", "use_of_english", "health", "'I have a headache' means your ___ hurts.", ["head", "hand", "heart", "hip"], "head"),
  q("A1", "use_of_english", "education", "'Homework' is work you do at ___.", ["home", "school", "the park", "the shop"], "home"),
  q("A1", "use_of_english", "technology", "'To log in' means to ___ your account.", ["enter", "exit", "delete", "create"], "enter"),
  q("A1", "use_of_english", "entertainment", "A 'bestseller' is a book that ___ very well.", ["sells", "smells", "spells", "swells"], "sells"),
  q("A1", "use_of_english", "sports", "A 'draw' in football means the score is ___.", ["equal", "different", "wrong", "high"], "equal"),
  q("A1", "use_of_english", "environment", "'To save water' means to ___ less water.", ["use", "drink", "boil", "sell"], "use"),
  q("A1", "use_of_english", "culture", "A 'gallery' is a place where you can see ___.", ["art", "animals", "food", "cars"], "art"),

  q("A2", "use_of_english", "daily_life", "'I would be grateful if you could...' is a polite way to ___.", ["make a request", "give an order", "express anger", "say goodbye"], "make a request"),
  q("A2", "use_of_english", "travel", "'To check in' at a hotel means to ___.", ["register your arrival", "pay your bill", "clean your room", "leave the hotel"], "register your arrival"),
  q("A2", "use_of_english", "food", "'To be full' after eating means you ___.", ["cannot eat more", "are still hungry", "want dessert", "feel sick"], "cannot eat more"),
  q("A2", "use_of_english", "health", "'Over the counter' medicine means you can buy it ___.", ["without a prescription", "only in hospitals", "only online", "only with a doctor's letter"], "without a prescription"),
  q("A2", "use_of_english", "education", "A 'term' at school is a ___ of the academic year.", ["period", "problem", "product", "project"], "period"),
  q("A2", "use_of_english", "technology", "'To go viral' online means something ___ very quickly.", ["spreads", "stops", "shrinks", "sleeps"], "spreads"),
  q("A2", "use_of_english", "entertainment", "'A spoiler' reveals the ___ of a story.", ["ending", "beginning", "author", "title"], "ending"),
  q("A2", "use_of_english", "sports", "'A warm-up' is done ___ exercise.", ["before", "after", "during", "instead of"], "before"),
  q("A2", "use_of_english", "environment", "'Renewable energy' comes from sources that ___.", ["do not run out", "are very expensive", "cause pollution", "are underground"], "do not run out"),
  q("A2", "use_of_english", "culture", "'Heritage' refers to traditions and values passed from ___ generations.", ["previous", "future", "modern", "current"], "previous"),

  q("B1", "use_of_english", "daily_life", "The expression 'at the end of the day' means ___.", ["ultimately / when everything is considered", "in the evening", "at closing time", "when the sun sets"], "ultimately / when everything is considered"),
  q("B1", "use_of_english", "travel", "'Off the beaten track' describes a place that is ___.", ["not well known by tourists", "dangerous", "very crowded", "close to the airport"], "not well known by tourists"),
  q("B1", "use_of_english", "food", "'From scratch' means to make something ___.", ["from the very beginning using basic ingredients", "very quickly", "using a recipe book", "in a restaurant"], "from the very beginning using basic ingredients"),
  q("B1", "use_of_english", "health", "'To feel under the weather' means to feel ___.", ["slightly ill", "very happy", "very cold", "extremely tired"], "slightly ill"),
  q("B1", "use_of_english", "education", "'To learn by heart' means to ___.", ["memorise something completely", "study with emotion", "enjoy learning", "learn slowly"], "memorise something completely"),
  q("B1", "use_of_english", "technology", "'User-friendly' means something is ___.", ["easy to use", "free of charge", "made by users", "very expensive"], "easy to use"),
  q("B1", "use_of_english", "entertainment", "'A page-turner' is a book that is ___.", ["very exciting and hard to stop reading", "very boring", "very long", "very expensive"], "very exciting and hard to stop reading"),
  q("B1", "use_of_english", "sports", "'A level playing field' means conditions are ___.", ["fair and equal for everyone", "flat and green", "competitive", "difficult for all"], "fair and equal for everyone"),
  q("B1", "use_of_english", "environment", "'Carbon footprint' refers to the amount of ___.", ["greenhouse gases produced by activities", "carbon in the soil", "feet on carbon surfaces", "carbon in food"], "greenhouse gases produced by activities"),
  q("B1", "use_of_english", "culture", "'Melting pot' describes a place where ___.", ["many different cultures mix together", "metal is heated", "food is cooked", "ice cream is made"], "many different cultures mix together"),

  q("B2", "use_of_english", "daily_life", "'To read between the lines' means to ___.", ["understand the hidden meaning", "read very slowly", "read aloud", "skip some paragraphs"], "understand the hidden meaning"),
  q("B2", "use_of_english", "travel", "'To live out of a suitcase' means to ___.", ["travel frequently without settling down", "have very few belongings", "live in a hotel permanently", "pack very carefully"], "travel frequently without settling down"),
  q("B2", "use_of_english", "food", "'An acquired taste' is something that ___.", ["you learn to enjoy over time", "everyone likes immediately", "tastes terrible", "is very expensive"], "you learn to enjoy over time"),
  q("B2", "use_of_english", "health", "'Prevention is better than cure' means ___.", ["it is better to stop problems before they start", "medicine is unnecessary", "doctors are not helpful", "illness is avoidable"], "it is better to stop problems before they start"),
  q("B2", "use_of_english", "education", "A 'steep learning curve' means something is ___.", ["difficult to learn at first", "easy to master", "impossible to understand", "boring to study"], "difficult to learn at first"),
  q("B2", "use_of_english", "technology", "'Cutting-edge technology' refers to technology that is ___.", ["the most advanced and newest available", "very old and reliable", "cheap and widely available", "dangerous and untested"], "the most advanced and newest available"),
  q("B2", "use_of_english", "entertainment", "'Typecasting' in acting means ___.", ["always being given similar roles", "typing scripts quickly", "casting votes", "being a type of actor"], "always being given similar roles"),
  q("B2", "use_of_english", "sports", "'Moving the goalposts' means to ___.", ["change the rules or conditions unfairly", "rearrange the football pitch", "score a winning goal", "train harder"], "change the rules or conditions unfairly"),
  q("B2", "use_of_english", "environment", "'Greenwashing' is when a company ___.", ["falsely claims to be environmentally friendly", "uses green paint", "cleans the environment", "recycles its products"], "falsely claims to be environmentally friendly"),
  q("B2", "use_of_english", "culture", "'Cultural appropriation' refers to ___.", ["adopting elements of another culture without respect", "appreciating art", "travelling abroad", "learning a new language"], "adopting elements of another culture without respect"),

  q("C1", "use_of_english", "daily_life", "'To have one's cake and eat it too' means to ___.", ["want to enjoy two incompatible benefits", "eat too much", "share food generously", "celebrate a birthday"], "want to enjoy two incompatible benefits"),
  q("C1", "use_of_english", "travel", "'Wanderlust' describes a strong desire to ___.", ["travel and explore the world", "stay at home", "read travel books", "collect maps"], "travel and explore the world"),
  q("C1", "use_of_english", "food", "'Gastronomic' relates to the art of ___.", ["fine cooking and eating", "fast food preparation", "food photography", "grocery shopping"], "fine cooking and eating"),
  q("C1", "use_of_english", "health", "'Psychosomatic' describes a physical illness caused by ___.", ["mental or emotional factors", "bacteria", "physical injury", "poor diet"], "mental or emotional factors"),
  q("C1", "use_of_english", "education", "'Pedagogy' refers to ___.", ["the method and practice of teaching", "the study of children", "school architecture", "educational technology"], "the method and practice of teaching"),
  q("C1", "use_of_english", "technology", "'Ubiquitous computing' means technology that is ___.", ["present everywhere in daily life", "very expensive", "only used by experts", "always connected to the internet"], "present everywhere in daily life"),
  q("C1", "use_of_english", "entertainment", "'Avant-garde' in art describes work that is ___.", ["experimental and pushing boundaries", "traditional and classical", "simple and minimalist", "commercial and popular"], "experimental and pushing boundaries"),
  q("C1", "use_of_english", "sports", "'To rest on one's laurels' means to ___.", ["stop trying after achieving success", "take a nap after exercise", "win a prize", "celebrate a victory"], "stop trying after achieving success"),
  q("C1", "use_of_english", "environment", "'Anthropocene' refers to the current geological era defined by ___.", ["significant human impact on the Earth", "ancient rock formations", "ice ages", "volcanic activity"], "significant human impact on the Earth"),
  q("C1", "use_of_english", "culture", "'Zeitgeist' refers to the ___.", ["spirit or mood of a particular period", "German word for clock", "latest fashion trend", "political system"], "spirit or mood of a particular period"),
];

const readingQuestions: QuestionDef[] = [
  q("A0", "reading", "daily_life", "What does the notice say?", ["The shop is closed today", "The park is open all day", "You can buy lunch here", "School starts at 8 AM"],
    "The shop is closed today",
    "NOTICE\nThis shop is closed today.\nWe are sorry for any inconvenience.\nWe open again tomorrow at 9 AM."),
  q("A0", "reading", "food", "What does the menu say?", ["Soup costs two euros", "Pizza is free", "The restaurant is closed", "No food today"],
    "Soup costs two euros",
    "TODAY'S MENU\nSoup: 2 euros\nSandwich: 3 euros\nCoffee: 1 euro"),
  q("A0", "reading", "health", "What does the sign say?", ["No smoking here", "Free food inside", "Open 24 hours", "Parking available"],
    "No smoking here",
    "NO SMOKING\nPlease do not smoke in this area.\nThank you."),
  q("A0", "reading", "travel", "When does the train leave?", ["At 10 AM", "At night", "On Sunday", "Never"],
    "At 10 AM",
    "TRAIN TIMETABLE\nLondon to Oxford: 10:00 AM\nPlatform 3"),
  q("A0", "reading", "education", "What is Maria's hobby?", ["She likes painting", "She likes cooking", "She likes swimming", "She likes singing"],
    "She likes painting",
    "My name is Maria. I am 12 years old. I like painting. I paint every weekend."),
  q("A0", "reading", "environment", "What should we do?", ["Save water", "Buy more water", "Use hot water", "Drink only water"],
    "Save water",
    "SAVE WATER\nPlease turn off the tap when you brush your teeth.\nEvery drop counts."),
  q("A0", "reading", "sports", "When is the football match?", ["On Saturday at 3 PM", "On Monday at 9 AM", "On Friday night", "Every day"],
    "On Saturday at 3 PM",
    "FOOTBALL MATCH\nSaturday, 3 PM\nCity Stadium\nTickets: 5 euros"),
  q("A0", "reading", "technology", "What is the password?", ["abc123", "The shop is closed", "Call us tomorrow", "No parking"],
    "abc123",
    "WIFI\nNetwork: Library_Free\nPassword: abc123"),
  q("A0", "reading", "entertainment", "What film is showing?", ["Happy Days at 7 PM", "A scary film at midnight", "No films today", "Three films at once"],
    "Happy Days at 7 PM",
    "CINEMA\nTonight: Happy Days\nTime: 7:00 PM\nTickets: 8 euros"),
  q("A0", "reading", "culture", "What day is the museum free?", ["Sunday", "Monday", "Every day", "Never"],
    "Sunday",
    "CITY MUSEUM\nOpen: Tuesday to Sunday\nFree entry on Sundays"),

  q("A1", "reading", "daily_life", "What is the purpose of the message?", ["To invite someone to a birthday party", "To cancel plans", "To complain about noise", "To ask for help moving house"],
    "To invite someone to a birthday party",
    "Hi Tom,\nI'm having a birthday party this Saturday at my house at 6 PM. Would you like to come? There will be cake and music!\nSee you there,\nAnna"),
  q("A1", "reading", "travel", "What does the sign say about the hotel?", ["Breakfast is included", "The pool is closed", "Rooms are not available", "Check-out is at 8 AM"],
    "Breakfast is included",
    "WELCOME TO HOTEL SUNRISE\nBreakfast included: 7:00 - 10:00 AM\nWifi: Free in all rooms\nCheck-out: 11:00 AM"),
  q("A1", "reading", "food", "What did the reviewer think of the restaurant?", ["The food was delicious but expensive", "The service was terrible", "The restaurant was closed", "The music was too loud"],
    "The food was delicious but expensive",
    "Restaurant Review: La Bella\nThe pasta was absolutely delicious and the desserts were amazing. However, the prices are quite high. A main course costs about 25 euros. Worth it for a special occasion."),
  q("A1", "reading", "health", "What advice does the article give?", ["Drink 8 glasses of water a day", "Avoid all fruit", "Sleep only 4 hours", "Never exercise"],
    "Drink 8 glasses of water a day",
    "HEALTH TIPS\nDoctors recommend drinking at least 8 glasses of water every day. This helps your body stay healthy and gives you more energy."),
  q("A1", "reading", "education", "What does the notice say?", ["The library is open until 9 PM this week", "The library is permanently closed", "Books are free to keep", "Students cannot use computers"],
    "The library is open until 9 PM this week",
    "LIBRARY NOTICE\nDuring exam week (March 10-15), the library will stay open until 9 PM. Normal hours resume on March 16."),
  q("A1", "reading", "technology", "What is the email about?", ["A new app update", "A broken computer", "A stolen phone", "A cancelled subscription"],
    "A new app update",
    "Dear User,\nA new update is available for your app. Please update to version 3.0 for new features and better performance.\nDownload it from the app store today."),
  q("A1", "reading", "entertainment", "What is happening this weekend?", ["A free outdoor concert", "A cinema closing", "A book sale", "A sports event"],
    "A free outdoor concert",
    "WEEKEND EVENTS\nFree outdoor concert in Central Park\nSaturday, 4 PM\nBring your own blanket and enjoy live music!"),
  q("A1", "reading", "sports", "What does the notice say?", ["Swimming lessons are available for children", "The pool is permanently closed", "Only adults can swim", "Swimming is dangerous"],
    "Swimming lessons are available for children",
    "SWIMMING LESSONS\nFor children aged 6-12\nEvery Wednesday, 4:00 - 5:00 PM\nCost: 10 euros per session\nSign up at reception"),
  q("A1", "reading", "environment", "What does the poster say?", ["Plant a tree this spring", "Cut down old trees", "Trees are not important", "Forests are disappearing"],
    "Plant a tree this spring",
    "PLANT A TREE\nJoin our tree-planting event this spring!\nDate: April 5\nMeeting point: City Park entrance\nAll ages welcome!"),
  q("A1", "reading", "culture", "What is the exhibition about?", ["Ancient Egyptian art", "Modern photography", "Local food recipes", "Children's drawings"],
    "Ancient Egyptian art",
    "NEW EXHIBITION\nAncient Egypt: Art and Life\nNational Museum, Gallery 3\nJanuary 15 - March 30\nAdults: 12 euros / Students: 6 euros"),

  q("A2", "reading", "daily_life", "What is the writer's main advice?", ["Start saving money as early as possible", "Spend money on experiences", "Avoid using bank accounts", "Borrow from friends"],
    "Start saving money as early as possible",
    "Financial Advice for Young Adults\nOne of the most important things you can do is start saving money as early as possible. Even putting aside a small amount each month can make a big difference over time. Most experts recommend saving at least 10% of your income."),
  q("A2", "reading", "travel", "What happened on the trip?", ["The travellers missed their connecting flight", "The hotel was overbooked", "The luggage was lost forever", "The trip was cancelled"],
    "The travellers missed their connecting flight",
    "Travel Blog: A Trip to Remember\nOur journey started badly when we missed our connecting flight in Frankfurt due to a 30-minute delay from London. The airline put us on the next flight three hours later and gave us meal vouchers. We finally arrived in Rome at midnight, exhausted but excited."),
  q("A2", "reading", "food", "What does the article say about the Mediterranean diet?", ["It can reduce the risk of heart disease", "It makes you gain weight", "It is only for Italian people", "It is too expensive for most people"],
    "It can reduce the risk of heart disease",
    "Health & Food: The Mediterranean Diet\nStudies show that the Mediterranean diet, rich in olive oil, fish, vegetables, and whole grains, can significantly reduce the risk of heart disease. Researchers followed 7,500 people over five years and found a 30% lower risk among those following this diet."),
  q("A2", "reading", "health", "What does the article recommend?", ["Getting at least 7 hours of sleep per night", "Sleeping only when tired", "Taking sleeping pills regularly", "Avoiding sleep on weekends"],
    "Getting at least 7 hours of sleep per night",
    "Sleep and Health\nResearch shows that adults should get at least 7 hours of sleep per night. Poor sleep is linked to weight gain, weakened immune function, and reduced concentration. Experts suggest establishing a regular bedtime routine and avoiding screens before bed."),
  q("A2", "reading", "education", "What change is being made?", ["A new language requirement for all students", "Shorter school hours", "More homework", "Fewer examinations"],
    "A new language requirement for all students",
    "To: All Students and Parents\nSubject: New Language Policy\nFrom September, all students will be required to study at least two foreign languages until the age of 16. This decision reflects our commitment to preparing students for an increasingly international world."),
  q("A2", "reading", "technology", "What is the article about?", ["How smartphones affect sleep quality", "How to repair a smartphone", "The most expensive smartphones", "Smartphone games for children"],
    "How smartphones affect sleep quality",
    "Digital Wellbeing\nA new study from Oxford University found that using smartphones before bed can reduce sleep quality by up to 20%. The blue light from screens suppresses melatonin production, making it harder to fall asleep. Experts recommend putting devices away at least one hour before bedtime."),
  q("A2", "reading", "entertainment", "What does the review say?", ["The book is worth reading despite being long", "The book is too short", "The author is unknown", "The book has no plot"],
    "The book is worth reading despite being long",
    "Book Review: The Silent Road\nAt over 500 pages, this novel demands patience, but it rewards the reader with a beautifully crafted story of family and forgiveness. The characters feel real and the ending is deeply satisfying. Highly recommended for anyone who enjoys literary fiction."),
  q("A2", "reading", "sports", "What happened in the match?", ["The underdog team won in the last minute", "Both teams drew", "The match was cancelled", "No goals were scored"],
    "The underdog team won in the last minute",
    "Sports News: Incredible Final!\nIn one of the most dramatic finals in recent history, underdog FC Estrela scored in the 94th minute to beat last year's champions 2-1. Their manager called it 'the greatest moment of my career'. Over 60,000 fans celebrated in the stadium."),
  q("A2", "reading", "environment", "What does the report say?", ["Plastic waste in the oceans has doubled in ten years", "The oceans are getting cleaner", "Plastic is no longer a problem", "Fish populations are growing"],
    "Plastic waste in the oceans has doubled in ten years",
    "Environmental Report\nAccording to a new UN report, the amount of plastic waste in the world's oceans has doubled over the last ten years. An estimated 8 million tonnes of plastic enter the oceans every year, threatening marine life and ecosystems. The report calls for urgent action."),
  q("A2", "reading", "culture", "What does the article discuss?", ["How traditional festivals help preserve local culture", "Why festivals should be cancelled", "The cost of organising festivals", "Festival food safety rules"],
    "How traditional festivals help preserve local culture",
    "Culture & Society\nTraditional festivals play a vital role in preserving local culture and identity. From the Carnival in Venice to Diwali in India, these celebrations bring communities together and pass traditions from one generation to the next. Researchers say they also boost local economies through tourism."),

  q("B1", "reading", "daily_life", "What is the main point of the article?", ["That walking 30 minutes daily can significantly improve mental health", "That running is better than walking", "That exercise is unnecessary", "That only young people should exercise"],
    "That walking 30 minutes daily can significantly improve mental health",
    "A study published in the British Medical Journal followed 10,000 adults over three years and found that those who walked briskly for at least 30 minutes a day reported 40% fewer symptoms of anxiety and depression than those who were sedentary. The researchers emphasised that even moderate physical activity, when done consistently, can have profound effects on mental wellbeing, comparable in some cases to medication."),
  q("B1", "reading", "travel", "What does the article suggest about sustainable tourism?", ["That travellers should choose local accommodation and transport", "That flying is the most sustainable option", "That luxury resorts are eco-friendly", "That tourism should be banned"],
    "That travellers should choose local accommodation and transport",
    "Sustainable Tourism: A Growing Trend\nMore travellers are choosing sustainable options when planning holidays. Experts recommend staying in locally owned accommodation rather than international hotel chains, using public transport, and supporting local businesses. A recent survey found that 58% of travellers under 35 consider environmental impact when booking trips. Small changes, such as carrying a reusable water bottle, can also make a difference."),
  q("B1", "reading", "food", "What did the study find?", ["That children who cook with their parents eat more vegetables", "That children prefer junk food", "That cooking is too dangerous for children", "That parents should not let children in the kitchen"],
    "That children who cook with their parents eat more vegetables",
    "A study by the University of Alberta found that children who regularly help prepare meals at home eat 25% more vegetables than those who do not. Researchers observed 150 families over 12 months and concluded that involving children in cooking from an early age helps them develop healthier eating habits that last into adulthood. The study recommends age-appropriate cooking tasks for children as young as five."),
  q("B1", "reading", "health", "What health risk is highlighted?", ["Prolonged sitting increases the risk of heart disease", "Eating too much fruit is dangerous", "Sleeping too much causes headaches", "Running causes joint damage"],
    "Prolonged sitting increases the risk of heart disease",
    "Health Warning: The Dangers of Sitting\nNew research has shown that sitting for more than 8 hours a day without regular movement increases the risk of heart disease by 35%. The study, which tracked 50,000 office workers over five years, found that even regular exercise cannot fully offset the negative effects of prolonged sitting. Health experts recommend standing for at least 5 minutes every hour."),
  q("B1", "reading", "education", "What approach does the article recommend?", ["Combining traditional teaching with technology to improve learning outcomes", "Replacing teachers with computers", "Banning technology in classrooms", "Only using textbooks"],
    "Combining traditional teaching with technology to improve learning outcomes",
    "Education in the Digital Age\nSchools that blend traditional teaching methods with technology are seeing significant improvements in student performance. A three-year study across 200 European schools found that students in blended learning environments scored 15% higher on standardised tests than those in traditional-only classrooms. However, researchers warn that technology should support, not replace, the role of the teacher."),
  q("B1", "reading", "technology", "What concern does the article raise?", ["That AI could replace many jobs within the next decade", "That AI is completely harmless", "That technology is getting slower", "That computers are becoming cheaper"],
    "That AI could replace many jobs within the next decade",
    "The Future of Work and AI\nA report by the World Economic Forum predicts that artificial intelligence could automate up to 40% of routine tasks currently performed by humans within the next 10 years. While AI will create new types of jobs, there is growing concern that many workers, particularly in administrative and manufacturing roles, may not have the skills needed for the transition. Governments are urged to invest heavily in retraining programmes."),
  q("B1", "reading", "entertainment", "What does the article say about streaming services?", ["They have fundamentally changed how people consume entertainment", "They are less popular than cinemas", "They only show old films", "They are about to close down"],
    "They have fundamentally changed how people consume entertainment",
    "The Rise of Streaming\nStreaming platforms have fundamentally transformed the entertainment industry. Global subscriptions reached 1.5 billion in 2025, with the average user watching 3.5 hours of content per day. While cinemas have struggled, streaming has created opportunities for independent filmmakers who previously had limited distribution options. Critics argue, however, that the quality of content has declined due to the pressure to produce quantity."),
  q("B1", "reading", "sports", "What does the research show?", ["That team sports improve social skills more than individual sports", "That individual sports are always better", "That sport is not important for children", "That competitive sports should be banned for children"],
    "That team sports improve social skills more than individual sports",
    "Sport and Social Development\nResearchers at Cambridge University found that children who participate in team sports develop significantly better social skills than those who only do individual sports. The study followed 3,000 children aged 8-14 over four years and found that team sport participants showed 30% higher scores in cooperation, communication, and conflict resolution. The researchers recommend that schools offer a balance of both team and individual sports."),
  q("B1", "reading", "environment", "What solution is proposed?", ["Creating urban green spaces to combat air pollution in cities", "Building more motorways", "Closing all factories", "Moving all people to the countryside"],
    "Creating urban green spaces to combat air pollution in cities",
    "Green Cities Initiative\nA growing body of research supports the creation of urban green spaces as an effective way to combat air pollution. Trees and plants naturally filter pollutants, and studies show that neighbourhoods with more green areas have 20% lower levels of harmful particulate matter. Cities like Milan and Singapore have pioneered vertical gardens and rooftop forests, demonstrating that even densely populated areas can benefit from nature-based solutions."),
  q("B1", "reading", "culture", "What does the article argue?", ["That bilingualism has cognitive benefits that last into old age", "That learning languages is a waste of time", "That monolingual people are smarter", "That children should only learn one language"],
    "That bilingualism has cognitive benefits that last into old age",
    "The Bilingual Brain\nResearch published in the journal Neurology shows that people who speak two or more languages develop symptoms of dementia an average of 4.5 years later than monolinguals. Scientists believe that constantly switching between languages strengthens the brain's executive functions, including attention, problem-solving, and mental flexibility. These findings suggest that bilingualism acts as a form of 'cognitive reserve' that protects the brain as it ages."),

  q("B2", "reading", "daily_life", "What paradox does the article describe?", ["That increased connectivity has led to greater feelings of isolation", "That phones are getting smaller", "That people sleep more now", "That social media is declining"],
    "That increased connectivity has led to greater feelings of isolation",
    "The Loneliness Paradox\nIn an age of unprecedented digital connectivity, loneliness has reached epidemic proportions. A comprehensive study by the American Psychological Association found that despite having an average of 338 online connections, 46% of adults report feeling lonely regularly. Psychologists attribute this to the superficial nature of digital interactions, which often substitute for, rather than supplement, meaningful face-to-face relationships. The phenomenon is particularly acute among 18-25 year olds, who paradoxically have the highest social media usage."),
  q("B2", "reading", "travel", "What does the article discuss?", ["How overtourism is destroying the places people most want to visit", "How to find cheap flights", "The best beaches in Europe", "New airline routes"],
    "How overtourism is destroying the places people most want to visit",
    "The Overtourism Crisis\nFrom Venice to Barcelona, from Machu Picchu to the Great Wall, the world's most iconic destinations are being overwhelmed by visitor numbers that far exceed their carrying capacity. Venice, which has a resident population of just 50,000, receives 30 million tourists annually, leading to environmental degradation, rising living costs, and the erosion of local culture. Several cities have introduced tourist taxes and visitor caps, but critics argue these measures are insufficient without a fundamental rethink of how tourism is managed."),
  q("B2", "reading", "food", "What trend does the article highlight?", ["The growing popularity of lab-grown meat as a sustainable alternative", "That vegetarianism is declining", "That fast food is healthier now", "That organic food is unnecessary"],
    "The growing popularity of lab-grown meat as a sustainable alternative",
    "The Future of Food: Lab-Grown Meat\nCultivated meat—produced by growing animal cells in bioreactors—has moved from science fiction to commercial reality. Singapore and the US have approved several lab-grown meat products, and production costs have fallen 99% over the past decade. Proponents argue that cultivated meat could reduce agricultural emissions by 92% and land use by 95%. However, consumer acceptance remains a challenge, with surveys showing that only 35% of Europeans would willingly try the product."),
  q("B2", "reading", "health", "What does the research reveal?", ["That gut bacteria significantly influence mental health and cognitive function", "That antibiotics cure depression", "That diet has no effect on mood", "That probiotics are dangerous"],
    "That gut bacteria significantly influence mental health and cognitive function",
    "The Gut-Brain Connection\nEmerging research in neurogastroenterology reveals that the trillions of bacteria residing in the human gut play a far more significant role in mental health than previously understood. The gut produces approximately 95% of the body's serotonin, a key mood regulator. Studies have shown that individuals with a diverse gut microbiome exhibit lower rates of anxiety and depression. This has led to the development of 'psychobiotics'—probiotics specifically designed to improve mental health outcomes."),
  q("B2", "reading", "education", "What does the report conclude?", ["That critical thinking skills are more important than content knowledge in the modern economy", "That memorisation is the best learning method", "That universities are no longer needed", "That online education is inferior"],
    "That critical thinking skills are more important than content knowledge in the modern economy",
    "Education for the 21st Century\nThe OECD's latest education report argues that traditional curricula, which prioritise content knowledge and memorisation, are ill-suited to the demands of the modern economy. The report advocates a fundamental shift towards developing critical thinking, creativity, and collaborative problem-solving skills. Countries that have reformed their education systems accordingly—notably Finland and Singapore—consistently outperform others in international assessments and produce graduates better equipped for rapidly evolving workplaces."),
  q("B2", "reading", "technology", "What ethical dilemma is discussed?", ["Whether AI should be used to make life-and-death decisions in healthcare", "How to repair old computers", "Which programming language is best", "How to speed up the internet"],
    "Whether AI should be used to make life-and-death decisions in healthcare",
    "The Ethics of AI in Medicine\nAs artificial intelligence systems become capable of diagnosing diseases with greater accuracy than human doctors, a profound ethical question emerges: should algorithms be permitted to make life-and-death medical decisions? A recent case in which an AI system correctly identified a rare cancer that three specialists had missed has reignited the debate. While AI's diagnostic accuracy is impressive, critics argue that reducing patients to data points strips medicine of its essential humanity and raises troubling questions about accountability when errors occur."),
  q("B2", "reading", "entertainment", "What does the article argue?", ["That social media algorithms are creating cultural echo chambers", "That books are more popular than ever", "That TV is becoming extinct", "That music quality has improved"],
    "That social media algorithms are creating cultural echo chambers",
    "Culture in the Algorithm Age\nSocial media recommendation algorithms, designed to maximise engagement by serving content aligned with existing preferences, are inadvertently creating cultural echo chambers. Users are increasingly exposed only to music, art, film, and opinions that reinforce their existing tastes, reducing exposure to diverse cultural perspectives. Cultural critics warn that this algorithmic curation is producing a generation with narrower cultural literacy and diminished capacity for empathy with unfamiliar viewpoints."),
  q("B2", "reading", "sports", "What issue does the article raise?", ["The growing financial inequality between elite and grassroots sports", "That football is becoming less popular", "That athletes should not be paid", "That amateur sport is unnecessary"],
    "The growing financial inequality between elite and grassroots sports",
    "The Two Worlds of Sport\nWhile elite football clubs spend hundreds of millions on player transfers, grassroots sports facilities across Europe are crumbling due to chronic underinvestment. A report by the European Sports Council found that 60% of community sports centres need significant repairs, and participation in organised youth sport has declined by 25% over the past decade. Critics argue that the vast wealth generated by professional sport should be more equitably distributed to support the community foundations upon which elite athletes are ultimately developed."),
  q("B2", "reading", "environment", "What does the report warn about?", ["That rising sea levels will displace 200 million people by 2050", "That icebergs are growing", "That pollution is decreasing globally", "That forests are expanding"],
    "That rising sea levels will displace 200 million people by 2050",
    "Climate Report: The Rising Tide\nThe latest IPCC report paints a stark picture: without dramatic intervention, rising sea levels will displace approximately 200 million people worldwide by 2050. Low-lying nations such as Bangladesh, the Maldives, and Tuvalu face existential threats. Even in developed nations, coastal cities from Miami to Amsterdam are spending billions on flood defences. The report emphasises that while adaptation is necessary, it cannot substitute for aggressive emissions reduction."),
  q("B2", "reading", "culture", "What phenomenon does the article explore?", ["The tension between globalisation and the preservation of minority languages", "The popularity of English worldwide", "Why everyone should learn Chinese", "How to write a dictionary"],
    "The tension between globalisation and the preservation of minority languages",
    "Losing Words: The Death of Languages\nLinguists estimate that one language dies every two weeks. Of the approximately 7,000 languages currently spoken worldwide, nearly half are endangered. Globalisation, urbanisation, and the dominance of a handful of 'prestige' languages—English, Mandarin, Spanish—are driving this decline. Each lost language represents not merely a communication system, but an irreplaceable worldview, a unique way of understanding human experience. Efforts to document and revitalise endangered languages are gaining momentum, but face significant funding and political challenges."),

  q("C1", "reading", "daily_life", "What societal shift does the article analyse?", ["The erosion of privacy in the digital age and its implications for democracy", "How to protect your password", "The popularity of smart homes", "Tips for online shopping"],
    "The erosion of privacy in the digital age and its implications for democracy",
    "The End of Privacy?\nThe concept of privacy as understood by previous generations is rapidly becoming obsolete. Surveillance capitalism—the monetisation of personal data by technology corporations—has created an economy in which every click, purchase, and movement generates commercially valuable information. The implications extend beyond commerce: when citizens know they are being watched, self-censorship follows, and democratic discourse suffers. As philosopher Shoshana Zuboff argues, the real product in the digital economy is not data, but the modification of human behaviour itself."),
  q("C1", "reading", "travel", "What paradox does the author identify?", ["That authenticity in travel is commodified the moment it is sought", "That aeroplanes are getting faster", "That hotels are more comfortable now", "That travel is becoming cheaper"],
    "That authenticity in travel is commodified the moment it is sought",
    "The Authenticity Trap\nThe contemporary traveller's quest for 'authentic' experiences reveals a fundamental paradox: the moment authenticity is consciously sought, it is inevitably commodified. Local communities, recognising the economic value of their 'authentic' culture, begin performing it for tourists, creating a simulacrum that satisfies visitors' expectations while gradually replacing the genuine article. This phenomenon, which sociologist Dean MacCannell termed 'staged authenticity', raises profound questions about the ethics of cultural tourism and the impossibility of experiencing another culture without fundamentally altering it."),
  q("C1", "reading", "education", "What paradigm shift does the article discuss?", ["The move from knowledge acquisition to knowledge navigation in education", "Longer school days", "More examinations", "Stricter dress codes"],
    "The move from knowledge acquisition to knowledge navigation in education",
    "Beyond Knowledge: Education Reimagined\nThe traditional educational paradigm—premised on the acquisition and retention of codified knowledge—is fundamentally misaligned with an era in which information is ubiquitous and the half-life of professional knowledge is shrinking. The emerging paradigm prioritises metacognitive skills: the ability to evaluate sources, synthesise disparate information, and navigate epistemic uncertainty. Universities that have embraced this shift report graduates who are more adaptable, more innovative, and paradoxically, more deeply knowledgeable, because they have learned how to learn rather than what to learn."),
  q("C1", "reading", "health", "What does the research reveal about longevity?", ["That social connection is as important as diet and exercise for lifespan", "That medication is the key to long life", "That genetics alone determine lifespan", "That exercise is harmful in old age"],
    "That social connection is as important as diet and exercise for lifespan",
    "The Longevity Equation\nA landmark study spanning three decades and five continents has identified the factors most strongly correlated with longevity. While diet and exercise remain important, the strongest predictor of a long life is the quality of one's social relationships. Individuals with strong social bonds live an average of 7.5 years longer than those who are socially isolated—a greater impact than quitting smoking. The implications for public health policy are profound: addressing loneliness may be as important as combating obesity."),
  q("C1", "reading", "technology", "What philosophical question does the article raise?", ["Whether artificial consciousness, if achieved, would require moral rights", "How to programme faster computers", "Which smartphone brand is best", "How the internet was invented"],
    "Whether artificial consciousness, if achieved, would require moral rights",
    "The Consciousness Question\nAs artificial intelligence approaches and potentially surpasses human cognitive capabilities, a question once confined to philosophy departments demands practical consideration: if a machine achieves genuine consciousness—subjective experience, self-awareness, the capacity for suffering—would it possess moral rights? The question is not merely academic: several AI systems have exhibited behaviours that, in biological organisms, would be interpreted as rudimentary emotional responses. The absence of a scientific consensus on the nature of consciousness itself makes adjudicating such claims extraordinarily challenging."),
  q("C1", "reading", "environment", "What fundamental tension does the article examine?", ["Whether economic growth and environmental sustainability are ultimately incompatible", "How to recycle paper", "Tips for saving electricity", "The cost of solar panels"],
    "Whether economic growth and environmental sustainability are ultimately incompatible",
    "Growth vs. The Planet\nThe dominant economic paradigm assumes that perpetual growth is both possible and desirable. Yet mounting evidence suggests that the ecological systems upon which human civilisation depends cannot sustain indefinite material expansion. The concept of 'decoupling'—the hope that economic growth can be separated from resource consumption through technology—has largely failed to materialise at the scale required. A growing movement of economists advocates for post-growth models that prioritise wellbeing over GDP, but such proposals face fierce resistance from political and corporate interests invested in the status quo."),
  q("C1", "reading", "sports", "What does the analysis reveal?", ["That data analytics is fundamentally transforming athletic performance and strategy", "That sports are becoming less popular", "That technology should be banned from sports", "That traditional training is always best"],
    "That data analytics is fundamentally transforming athletic performance and strategy",
    "The Datafication of Sport\nThe integration of advanced data analytics into professional sport has progressed from a competitive advantage to an existential necessity. Teams that fail to invest in data science find themselves structurally disadvantaged. The implications extend beyond tactics: athlete monitoring systems now track sleep patterns, stress hormones, and cognitive load in real time, enabling unprecedented optimisation of training regimens. Critics, however, warn of a dehumanising tendency—the reduction of athletes to datasets—and raise privacy concerns about the extent of biological surveillance that modern sport demands."),
  q("C1", "reading", "culture", "What does the essay explore?", ["How the concept of 'truth' has been destabilised in the post-truth era", "How to write better essays", "The history of printing", "Popular book recommendations"],
    "How the concept of 'truth' has been destabilised in the post-truth era",
    "Truth in the Post-Truth Era\nThe concept of objective truth—once the bedrock of Enlightenment epistemology—has been profoundly destabilised. The proliferation of information sources, the democratisation of content creation, and the deliberate weaponisation of disinformation have created an epistemic environment in which distinguishing fact from fiction requires cognitive resources that most individuals lack. Philosopher Hannah Arendt's observation that the ideal subject of totalitarian rule is not the convinced ideologue, but the person for whom the distinction between fact and fiction no longer exists, has acquired a chilling contemporary relevance."),
  q("C1", "reading", "entertainment", "What cultural shift does the article analyse?", ["The blurring of boundaries between high art and popular culture", "Why opera is dying", "How to write a screenplay", "The best films of the year"],
    "The blurring of boundaries between high art and popular culture",
    "The Collapse of Cultural Hierarchies\nThe traditional distinction between 'high' culture and 'popular' culture—a hierarchy that dominated Western aesthetics for centuries—is increasingly untenable. Video games are exhibited in contemporary art museums, graphic novels win literary prizes, and hip-hop is studied in musicology departments. This democratisation of cultural value, while celebrated by some as overdue inclusivity, is mourned by others as the loss of evaluative standards. The truth, as cultural theorist Pierre Bourdieu might argue, is that the hierarchy was never purely aesthetic—it was always fundamentally about social power and distinction."),
  q("C1", "reading", "food", "What does the investigation reveal?", ["That ultra-processed foods are engineered to be addictive using specific chemical combinations", "That all processed food is healthy", "That cooking at home is unnecessary", "That organic food has no benefits"],
    "That ultra-processed foods are engineered to be addictive using specific chemical combinations",
    "Engineered to Addict\nAn investigation into the ultra-processed food industry reveals systematic practices designed to maximise consumption through the manipulation of 'bliss points'—precise combinations of sugar, salt, and fat that trigger maximum neural reward responses. Internal documents from major food corporations show that products are extensively tested using neuroimaging technology to optimise their addictive potential. The parallels with the tobacco industry are striking: both industries prioritised profit over public health while deploying sophisticated lobbying to resist regulation."),
];

const listeningQuestions: QuestionDef[] = [
  q("A0", "listening", "daily_life", "Where is John from?", ["London", "Paris", "Rome", "Berlin"], "London",
    "You will hear:\nMan: Hello! My name is John. I am from London."),
  q("A0", "listening", "travel", "When does the train leave?", ["9 o'clock", "10 o'clock", "8 o'clock", "7 o'clock"], "9 o'clock",
    "You will hear:\nAnnouncement: The train to Manchester leaves at 9 o'clock from platform 3."),
  q("A0", "listening", "food", "What is the waiter asking about?", ["A drink", "A meal", "The bill", "A table"], "A drink",
    "You will hear:\nWaiter: Good morning. Would you like tea or coffee?"),
  q("A0", "listening", "health", "How often should you take the medicine?", ["Twice a day", "Once a week", "Three times a day", "Once a day"], "Twice a day",
    "You will hear:\nDoctor: Take this medicine twice a day, in the morning and in the evening."),
  q("A0", "listening", "education", "What should the students do?", ["Open the book", "Close the book", "Write in the book", "Read aloud"], "Open the book",
    "You will hear:\nTeacher: Good morning, class. Open your books to page 10, please."),
  q("A0", "listening", "technology", "Where is the password?", ["On the wall", "On the table", "In the book", "On the phone"], "On the wall",
    "You will hear:\nReceptionist: The wifi password is on the wall, next to the door."),
  q("A0", "listening", "entertainment", "When does the film start?", ["8 PM", "7 PM", "9 PM", "6 PM"], "8 PM",
    "You will hear:\nWoman: What time is the film?\nMan: It starts at 8 PM."),
  q("A0", "listening", "sports", "What does the coach want them to do?", ["Run", "Walk", "Sit down", "Jump"], "Run",
    "You will hear:\nCoach: OK everyone, run to the other side of the field. Go!"),
  q("A0", "listening", "environment", "What is the weather like?", ["Rainy", "Sunny", "Snowy", "Windy"], "Rainy",
    "You will hear:\nWoman: Do you want to go to the park?\nMan: No, it is raining outside. Let's stay home."),
  q("A0", "listening", "culture", "How old is the building?", ["500 years", "50 years", "5 years", "5,000 years"], "500 years",
    "You will hear:\nGuide: Welcome, everyone. This building is 500 years old. It was built in 1526."),

  q("A1", "listening", "daily_life", "What time does this person wake up?", ["7 AM", "6 AM", "8 AM", "9 AM"], "7 AM",
    "You will hear:\nWoman: What is your daily routine?\nMan: I usually wake up at 7, have breakfast, and take the bus to work."),
  q("A1", "listening", "travel", "What happened to the flight?", ["It is delayed", "It is cancelled", "It arrived early", "It changed its destination"], "It is delayed",
    "You will hear:\nAnnouncement: Attention please. Flight 302 to Paris is delayed by two hours. We apologise for the inconvenience."),
  q("A1", "listening", "food", "What type of food does this person like?", ["Italian food", "Chinese food", "Mexican food", "Indian food"], "Italian food",
    "You will hear:\nMan: What kind of food do you like?\nWoman: I prefer Italian food, especially pizza and pasta. They are my favourites."),
  q("A1", "listening", "health", "When should you take the medicine?", ["After meals", "Before meals", "Before bed", "In the morning only"], "After meals",
    "You will hear:\nPharmacist: Here is your prescription. Take one tablet with water after meals, three times a day."),
  q("A1", "listening", "education", "What is their favourite subject?", ["Maths", "English", "Science", "Art"], "Maths",
    "You will hear:\nTeacher: What is your favourite subject?\nStudent: My favourite subject is maths because I like solving problems."),
  q("A1", "listening", "technology", "Which button starts the machine?", ["The green one", "The red one", "The blue one", "The yellow one"], "The green one",
    "You will hear:\nInstructor: To start the machine, press the green button. The red button is to stop it."),
  q("A1", "listening", "entertainment", "How was the concert?", ["Amazing", "Boring", "Cancelled", "Disappointing"], "Amazing",
    "You will hear:\nWoman: Did you go out last night?\nMan: Yes, I went to a concert. The band was amazing!"),
  q("A1", "listening", "sports", "Who won?", ["The home team", "The away team", "Nobody - it was a draw", "The match was cancelled"], "The home team",
    "You will hear:\nCommentator: And that is the final whistle! The final score is 3-1 to the home team. What a great match!"),
  q("A1", "listening", "environment", "Why should we plant trees?", ["To clean the air", "To get fruit", "To make furniture", "To build houses"], "To clean the air",
    "You will hear:\nTeacher: Today we are talking about the environment. We should plant more trees because they help clean the air."),
  q("A1", "listening", "culture", "Who painted it?", ["Leonardo da Vinci", "Michelangelo", "Picasso", "Van Gogh"], "Leonardo da Vinci",
    "You will hear:\nGuide: If you look to your left, you can see a famous painting. It was created by Leonardo da Vinci in the 16th century."),

  q("A2", "listening", "daily_life", "Why was the meeting moved?", ["The room was not available", "The speaker was ill", "There were too many people", "The equipment was broken"], "The room was not available",
    "You will hear:\nManager: I am sorry, but the meeting has been moved from 2 PM to 4 PM. The room was not available at the earlier time.\nColleague: OK, that is fine. I will change my schedule."),
  q("A2", "listening", "travel", "When does the agent suggest travelling?", ["Spring", "Summer", "Autumn", "Winter"], "Spring",
    "You will hear:\nCustomer: When is the best time to visit?\nAgent: I recommend visiting in spring. It is less crowded then and the weather is mild."),
  q("A2", "listening", "food", "What is important for good risotto?", ["Fresh stock and constant stirring", "Using frozen vegetables", "Cooking at high temperature", "Adding cream at the start"], "Fresh stock and constant stirring",
    "You will hear:\nInterviewer: What is your top cooking tip?\nChef: The secret to a good risotto is using fresh stock and stirring constantly. Never stop stirring!"),
  q("A2", "listening", "health", "What advice does the nurse give?", ["Reduce salt and exercise more", "Eat more salt", "Rest in bed", "Take antibiotics"], "Reduce salt and exercise more",
    "You will hear:\nNurse: Your blood pressure is a bit high today.\nPatient: What should I do?\nNurse: Try reducing salt in your food and exercising more regularly."),
  q("A2", "listening", "education", "When is the new deadline?", ["Next Friday", "This Monday", "Tomorrow", "In two weeks"], "Next Friday",
    "You will hear:\nLecturer: Good news, everyone. The essay deadline has been extended to next Friday because of the bank holiday this week."),
  q("A2", "listening", "technology", "What advice is given?", ["Back up files regularly", "Buy a new computer", "Delete old files", "Use only cloud storage"], "Back up files regularly",
    "You will hear:\nIT support: Remember to back up your files regularly. If your computer crashes and you have no backup, you could lose everything."),
  q("A2", "listening", "entertainment", "When should you visit the exhibition?", ["On a weekday", "On Saturday", "On Sunday", "At night"], "On a weekday",
    "You will hear:\nPresenter: The new exhibition at the city gallery is well worth visiting, but I would avoid weekends. It gets very crowded on Saturdays and Sundays."),
  q("A2", "listening", "sports", "Why did the team lose?", ["Poor defence in the second half", "The referee made mistakes", "They did not score enough", "The weather was bad"], "Poor defence in the second half",
    "You will hear:\nJournalist: What happened in the match today?\nCoach: Honestly, we lost because we did not defend well in the second half. We need to work on that."),
  q("A2", "listening", "environment", "What does the scientist predict?", ["A 2-degree temperature rise by 2050", "Temperatures will drop", "No change in climate", "An ice age by 2050"], "A 2-degree temperature rise by 2050",
    "You will hear:\nScientist: Our research shows that if we continue at this rate, global temperatures will rise by 2 degrees by 2050. This will have serious consequences."),
  q("A2", "listening", "culture", "What benefit of learning languages is mentioned?", ["Understanding other cultures", "Getting a higher salary", "Travelling more cheaply", "Making more friends online"], "Understanding other cultures",
    "You will hear:\nSpeaker: Learning a second language opens doors to other cultures and other ways of thinking. It changes how you see the world."),

  q("B1", "listening", "daily_life", "What is the speaker's concern about remote work?", ["Feeling isolated from social interaction", "Too many distractions at home", "Unreliable internet connection", "Difficulty separating work and personal life"], "Feeling isolated from social interaction",
    "You will hear:\nInterviewer: How do you find working from home?\nEmployee: It has its advantages, like saving time on the commute. But I find the lack of social interaction quite isolating. I miss talking to colleagues."),
  q("B1", "listening", "travel", "What caused tourism to increase?", ["A travel blog feature", "A new airport", "A government campaign", "A famous film"], "A travel blog feature",
    "You will hear:\nGuide: This region was largely unknown to tourists until 2019. Then a popular travel blog featured it, and after that, visitor numbers tripled almost overnight."),
  q("B1", "listening", "food", "What point is being made?", ["Processed foods often contain hidden sugar", "Chocolate bars are healthier than pasta", "Pasta sauce should never be eaten", "All sugar is equally harmful"], "Processed foods often contain hidden sugar",
    "You will hear:\nNutritionist: People often underestimate how much sugar is in processed foods. For example, a single jar of pasta sauce can contain the same amount of sugar as a chocolate bar. It is quite shocking."),
  q("B1", "listening", "health", "What does the doctor say about stress?", ["Small amounts can be beneficial but chronic stress is harmful", "All stress is dangerous", "Stress has no effect on the body", "Chronic stress improves performance"], "Small amounts can be beneficial but chronic stress is harmful",
    "You will hear:\nDoctor: Stress is not inherently harmful. In small doses, it can actually improve your focus and performance. The problem arises when it becomes chronic. That is when it starts to damage your health."),
  q("B1", "listening", "education", "What learning method is recommended?", ["Self-testing", "Re-reading notes", "Listening to lectures", "Highlighting text"], "Self-testing",
    "You will hear:\nProfessor: Research shows that the most effective learners are those who regularly test themselves, rather than simply re-reading their notes. Testing forces you to retrieve information actively."),
  q("B1", "listening", "technology", "What is the main benefit of smart home devices according to the expert?", ["Energy savings", "Entertainment", "Security", "Convenience"], "Energy savings",
    "You will hear:\nPresenter: So what is the real value of smart home technology?\nExpert: It is not just convenience. The real value is the energy savings they can generate through automated adjustments, like reducing heating when nobody is home."),
  q("B1", "listening", "entertainment", "What does the critic praise?", ["The quality of the writing", "The originality of the plot", "The length of the book", "The ending"], "The quality of the writing",
    "You will hear:\nCritic: I have just finished reading this novel and I must say, what makes it remarkable is not the plot, which is fairly conventional. It is the extraordinary quality of the prose. The writing is beautiful."),
  q("B1", "listening", "sports", "What helped the team succeed?", ["Tactical discipline and team spirit", "Better players", "More money", "Luck"], "Tactical discipline and team spirit",
    "You will hear:\nCommentator: What a result! Despite having fewer resources than their rivals, the team won thanks to incredible tactical discipline and team spirit. Those were the decisive factors today."),
  q("B1", "listening", "environment", "What point is the researcher making?", ["Urban beekeeping genuinely helps pollinators", "Beekeeping is just a hobby", "Rural bees are healthy", "Cities are bad for bees"], "Urban beekeeping genuinely helps pollinators",
    "You will hear:\nResearcher: Urban beekeeping is not just a trend or a hobby. Our studies show it plays a genuine role in supporting pollinator populations, especially those that are declining in rural areas due to pesticide use."),
  q("B1", "listening", "culture", "What is the historian suggesting?", ["That selective memory shapes our understanding of history", "That we should forget the past", "That history books are always accurate", "That memory is perfect"], "That selective memory shapes our understanding of history",
    "You will hear:\nHistorian: The way we remember history is fascinating. It is shaped as much by what we choose to forget as by what we choose to remember. Our collective memory is always selective."),

  q("B2", "listening", "daily_life", "What criticism is made of the gig economy?", ["It creates insecurity without traditional employment benefits", "It pays too well", "It offers too much flexibility", "It requires formal qualifications"], "It creates insecurity without traditional employment benefits",
    "You will hear:\nSociologist: The gig economy promises flexibility and freedom. But in practice, many workers find themselves trapped in a cycle of insecurity, without the benefits that traditional employment provides, such as sick pay and pensions.\nHost: So the promise does not match the reality?\nSociologist: Exactly."),
  q("B2", "listening", "travel", "What concern is raised about voluntourism?", ["It can perpetuate stereotypes and create dependency", "It is too expensive", "It requires special skills", "It takes too long"], "It can perpetuate stereotypes and create dependency",
    "You will hear:\nAnthropologist: Voluntourism is complicated. Despite its good intentions, it can perpetuate harmful stereotypes about the communities it aims to help, and it often creates dependency rather than genuine, lasting development."),
  q("B2", "listening", "food", "What point is being made about food miles?", ["That local food is not always more environmentally friendly", "That imported food is always better", "That greenhouses should be banned", "That tomatoes are bad for the environment"], "That local food is not always more environmentally friendly",
    "You will hear:\nResearcher: The concept of food miles oversimplifies things. Consider this: a locally grown tomato in a heated greenhouse during winter can have a larger carbon footprint than one shipped from a warmer climate where it grew naturally outdoors."),
  q("B2", "listening", "health", "What concern does the psychiatrist express?", ["That normal emotions are being treated as medical conditions", "That people do not take enough medicine", "That psychiatry is unnecessary", "That emotions are always pathological"], "That normal emotions are being treated as medical conditions",
    "You will hear:\nPsychiatrist: I am increasingly worried about the medicalisation of normal human emotions. We risk pathologising the full range of human experience, and creating a dependency on pharmaceutical solutions for feelings that are, in fact, perfectly normal."),
  q("B2", "listening", "education", "What limitation of standardised testing is identified?", ["It neglects skills like creativity and collaboration", "It is too easy", "It costs too much money", "It takes too long to administer"], "It neglects skills like creativity and collaboration",
    "You will hear:\nPolicy maker: Standardised testing measures what is easily quantifiable: facts, procedures, formulae. But it neglects the skills that matter most in the real world, such as creativity, critical thinking, and collaboration."),
  q("B2", "listening", "technology", "What trade-off is discussed?", ["Convenience versus impact on freedom and behaviour", "Speed versus accuracy", "Cost versus quality", "Privacy versus entertainment"], "Convenience versus impact on freedom and behaviour",
    "You will hear:\nEthicist: Facial recognition technology is undeniably convenient. But its convenience must be weighed against the chilling effect it has on public behaviour. People act differently when they know they are being watched, and that affects freedom of assembly."),
  q("B2", "listening", "entertainment", "What is the effect of algorithm-driven commissioning?", ["More broadly appealing but less creatively risky content", "Higher quality programmes", "More diverse content", "Fewer shows overall"], "More broadly appealing but less creatively risky content",
    "You will hear:\nProducer: The problem with algorithm-driven commissioning is this: we end up producing more shows that appeal to the broadest possible audience. That sounds good, but it means fewer productions that take genuine creative risks. Innovation suffers."),
  q("B2", "listening", "sports", "What problem is described?", ["Wealthy clubs circumventing salary cap rules", "Players earning too little", "Too many teams in the league", "Fans losing interest"], "Wealthy clubs circumventing salary cap rules",
    "You will hear:\nAnalyst: The salary cap was introduced to ensure competitive balance across the league. However, wealthy clubs have found various loopholes in the regulations that largely defeat its purpose. The playing field remains uneven."),
  q("B2", "listening", "environment", "What challenge is identified?", ["The political difficulty of carbon pricing", "The low cost of carbon taxes", "Public enthusiasm for carbon pricing", "The simplicity of environmental policy"], "The political difficulty of carbon pricing",
    "You will hear:\nEconomist: Putting a price on carbon is theoretically sound. Most economists agree on that. But it is politically toxic. No government wants to tell voters that the true cost of their lifestyle is much higher than they are currently paying."),
  q("B2", "listening", "culture", "What tension is identified?", ["Between global communication and linguistic diversity", "Between grammar and vocabulary", "Between writing and speaking", "Between formal and informal English"], "Between global communication and linguistic diversity",
    "You will hear:\nLinguist: English as a global lingua franca facilitates international communication, and that is valuable. But it also impoverishes the linguistic diversity that enriches human thought. Every time a language dies, we lose a unique way of understanding the world."),

  q("C1", "listening", "daily_life", "What claim is made about decision-making?", ["That most decisions are driven by unconscious cognitive biases", "That all decisions are perfectly rational", "That we should not make decisions", "That rationality is always beneficial"], "That most decisions are driven by unconscious cognitive biases",
    "You will hear:\nPhilosopher: The notion that we make rational choices is largely an illusion. Decades of research in behavioural psychology show that most decisions are driven by cognitive biases we are entirely unaware of. Our post-hoc rationalisations merely create a comforting narrative of agency.\nHost: So free will is an illusion?\nPhilosopher: I would say our sense of rational deliberation is, at least."),
  q("C1", "listening", "travel", "What argument is made about wilderness?", ["That the concept of untouched wilderness is a cultural construction", "That nature has never been affected by humans", "That all landscapes are artificial", "That wilderness should be protected"], "That the concept of untouched wilderness is a cultural construction",
    "You will hear:\nGeographer: The concept of wilderness as untouched nature is itself a cultural construction, largely a product of 19th-century Romanticism. Every landscape on Earth bears the imprint of human activity, rendering the distinction between natural and artificial fundamentally untenable."),
  q("C1", "listening", "food", "What does the historian argue about national cuisines?", ["That national cuisines are constructed rather than authentic traditions", "That all food is the same everywhere", "That 19th-century food was better", "That immigration has harmed food culture"], "That national cuisines are constructed rather than authentic traditions",
    "You will hear:\nFood historian: The notion of national cuisines is largely a 19th-century invention, bound up with the rise of nationalism. What we consider traditional dishes are often the product of global trade routes, colonial encounters, and immigrant communities. Authenticity is a myth."),
  q("C1", "listening", "health", "What ethical issue is raised?", ["The boundary between treating disease and enhancing human capabilities", "The cost of genetic testing", "Whether exercise is beneficial", "How to prescribe medication"], "The boundary between treating disease and enhancing human capabilities",
    "You will hear:\nBioethicist: The ability to edit the human genome through technologies like CRISPR raises profound ethical questions. Where does therapeutic intervention end and enhancement begin? And critically, who should have the authority to draw that line?\nInterviewer: Is there a clear answer?\nBioethicist: That is precisely the problem. There is not."),
  q("C1", "listening", "education", "What concept is discussed?", ["The hidden curriculum and its influence on students", "The importance of homework", "Why exams should be abolished", "How to improve school buildings"], "The hidden curriculum and its influence on students",
    "You will hear:\nEducation theorist: What I call the hidden curriculum, the implicit values, norms, and behaviours that schools transmit alongside the formal syllabus, may actually be more influential in shaping students than the subjects they officially study. We need to examine what we are teaching without realising it."),
  q("C1", "listening", "technology", "What does the researcher argue about the digital divide?", ["That it encompasses much more than just access to technology", "That everyone has equal access to technology", "That digital literacy is unnecessary", "That the internet should be free"], "That it encompasses much more than just access to technology",
    "You will hear:\nResearcher: The digital divide is commonly understood as a question of access. Do you have a device? Do you have an internet connection? But it encompasses far more than that. It includes digital literacy, the ability to critically evaluate information, and the capacity to leverage digital tools for genuine socioeconomic advancement."),
  q("C1", "listening", "entertainment", "What phenomenon is analysed?", ["Parasocial relationships with media figures substituting for real connections", "The popularity of reality TV", "How actors prepare for roles", "Why people watch the news"], "Parasocial relationships with media figures substituting for real connections",
    "You will hear:\nMedia theorist: The parasocial relationships audiences develop with fictional characters and media personalities fulfil genuine psychological needs for connection and belonging. However, they may also function as a substitute for the more demanding, less controllable work of building real human relationships."),
  q("C1", "listening", "sports", "What argument is made about doping?", ["That it undermines sport by removing the voluntary constraints that give it meaning", "That it should be legalised", "That it is common and acceptable", "That athletes should be free to choose"], "That it undermines sport by removing the voluntary constraints that give it meaning",
    "You will hear:\nPhilosopher: The essence of sport lies in the voluntary acceptance of unnecessary obstacles. You could drive to the finish line, but you choose to run. Remove the constraints and you remove the meaning. This is precisely why performance-enhancing drugs fundamentally undermine the entire athletic endeavour."),
  q("C1", "listening", "environment", "What tension is identified about tipping points?", ["Between the scientific reality of tipping points and the risk of fatalism", "Between optimism and pessimism", "Between governments and scientists", "Between policy and economics"], "Between the scientific reality of tipping points and the risk of fatalism",
    "You will hear:\nClimate scientist: The concept of tipping points is both scientifically crucial and rhetorically dangerous. Threshold effects are absolutely real. However, the language of irreversibility can paradoxically foster fatalism rather than action. If people believe it is too late, they stop trying."),
  q("C1", "listening", "culture", "What is argued about nostalgia?", ["That it reflects dissatisfaction with the present rather than genuine memory of the past", "That the past was always better", "That nostalgia is a mental illness", "That we should forget the past"], "That it reflects dissatisfaction with the present rather than genuine memory of the past",
    "You will hear:\nCultural theorist: Nostalgia is never truly about the past. It is a commentary on the present. It is an expression of dissatisfaction with contemporary conditions, projected onto an idealised version of what came before. The golden age we long for never actually existed."),
];

export function getBusinessEnglishQuestions(): InsertBeQuestion[] {
  const all = [...grammarQuestions, ...vocabularyQuestions, ...useOfEnglishQuestions, ...readingQuestions, ...listeningQuestions];
  return all.map(q => ({
    level: q.level,
    skillType: q.skillType,
    section: q.skillType,
    topic: q.topic,
    question: q.question,
    options: JSON.stringify(q.options),
    correctAnswer: q.correctAnswer,
    passage: q.passage || null,
    audioUrl: null,
    explanation: null,
    difficulty: q.difficulty,
    discrimination: q.discrimination,
    calibrationStatus: "calibrated",
    calibrationNotes: null,
  }));
}
