import type { InsertBeQuestion } from "@shared/schema";

interface QuestionDef {
  level: string;
  skillType: string;
  topic: string;
  question: string;
  options: string[];
  correctAnswer: string;
  passage?: string;
  difficulty: number;
  discrimination: number;
}

function q(level: string, skillType: string, topic: string, question: string, options: string[], correctAnswer: string, passage?: string): QuestionDef {
  const difficultyMap: Record<string, number> = { A0: -250, A1: -150, A2: -50, B1: 50, B2: 150, C1: 250 };
  return {
    level, skillType, topic, question, options, correctAnswer, passage,
    difficulty: difficultyMap[level] ?? 0,
    discrimination: 100,
  };
}

const grammarQuestions: QuestionDef[] = [
  q("A0", "grammar", "daily_life", "I ___ a student.", ["am", "is", "are", "be"], "am"),
  q("A0", "grammar", "travel", "She ___ from Italy.", ["is", "am", "are", "be"], "is"),
  q("A0", "grammar", "food", "They ___ hungry.", ["are", "is", "am", "be"], "are"),
  q("A0", "grammar", "health", "He ___ a doctor.", ["is", "am", "are", "be"], "is"),
  q("A0", "grammar", "education", "We ___ in the classroom.", ["are", "is", "am", "be"], "are"),
  q("A0", "grammar", "technology", "It ___ a good phone.", ["is", "am", "are", "be"], "is"),
  q("A0", "grammar", "entertainment", "I ___ not tired.", ["am", "is", "are", "be"], "am"),
  q("A0", "grammar", "sports", "The park ___ big.", ["is", "am", "are", "be"], "is"),
  q("A0", "grammar", "environment", "You ___ my friend.", ["are", "is", "am", "be"], "are"),
  q("A0", "grammar", "culture", "This ___ my book.", ["is", "am", "are", "be"], "is"),

  q("A1", "grammar", "daily_life", "She ___ to work by bus every day.", ["goes", "go", "going", "gone"], "goes"),
  q("A1", "grammar", "travel", "We ___ a vacation next month.", ["have", "has", "having", "had"], "have"),
  q("A1", "grammar", "food", "The coffee shop ___ at 7 AM.", ["opens", "open", "opening", "opened"], "opens"),
  q("A1", "grammar", "health", "I ___ exercise every morning.", ["do", "does", "doing", "did"], "do"),
  q("A1", "grammar", "education", "The class ___ at 9 AM.", ["starts", "start", "starting", "started"], "starts"),
  q("A1", "grammar", "technology", "He ___ his cell phone all the time.", ["uses", "use", "using", "used"], "uses"),
  q("A1", "grammar", "entertainment", "They ___ a movie tonight.", ["watch", "watches", "watching", "watched"], "watch"),
  q("A1", "grammar", "sports", "She ___ soccer on Saturdays.", ["plays", "play", "playing", "played"], "plays"),
  q("A1", "grammar", "environment", "It ___ a lot in England.", ["rains", "rain", "raining", "rained"], "rains"),
  q("A1", "grammar", "culture", "We ___ to visit the museum.", ["want", "wants", "wanting", "wanted"], "want"),

  q("A2", "grammar", "daily_life", "I ___ a text to my friend yesterday.", ["sent", "send", "sended", "sending"], "sent"),
  q("A2", "grammar", "travel", "We ___ about the trip last week.", ["talked", "talk", "talking", "talks"], "talked"),
  q("A2", "grammar", "food", "The cake ___ made by my grandma.", ["was", "is", "were", "been"], "was"),
  q("A2", "grammar", "health", "She ___ feeling sick since Monday.", ["has been", "is been", "was been", "have been"], "has been"),
  q("A2", "grammar", "education", "The homework ___ finished by tomorrow.", ["will be", "is", "are been", "was"], "will be"),
  q("A2", "grammar", "technology", "If you ___ the button, the screen changes.", ["press", "pressed", "pressing", "will press"], "press"),
  q("A2", "grammar", "entertainment", "The concert ___ held last Saturday.", ["was", "is", "were", "been"], "was"),
  q("A2", "grammar", "sports", "I ___ the race before it started raining.", ["finished", "finish", "finishing", "finishes"], "finished"),
  q("A2", "grammar", "environment", "He ___ recycling since last year.", ["has been", "is been", "was been", "had been"], "has been"),
  q("A2", "grammar", "culture", "They ___ the exhibition last month.", ["visited", "visit", "visiting", "visits"], "visited"),

  q("B1", "grammar", "daily_life", "If we ___ earlier, we could have caught the train.", ["had left", "left", "would leave", "have left"], "had left"),
  q("B1", "grammar", "travel", "The plane ___ by the time we got to the airport.", ["had departed", "was departing", "has departed", "departs"], "had departed"),
  q("B1", "grammar", "food", "She told me that she ___ the recipe the day before.", ["had tried", "tried", "tries", "has tried"], "had tried"),
  q("B1", "grammar", "health", "All patients ___ to wait in the waiting room.", ["are required", "is required", "requiring", "have requiring"], "are required"),
  q("B1", "grammar", "education", "The book, ___ was published in 1990, is still popular.", ["which", "who", "what", "where"], "which"),
  q("B1", "grammar", "technology", "The app ___ unless they add new features.", ["will not be updated", "not updates", "isn't updating", "doesn't update"], "will not be updated"),
  q("B1", "grammar", "entertainment", "Having ___ the movie, we talked about it over dinner.", ["watched", "watch", "watching", "been watched"], "watched"),
  q("B1", "grammar", "sports", "The game should ___ by 5 PM.", ["be finished", "finish", "finished", "be finishing"], "be finished"),
  q("B1", "grammar", "environment", "Neither the government ___ the companies took action.", ["nor", "or", "and", "but"], "nor"),
  q("B1", "grammar", "culture", "We insisted that the museum ___ open longer hours.", ["keep", "keeps", "kept", "keeping"], "keep"),

  q("B2", "grammar", "daily_life", "Had the neighbors ___ us sooner, we could have helped.", ["warned", "warn", "warning", "been warned"], "warned"),
  q("B2", "grammar", "travel", "The explorer, ___ journeys are legendary, published a new book.", ["whose", "who's", "which", "whom"], "whose"),
  q("B2", "grammar", "food", "Not until we tasted the dish ___ we realize how spicy it was.", ["did", "do", "have", "had"], "did"),
  q("B2", "grammar", "health", "The guidelines require that each person ___ a medical check-up.", ["undergo", "undergoes", "undergoing", "underwent"], "undergo"),
  q("B2", "grammar", "education", "Were the students ___ on time, the exam would have started.", ["to arrive", "arriving", "arrived", "arrives"], "to arrive"),
  q("B2", "grammar", "technology", "So rapid ___ the growth of AI that society struggled to keep up.", ["was", "is", "were", "has been"], "was"),
  q("B2", "grammar", "entertainment", "The show turned out ___ popular than anyone expected.", ["far more", "much", "very more", "so much"], "far more"),
  q("B2", "grammar", "sports", "Only after checking the replay ___ the referee change the decision.", ["did", "does", "has", "will"], "did"),
  q("B2", "grammar", "environment", "The proposal, ___ merits notwithstanding, was rejected by the council.", ["its", "it's", "whose", "which"], "its"),
  q("B2", "grammar", "culture", "Little ___ the tourists know about the real history of the place.", ["did", "do", "have", "were"], "did"),

  q("C1", "grammar", "daily_life", "Scarcely ___ the news broken when people started posting about it online.", ["had", "has", "was", "did"], "had"),
  q("C1", "grammar", "travel", "The journey, ___ challenging in parts, was ultimately rewarding.", ["albeit", "although it", "despite", "however"], "albeit"),
  q("C1", "grammar", "food", "So convinced ___ the chef of the recipe that he entered it in the competition.", ["was", "were", "is", "has been"], "was"),
  q("C1", "grammar", "health", "It is imperative that the government ___ its public health programmes.", ["strengthen", "strengthens", "strengthened", "strengthening"], "strengthen"),
  q("C1", "grammar", "education", "Not only ___ the funding been cut, but courses had also been cancelled.", ["had", "has", "was", "did"], "had"),
  q("C1", "grammar", "technology", "The invention, ___ it to succeed, would fundamentally change communication.", ["were", "was", "should", "if"], "were"),
  q("C1", "grammar", "entertainment", "Under no circumstances ___ personal recordings be shared online.", ["should", "shall", "would", "could"], "should"),
  q("C1", "grammar", "sports", "The match, the outcome of ___ remains disputed, was replayed.", ["which", "that", "what", "whom"], "which"),
  q("C1", "grammar", "environment", "Notwithstanding the concerns ___ by several scientists, the project went ahead.", ["raised", "raising", "to raise", "having raised"], "raised"),
  q("C1", "grammar", "culture", "Had the community been ___ to compromise, the conflict would have ended sooner.", ["willing", "willing be", "willingly", "willed"], "willing"),
];

const vocabularyQuestions: QuestionDef[] = [
  q("A0", "vocabulary", "daily_life", "A 'house' is a place where people ___.", ["live", "work", "swim", "fly"], "live"),
  q("A0", "vocabulary", "travel", "A 'passport' is needed to ___ to another country.", ["travel", "eat", "sleep", "read"], "travel"),
  q("A0", "vocabulary", "food", "A 'kitchen' is a room where you ___.", ["cook food", "sleep", "swim", "drive"], "cook food"),
  q("A0", "vocabulary", "health", "A 'hospital' is a place for ___ people.", ["sick", "happy", "fast", "tall"], "sick"),
  q("A0", "vocabulary", "education", "A 'school' is a place where children ___.", ["learn", "cook", "sleep", "drive"], "learn"),
  q("A0", "vocabulary", "technology", "A 'computer' is used to ___.", ["work and play", "cook food", "grow plants", "drive cars"], "work and play"),
  q("A0", "vocabulary", "entertainment", "A 'movie theater' (or 'cinema') is a place where you watch ___.", ["films", "sports", "birds", "clouds"], "films"),
  q("A0", "vocabulary", "sports", "A 'ball' is used in many ___.", ["sports", "kitchens", "hospitals", "libraries"], "sports"),
  q("A0", "vocabulary", "environment", "A 'tree' is a big ___.", ["plant", "animal", "rock", "cloud"], "plant"),
  q("A0", "vocabulary", "culture", "'Music' is something you ___ to.", ["listen", "eat", "wear", "drink"], "listen"),

  q("A1", "vocabulary", "daily_life", "I need to ___ the bus to get to work.", ["catch", "cook", "build", "grow"], "catch"),
  q("A1", "vocabulary", "travel", "We need to ___ a hotel room for our vacation.", ["book", "bake", "plant", "swim"], "book"),
  q("A1", "vocabulary", "food", "The soup tastes too ___. It needs more salt.", ["bland", "loud", "bright", "heavy"], "bland"),
  q("A1", "vocabulary", "health", "She went to the ___ because she had a bad cough.", ["doctor", "teacher", "waiter", "driver"], "doctor"),
  q("A1", "vocabulary", "education", "The teacher asked us to ___ the exercise.", ["complete", "compete", "complain", "compare"], "complete"),
  q("A1", "vocabulary", "technology", "You need a ___ to connect to the wifi.", ["password", "passport", "postcard", "package"], "password"),
  q("A1", "vocabulary", "entertainment", "The ___ was really funny and everyone laughed.", ["comedy", "tragedy", "drama", "mystery"], "comedy"),
  q("A1", "vocabulary", "sports", "The ___ scored the winning goal in the last minute.", ["striker", "singer", "driver", "painter"], "striker"),
  q("A1", "vocabulary", "environment", "We should ___ plastic bottles to help the environment.", ["recycle", "receive", "recover", "remove"], "recycle"),
  q("A1", "vocabulary", "culture", "The ___ is open from 10 AM to 6 PM.", ["museum", "bathroom", "bedroom", "classroom"], "museum"),

  q("A2", "vocabulary", "daily_life", "I would like to ___ a complaint about the noise.", ["make", "take", "get", "put"], "make"),
  q("A2", "vocabulary", "travel", "The flight was ___ because of bad weather.", ["delayed", "deleted", "designed", "delivered"], "delayed"),
  q("A2", "vocabulary", "food", "This restaurant is famous for its ___ cooking.", ["traditional", "transitional", "transparent", "temporary"], "traditional"),
  q("A2", "vocabulary", "health", "The doctor ___ some medicine for my cold.", ["prescribed", "presented", "preserved", "prevented"], "prescribed"),
  q("A2", "vocabulary", "education", "We need to ___ for the exam next week.", ["revise", "reverse", "revolve", "reveal"], "revise"),
  q("A2", "vocabulary", "technology", "You can ___ the app to your phone.", ["download", "downgrade", "downsize", "downplay"], "download"),
  q("A2", "vocabulary", "entertainment", "The book was so ___ that I could not put it down.", ["gripping", "grabbing", "grinding", "grooming"], "gripping"),
  q("A2", "vocabulary", "sports", "The team ___ their opponents 3-1 in the final.", ["defeated", "defended", "defined", "delayed"], "defeated"),
  q("A2", "vocabulary", "environment", "Air ___ is a major problem in big cities.", ["pollution", "position", "portion", "potion"], "pollution"),
  q("A2", "vocabulary", "culture", "The ___ attracted thousands of visitors from all over.", ["festival", "factory", "facility", "faculty"], "festival"),

  q("B1", "vocabulary", "daily_life", "She has a very ___ personality and makes friends easily.", ["outgoing", "outgoing", "outstanding", "outrageous"], "outgoing"),
  q("B1", "vocabulary", "travel", "The views from the mountain top were absolutely ___.", ["breathtaking", "breathless", "breaching", "breaking"], "breathtaking"),
  q("B1", "vocabulary", "food", "The chef uses only ___ grown ingredients in his dishes.", ["locally", "loudly", "loosely", "lonely"], "locally"),
  q("B1", "vocabulary", "health", "Regular exercise helps to ___ stress and anxiety.", ["relieve", "receive", "retrieve", "release"], "relieve"),
  q("B1", "vocabulary", "education", "The university offers a wide ___ of courses.", ["range", "rank", "rate", "ratio"], "range"),
  q("B1", "vocabulary", "technology", "The company plans to ___ a new version of the app.", ["launch", "latch", "lean", "leak"], "launch"),
  q("B1", "vocabulary", "entertainment", "The movie got ___ reviews from the critics.", ["mixed", "fixed", "pixelated", "maxed"], "mixed"),
  q("B1", "vocabulary", "sports", "The athlete showed incredible ___ throughout the competition.", ["determination", "destination", "decoration", "delegation"], "determination"),
  q("B1", "vocabulary", "environment", "The government introduced new laws to ___ wildlife.", ["protect", "project", "prospect", "protest"], "protect"),
  q("B1", "vocabulary", "culture", "The painting is considered a ___ of Renaissance art.", ["masterpiece", "manuscript", "manifesto", "marathon"], "masterpiece"),

  q("B2", "vocabulary", "daily_life", "The new rules have had ___ impact on how people live.", ["a profound", "a profuse", "a prolonged", "a provocative"], "a profound"),
  q("B2", "vocabulary", "travel", "The remote village is ___ only by a narrow mountain road.", ["accessible", "assessable", "acceptable", "achievable"], "accessible"),
  q("B2", "vocabulary", "food", "The dish has a ___ blend of Eastern and Western flavors.", ["subtle", "suburban", "subsequent", "submarine"], "subtle"),
  q("B2", "vocabulary", "health", "Obesity is increasingly ___ in modern society.", ["prevalent", "preventive", "predictive", "premature"], "prevalent"),
  q("B2", "vocabulary", "education", "The research ___ previous findings about learning styles.", ["corroborates", "contradicts", "constitutes", "consolidates"], "corroborates"),
  q("B2", "vocabulary", "technology", "The app was designed to ___ the user experience.", ["enhance", "enforce", "endure", "enlarge"], "enhance"),
  q("B2", "vocabulary", "entertainment", "Her ___ performance earned her a standing ovation.", ["compelling", "competing", "complying", "comparing"], "compelling"),
  q("B2", "vocabulary", "sports", "The team showed remarkable ___ after falling behind in the first half.", ["resilience", "resemblance", "residence", "resistance"], "resilience"),
  q("B2", "vocabulary", "environment", "Deforestation has led to ___ consequences for wildlife.", ["devastating", "decorative", "deliberate", "delightful"], "devastating"),
  q("B2", "vocabulary", "culture", "The exhibition ___ the evolution of modern art over the past century.", ["traces", "tracks", "trails", "trades"], "traces"),

  q("C1", "vocabulary", "daily_life", "The council's decision to close the library was met with ___ opposition.", ["vehement", "venerable", "versatile", "vulnerable"], "vehement"),
  q("C1", "vocabulary", "travel", "The region's ___ coastline attracts photographers from all over the world.", ["rugged", "ragged", "rigged", "ridged"], "rugged"),
  q("C1", "vocabulary", "food", "The food critic described the meal as ___.", ["exquisite", "exhaustive", "exclusive", "excessive"], "exquisite"),
  q("C1", "vocabulary", "health", "The research highlights the ___ relationship between diet and mental health.", ["intricate", "intrinsic", "intrepid", "intra"], "intricate"),
  q("C1", "vocabulary", "education", "The professor's lecture was both ___ and thought-provoking.", ["erudite", "erratic", "erroneous", "erosive"], "erudite"),
  q("C1", "vocabulary", "technology", "Market ___ has made traditional forecasting models useless.", ["volatility", "validity", "visibility", "viability"], "volatility"),
  q("C1", "vocabulary", "entertainment", "The playwright's ___ wit shone through every scene.", ["sardonic", "sanguine", "sedentary", "sporadic"], "sardonic"),
  q("C1", "vocabulary", "sports", "The athlete's ___ in the face of adversity inspired millions.", ["tenacity", "tendency", "tangibility", "transparency"], "tenacity"),
  q("C1", "vocabulary", "environment", "The ___ effects of climate change are becoming increasingly clear.", ["deleterious", "deliberate", "delightful", "democratic"], "deleterious"),
  q("C1", "vocabulary", "culture", "The composer's ___ use of silence was as powerful as the music itself.", ["judicious", "jubilant", "juvenile", "judicial"], "judicious"),
];

const useOfEnglishQuestions: QuestionDef[] = [
  q("A0", "use_of_english", "daily_life", "'Good morning' is a way to say ___.", ["hello", "goodbye", "thank you", "sorry"], "hello"),
  q("A0", "use_of_english", "travel", "When someone says 'Thanks', you can say ___.", ["You're welcome", "I'm sorry", "Goodbye", "Good night"], "You're welcome"),
  q("A0", "use_of_english", "food", "'How much is it?' asks about the ___.", ["price", "time", "color", "name"], "price"),
  q("A0", "use_of_english", "health", "'How are you?' asks about how someone ___.", ["feels", "works", "eats", "sleeps"], "feels"),
  q("A0", "use_of_english", "education", "'Where is it?' asks about a ___.", ["place", "time", "person", "reason"], "place"),
  q("A0", "use_of_english", "technology", "To say the time '3:00', we say ___.", ["three o'clock", "three hours", "o'clock three", "clock three"], "three o'clock"),
  q("A0", "use_of_english", "entertainment", "'I like it' means you think it is ___.", ["good", "bad", "ugly", "wrong"], "good"),
  q("A0", "use_of_english", "sports", "In English, Monday is a ___.", ["day", "month", "year", "number"], "day"),
  q("A0", "use_of_english", "environment", "'Please' is used when you ___ something.", ["ask for", "give away", "throw away", "take away"], "ask for"),
  q("A0", "use_of_english", "culture", "'Yes or no?' is a ___.", ["question", "answer", "name", "number"], "question"),

  q("A1", "use_of_english", "daily_life", "Which is a good way to end a friendly email?", ["Best wishes", "Yours faithfully", "To whom it may concern", "Dear Sir"], "Best wishes"),
  q("A1", "use_of_english", "travel", "'Excuse me, where's the nearest subway?' is a way to ___.", ["ask for directions", "order food", "buy clothes", "introduce yourself"], "ask for directions"),
  q("A1", "use_of_english", "food", "'Can I get the check, please?' or 'Can I have the bill?' is used at the end of a ___.", ["meal", "lesson", "game", "film"], "meal"),
  q("A1", "use_of_english", "health", "'I've got a headache' means your ___ hurts.", ["head", "hand", "heart", "hip"], "head"),
  q("A1", "use_of_english", "education", "'Homework' is work you do at ___.", ["home", "school", "the park", "the shop"], "home"),
  q("A1", "use_of_english", "technology", "'To log in' means to ___ your account.", ["enter", "exit", "delete", "create"], "enter"),
  q("A1", "use_of_english", "entertainment", "A 'bestseller' is a book that ___ really well.", ["sells", "smells", "spells", "swells"], "sells"),
  q("A1", "use_of_english", "sports", "A 'draw' or 'tie' in soccer means the score is ___.", ["equal", "different", "wrong", "high"], "equal"),
  q("A1", "use_of_english", "environment", "'To save water' means to ___ less water.", ["use", "drink", "boil", "sell"], "use"),
  q("A1", "use_of_english", "culture", "A 'gallery' is a place where you can see ___.", ["art", "animals", "food", "cars"], "art"),

  q("A2", "use_of_english", "daily_life", "'I'd appreciate it if you could...' is a polite way to ___.", ["make a request", "give an order", "express anger", "say goodbye"], "make a request"),
  q("A2", "use_of_english", "travel", "'To check in' at a hotel means to ___.", ["register your arrival", "pay your bill", "clean your room", "leave the hotel"], "register your arrival"),
  q("A2", "use_of_english", "food", "'I'm full' or 'I'm stuffed' after eating means you ___.", ["cannot eat any more", "are still hungry", "want dessert", "feel sick"], "cannot eat any more"),
  q("A2", "use_of_english", "health", "'Over-the-counter' medicine means you can buy it ___.", ["without a prescription", "only in hospitals", "only online", "only with a doctor's note"], "without a prescription"),
  q("A2", "use_of_english", "education", "A 'semester' or 'term' at school is a ___ of the year.", ["period", "problem", "product", "project"], "period"),
  q("A2", "use_of_english", "technology", "'To go viral' means something ___ very quickly online.", ["spreads", "stops", "shrinks", "sleeps"], "spreads"),
  q("A2", "use_of_english", "entertainment", "'A spoiler' gives away the ___ of a story.", ["ending", "beginning", "author", "title"], "ending"),
  q("A2", "use_of_english", "sports", "'A warm-up' is done ___ exercise.", ["before", "after", "during", "instead of"], "before"),
  q("A2", "use_of_english", "environment", "'Renewable energy' comes from sources that ___.", ["do not run out", "are very expensive", "cause pollution", "are underground"], "do not run out"),
  q("A2", "use_of_english", "culture", "'Heritage' refers to traditions passed down from ___ generations.", ["previous", "future", "modern", "current"], "previous"),

  q("B1", "use_of_english", "daily_life", "The expression 'at the end of the day' means ___.", ["ultimately / when everything is considered", "in the evening", "at closing time", "when the sun sets"], "ultimately / when everything is considered"),
  q("B1", "use_of_english", "travel", "'Off the beaten track' (or 'off the beaten path') describes a place that is ___.", ["not well known by tourists", "dangerous", "very crowded", "close to the airport"], "not well known by tourists"),
  q("B1", "use_of_english", "food", "'From scratch' means to make something ___.", ["from the very beginning using basic ingredients", "very quickly", "using a recipe book", "in a restaurant"], "from the very beginning using basic ingredients"),
  q("B1", "use_of_english", "health", "'To feel under the weather' means to feel ___.", ["slightly ill", "very happy", "very cold", "extremely tired"], "slightly ill"),
  q("B1", "use_of_english", "education", "'To learn by heart' (or 'to memorize') means to ___.", ["remember something completely", "study with emotion", "enjoy learning", "learn slowly"], "remember something completely"),
  q("B1", "use_of_english", "technology", "'User-friendly' means something is ___.", ["easy to use", "free of charge", "made by users", "very expensive"], "easy to use"),
  q("B1", "use_of_english", "entertainment", "'A page-turner' is a book that is ___.", ["very exciting and hard to stop reading", "very boring", "very long", "very expensive"], "very exciting and hard to stop reading"),
  q("B1", "use_of_english", "sports", "'A level playing field' means conditions are ___.", ["fair and equal for everyone", "flat and green", "competitive", "difficult for all"], "fair and equal for everyone"),
  q("B1", "use_of_english", "environment", "'Carbon footprint' refers to the amount of ___.", ["greenhouse gases produced by your activities", "carbon in the soil", "feet on carbon surfaces", "carbon in food"], "greenhouse gases produced by your activities"),
  q("B1", "use_of_english", "culture", "'Melting pot' describes a place where ___.", ["many different cultures mix together", "metal is heated", "food is cooked", "ice cream is made"], "many different cultures mix together"),

  q("B2", "use_of_english", "daily_life", "'To read between the lines' means to ___.", ["understand the hidden meaning", "read very slowly", "read aloud", "skip some paragraphs"], "understand the hidden meaning"),
  q("B2", "use_of_english", "travel", "'To live out of a suitcase' means to ___.", ["travel frequently without settling down", "have very few belongings", "live in a hotel permanently", "pack very carefully"], "travel frequently without settling down"),
  q("B2", "use_of_english", "food", "'An acquired taste' is something that ___.", ["you learn to enjoy over time", "everyone likes right away", "tastes terrible", "is very expensive"], "you learn to enjoy over time"),
  q("B2", "use_of_english", "health", "'Prevention is better than cure' means ___.", ["it is better to stop problems before they start", "medicine is unnecessary", "doctors are not helpful", "illness is avoidable"], "it is better to stop problems before they start"),
  q("B2", "use_of_english", "education", "A 'steep learning curve' means something is ___.", ["difficult to learn at first", "easy to master", "impossible to understand", "boring to study"], "difficult to learn at first"),
  q("B2", "use_of_english", "technology", "'Cutting-edge technology' refers to technology that is ___.", ["the most advanced and newest available", "very old and reliable", "cheap and widely available", "dangerous and untested"], "the most advanced and newest available"),
  q("B2", "use_of_english", "entertainment", "'Typecasting' in acting means ___.", ["always being given similar roles", "typing scripts quickly", "casting votes", "being a type of actor"], "always being given similar roles"),
  q("B2", "use_of_english", "sports", "'Moving the goalposts' means to ___.", ["change the rules or conditions unfairly", "rearrange the football pitch", "score a winning goal", "train harder"], "change the rules or conditions unfairly"),
  q("B2", "use_of_english", "environment", "'Greenwashing' is when a company ___.", ["falsely claims to be environmentally friendly", "uses green paint", "cleans the environment", "recycles its products"], "falsely claims to be environmentally friendly"),
  q("B2", "use_of_english", "culture", "'Cultural appropriation' refers to ___.", ["adopting elements of another culture without respect", "appreciating art", "travelling abroad", "learning a new language"], "adopting elements of another culture without respect"),

  q("C1", "use_of_english", "daily_life", "'To have one's cake and eat it too' means to ___.", ["want to enjoy two incompatible benefits", "eat too much", "share food generously", "celebrate a birthday"], "want to enjoy two incompatible benefits"),
  q("C1", "use_of_english", "travel", "'Wanderlust' describes a strong desire to ___.", ["travel and explore the world", "stay at home", "read travel books", "collect maps"], "travel and explore the world"),
  q("C1", "use_of_english", "food", "'Gastronomic' relates to the art of ___.", ["fine cooking and eating", "fast food preparation", "food photography", "grocery shopping"], "fine cooking and eating"),
  q("C1", "use_of_english", "health", "'Psychosomatic' describes a physical illness caused by ___.", ["mental or emotional factors", "bacteria", "physical injury", "poor diet"], "mental or emotional factors"),
  q("C1", "use_of_english", "education", "'Pedagogy' refers to ___.", ["the method and practice of teaching", "the study of children", "school architecture", "educational technology"], "the method and practice of teaching"),
  q("C1", "use_of_english", "technology", "'Ubiquitous computing' means technology that is ___.", ["present everywhere in daily life", "very expensive", "only used by experts", "always connected to the internet"], "present everywhere in daily life"),
  q("C1", "use_of_english", "entertainment", "'Avant-garde' in art describes work that is ___.", ["experimental and pushing boundaries", "traditional and classical", "simple and minimalist", "commercial and popular"], "experimental and pushing boundaries"),
  q("C1", "use_of_english", "sports", "'To rest on one's laurels' means to ___.", ["stop trying after achieving success", "take a nap after exercise", "win a prize", "celebrate a victory"], "stop trying after achieving success"),
  q("C1", "use_of_english", "environment", "'Anthropocene' refers to the current era defined by ___.", ["significant human impact on the Earth", "ancient rock formations", "ice ages", "volcanic activity"], "significant human impact on the Earth"),
  q("C1", "use_of_english", "culture", "'Zeitgeist' refers to the ___.", ["spirit or mood of a particular period", "German word for clock", "latest fashion trend", "political system"], "spirit or mood of a particular period"),
];

const readingQuestions: QuestionDef[] = [
  q("A0", "reading", "daily_life", "What does the notice say?", ["The shop is closed today", "The park is open all day", "You can buy lunch here", "School starts at 8 AM"],
    "The shop is closed today",
    "NOTICE\nThis shop is closed today.\nSorry for any trouble.\nWe open again tomorrow at 9 AM."),
  q("A0", "reading", "food", "What does the menu say?", ["Soup costs two dollars", "Pizza is free", "The restaurant is closed", "No food today"],
    "Soup costs two dollars",
    "TODAY'S MENU\nSoup: $2.00\nSandwich: $3.50\nCoffee: $1.50"),
  q("A0", "reading", "health", "What does the sign say?", ["No smoking here", "Free food inside", "Open 24 hours", "Parking available"],
    "No smoking here",
    "NO SMOKING\nPlease do not smoke in this area.\nThank you."),
  q("A0", "reading", "travel", "When does the train leave?", ["At 10 AM", "At night", "On Sunday", "Never"],
    "At 10 AM",
    "TRAIN SCHEDULE\nLondon to Oxford: 10:00 AM\nPlatform 3"),
  q("A0", "reading", "education", "What is Maria's hobby?", ["She likes painting", "She likes cooking", "She likes swimming", "She likes singing"],
    "She likes painting",
    "My name is Maria. I am 12 years old. I like painting. I paint every weekend."),
  q("A0", "reading", "environment", "What should we do?", ["Save water", "Buy more water", "Use hot water", "Drink only water"],
    "Save water",
    "SAVE WATER\nPlease turn off the faucet when you brush your teeth.\nEvery drop counts."),
  q("A0", "reading", "sports", "When is the soccer game?", ["On Saturday at 3 PM", "On Monday at 9 AM", "On Friday night", "Every day"],
    "On Saturday at 3 PM",
    "SOCCER MATCH\nSaturday, 3 PM\nCity Stadium\nTickets: $5"),
  q("A0", "reading", "technology", "What is the wifi password?", ["abc123", "The shop is closed", "Call us tomorrow", "No parking"],
    "abc123",
    "WIFI\nNetwork: Library_Free\nPassword: abc123"),
  q("A0", "reading", "entertainment", "What movie is showing?", ["Happy Days at 7 PM", "A scary film at midnight", "No movies today", "Three films at once"],
    "Happy Days at 7 PM",
    "CINEMA\nTonight: Happy Days\nTime: 7:00 PM\nTickets: $8"),
  q("A0", "reading", "culture", "What day is the museum free?", ["Sunday", "Monday", "Every day", "Never"],
    "Sunday",
    "CITY MUSEUM\nOpen: Tuesday to Sunday\nFree admission on Sundays"),

  q("A1", "reading", "daily_life", "What is the message about?", ["An invitation to a birthday party", "Cancelling plans", "A noise complaint", "Asking for help moving"],
    "An invitation to a birthday party",
    "Hey Tom,\nI'm having a birthday party this Saturday at my place at 6 PM. Wanna come? There'll be cake and music!\nSee you there,\nAnna"),
  q("A1", "reading", "travel", "What does the sign say about the hotel?", ["Breakfast is included", "The pool is closed", "Rooms are not available", "Check-out is at 8 AM"],
    "Breakfast is included",
    "WELCOME TO HOTEL SUNRISE\nBreakfast included: 7:00 - 10:00 AM\nWifi: Free in all rooms\nCheck-out: 11:00 AM"),
  q("A1", "reading", "food", "What did the reviewer think of the restaurant?", ["The food was great but pricey", "The service was terrible", "The restaurant was closed", "The music was too loud"],
    "The food was great but pricey",
    "Restaurant Review: La Bella\nThe pasta was amazing and the desserts were great. But the prices are kinda high. A main course is about $25. Worth it for a special night out."),
  q("A1", "reading", "health", "What advice does the article give?", ["Drink 8 glasses of water a day", "Avoid all fruit", "Sleep only 4 hours", "Never exercise"],
    "Drink 8 glasses of water a day",
    "HEALTH TIPS\nDoctors say you should drink at least 8 glasses of water every day. It helps your body stay healthy and gives you more energy."),
  q("A1", "reading", "education", "What does the notice say?", ["The library is open late this week", "The library is closed for good", "Books are free to keep", "Students can't use computers"],
    "The library is open late this week",
    "LIBRARY NOTICE\nDuring exam week (March 10-15), the library will stay open until 9 PM. Normal hours start again on March 16."),
  q("A1", "reading", "technology", "What is the email about?", ["A new app update", "A broken computer", "A stolen phone", "A cancelled subscription"],
    "A new app update",
    "Hi there,\nA new update is ready for your app. Please update to version 3.0 for cool new features and better performance.\nGet it from the app store today!"),
  q("A1", "reading", "entertainment", "What is happening this weekend?", ["A free outdoor concert", "A movie theater closing", "A book sale", "A sports event"],
    "A free outdoor concert",
    "WEEKEND EVENTS\nFree outdoor concert in Central Park\nSaturday, 4 PM\nBring a blanket and enjoy live music!"),
  q("A1", "reading", "sports", "What does the notice say?", ["Swimming lessons are available for kids", "The pool is closed forever", "Only adults can swim", "Swimming is dangerous"],
    "Swimming lessons are available for kids",
    "SWIMMING LESSONS\nFor kids aged 6-12\nEvery Wednesday, 4:00 - 5:00 PM\nCost: $10 per session\nSign up at the front desk"),
  q("A1", "reading", "environment", "What does the poster say?", ["Plant a tree this spring", "Cut down old trees", "Trees are not important", "Forests are disappearing"],
    "Plant a tree this spring",
    "PLANT A TREE\nJoin our tree-planting event this spring!\nDate: April 5\nMeeting point: City Park entrance\nEveryone's welcome!"),
  q("A1", "reading", "culture", "What is the exhibition about?", ["Ancient Egyptian art", "Modern photography", "Local food recipes", "Children's drawings"],
    "Ancient Egyptian art",
    "NEW EXHIBITION\nAncient Egypt: Art and Life\nNational Museum, Gallery 3\nJanuary 15 - March 30\nAdults: $12 / Students: $6"),

  q("A2", "reading", "daily_life", "What is the writer's main advice?", ["Start saving money as early as you can", "Spend money on experiences", "Avoid bank accounts", "Borrow from friends"],
    "Start saving money as early as you can",
    "Money Tips for Young Adults\nOne of the smartest things you can do is start saving money as early as possible. Even putting aside a small amount each month makes a big difference over time. Most experts say you should save at least 10% of what you earn."),
  q("A2", "reading", "travel", "What happened on the trip?", ["The travelers missed their connecting flight", "The hotel was overbooked", "The luggage was lost forever", "The trip was cancelled"],
    "The travelers missed their connecting flight",
    "Travel Blog: A Trip to Remember\nOur journey started badly when we missed our connecting flight in Frankfurt because of a 30-minute delay from London. The airline put us on the next flight three hours later and gave us meal vouchers. We finally got to Rome at midnight, tired but excited."),
  q("A2", "reading", "food", "What does the article say about the Mediterranean diet?", ["It can lower the risk of heart disease", "It makes you gain weight", "It is only for Italian people", "It is too expensive for most people"],
    "It can lower the risk of heart disease",
    "Health & Food: The Mediterranean Diet\nStudies show that the Mediterranean diet, rich in olive oil, fish, veggies, and whole grains, can significantly lower the risk of heart disease. Researchers followed 7,500 people over five years and found a 30% lower risk among those who ate this way."),
  q("A2", "reading", "health", "What does the article recommend?", ["Getting at least 7 hours of sleep a night", "Sleeping only when tired", "Taking sleeping pills regularly", "Skipping sleep on weekends"],
    "Getting at least 7 hours of sleep a night",
    "Sleep and Health\nResearch shows that adults need at least 7 hours of sleep per night. Not getting enough sleep is linked to weight gain, a weaker immune system, and trouble concentrating. Experts suggest having a regular bedtime and avoiding screens before bed."),
  q("A2", "reading", "education", "What change is being made?", ["A new language requirement for all students", "Shorter school days", "More homework", "Fewer tests"],
    "A new language requirement for all students",
    "To: All Students and Parents\nSubject: New Language Policy\nStarting in September, all students will need to study at least two foreign languages until age 16. This reflects our goal to prepare students for an increasingly global world."),
  q("A2", "reading", "technology", "What is the article about?", ["How phones affect sleep quality", "How to fix a phone", "The most expensive phones", "Phone games for kids"],
    "How phones affect sleep quality",
    "Digital Wellbeing\nA new study from Oxford found that using your phone before bed can reduce sleep quality by up to 20%. The blue light from screens suppresses melatonin, making it harder to fall asleep. Experts say you should put your devices away at least an hour before bedtime."),
  q("A2", "reading", "entertainment", "What does the review say?", ["The book is worth reading even though it's long", "The book is too short", "The author is unknown", "The book has no plot"],
    "The book is worth reading even though it's long",
    "Book Review: The Silent Road\nAt over 500 pages, this novel takes patience, but it rewards you with a beautifully written story of family and forgiveness. The characters feel real and the ending is deeply satisfying. Highly recommended for anyone who enjoys a good read."),
  q("A2", "reading", "sports", "What happened in the game?", ["The underdog team won in the last minute", "Both teams tied", "The game was cancelled", "Nobody scored"],
    "The underdog team won in the last minute",
    "Sports News: Incredible Final!\nIn one of the most dramatic finals in years, underdog FC Estrela scored in the 94th minute to beat last year's champs 2-1. Their coach called it 'the greatest moment of my career'. Over 60,000 fans went wild in the stadium."),
  q("A2", "reading", "environment", "What does the report say?", ["Plastic waste in the oceans has doubled in ten years", "The oceans are getting cleaner", "Plastic is no longer a problem", "Fish populations are growing"],
    "Plastic waste in the oceans has doubled in ten years",
    "Environmental Report\nAccording to a new UN report, plastic waste in the world's oceans has doubled over the last ten years. About 8 million tons of plastic end up in the oceans every year, threatening sea life. The report calls for urgent action."),
  q("A2", "reading", "culture", "What does the article discuss?", ["How traditional festivals help keep local culture alive", "Why festivals should be cancelled", "The cost of organizing festivals", "Festival food safety rules"],
    "How traditional festivals help keep local culture alive",
    "Culture & Society\nTraditional festivals play a big role in keeping local culture alive. From Carnival in Venice to Diwali in India, these celebrations bring people together and pass traditions from one generation to the next. They also boost local businesses through tourism."),

  q("B1", "reading", "daily_life", "What is the main point of the article?", ["That walking 30 minutes daily can really improve mental health", "That running is better than walking", "That exercise is pointless", "That only young people should exercise"],
    "That walking 30 minutes daily can really improve mental health",
    "A study in the British Medical Journal followed 10,000 adults over three years and found that those who walked briskly for at least 30 minutes a day had 40% fewer symptoms of anxiety and depression than those who didn't. The researchers said that even moderate activity, when done regularly, can have a big impact on how you feel mentally."),
  q("B1", "reading", "travel", "What does the article suggest about sustainable tourism?", ["That travelers should choose local places to stay and local transport", "That flying is the greenest option", "That luxury resorts are eco-friendly", "That tourism should be banned"],
    "That travelers should choose local places to stay and local transport",
    "Sustainable Tourism: A Growing Trend\nMore and more travelers are choosing greener options when planning trips. Experts recommend staying in locally owned places rather than big hotel chains, using public transit, and supporting local businesses. A recent survey found that 58% of travelers under 35 think about the environmental impact when booking. Even small things, like carrying a reusable water bottle, can help."),
  q("B1", "reading", "food", "What did the study find?", ["That kids who cook with their parents eat more veggies", "That kids prefer junk food", "That cooking is too dangerous for kids", "That parents shouldn't let kids in the kitchen"],
    "That kids who cook with their parents eat more veggies",
    "A study by the University of Alberta found that kids who regularly help make meals at home eat 25% more vegetables than those who don't. Researchers watched 150 families for 12 months and concluded that getting children involved in cooking from a young age helps them develop healthier eating habits. They recommend simple cooking tasks for kids as young as five."),
  q("B1", "reading", "health", "What health risk is highlighted?", ["Sitting too much increases the risk of heart disease", "Eating too much fruit is dangerous", "Sleeping too much causes headaches", "Running causes joint damage"],
    "Sitting too much increases the risk of heart disease",
    "Health Warning: The Dangers of Sitting\nNew research shows that sitting for more than 8 hours a day without moving around raises the risk of heart disease by 35%. The study tracked 50,000 office workers over five years and found that even hitting the gym regularly can't fully make up for sitting all day. Health experts say you should stand up for at least 5 minutes every hour."),
  q("B1", "reading", "education", "What approach does the article recommend?", ["Mixing traditional teaching with technology", "Replacing teachers with computers", "Banning tech in classrooms", "Only using textbooks"],
    "Mixing traditional teaching with technology",
    "Education in the Digital Age\nSchools that mix traditional teaching with tech are seeing real improvements. A three-year study across 200 European schools found that students in blended learning settings scored 15% higher on tests than those in traditional-only classrooms. But researchers warn that technology should support teachers, not replace them."),
  q("B1", "reading", "technology", "What concern does the article raise?", ["That AI could replace many jobs in the next decade", "That AI is totally harmless", "That technology is getting slower", "That computers are getting cheaper"],
    "That AI could replace many jobs in the next decade",
    "The Future of Work and AI\nA World Economic Forum report predicts that AI could automate up to 40% of routine tasks done by humans within the next 10 years. While AI will create new types of jobs, there's growing worry that many workers, especially in admin and manufacturing, might not have the skills to make the switch. Governments are being urged to invest in retraining programs."),
  q("B1", "reading", "entertainment", "What does the article say about streaming?", ["It has completely changed how people watch things", "It is less popular than going to the movies", "It only shows old content", "It is about to shut down"],
    "It has completely changed how people watch things",
    "The Rise of Streaming\nStreaming platforms have completely changed entertainment. Global subscriptions hit 1.5 billion in 2025, with the average person watching 3.5 hours of content a day. While movie theaters have struggled, streaming has given independent filmmakers opportunities they never had before. Some critics say, though, that quality has dropped because of the rush to produce more and more content."),
  q("B1", "reading", "sports", "What does the research show?", ["That team sports improve social skills more than individual sports", "That individual sports are always better", "That sport doesn't matter for kids", "That competitive sports should be banned for kids"],
    "That team sports improve social skills more than individual sports",
    "Sport and Social Development\nCambridge University researchers found that kids who play team sports develop much better social skills than those who only do individual sports. They followed 3,000 children aged 8-14 for four years and found that team sport players scored 30% higher in cooperation, communication, and conflict resolution. They recommend schools offer a mix of both."),
  q("B1", "reading", "environment", "What solution is proposed?", ["Creating green spaces in cities to fight air pollution", "Building more highways", "Shutting down all factories", "Moving everyone to the countryside"],
    "Creating green spaces in cities to fight air pollution",
    "Green Cities Initiative\nMore and more research supports creating green spaces in cities as a way to fight air pollution. Trees and plants naturally filter pollutants, and studies show that neighborhoods with more green areas have 20% lower levels of harmful particles in the air. Cities like Milan and Singapore have pioneered vertical gardens and rooftop forests, showing that even crowded cities can benefit from nature-based solutions."),
  q("B1", "reading", "culture", "What does the article argue?", ["That speaking two languages has brain benefits that last into old age", "That learning languages is a waste of time", "That people who speak one language are smarter", "That kids should only learn one language"],
    "That speaking two languages has brain benefits that last into old age",
    "The Bilingual Brain\nResearch in the journal Neurology shows that people who speak two or more languages develop symptoms of dementia an average of 4.5 years later than those who speak just one. Scientists think that switching between languages regularly strengthens the brain's ability to focus, solve problems, and stay flexible. Bilingualism acts as a kind of mental workout that protects the brain as it ages."),

  q("B2", "reading", "daily_life", "What paradox does the article describe?", ["That more connectivity has led to more loneliness", "That phones are getting smaller", "That people sleep more now", "That social media is declining"],
    "That more connectivity has led to more loneliness",
    "The Loneliness Paradox\nIn an age of non-stop digital connectivity, loneliness has become an epidemic. A major study by the American Psychological Association found that despite having an average of 338 online connections, 46% of adults say they regularly feel lonely. Psychologists blame the shallow nature of digital interactions, which often replace, rather than add to, real face-to-face relationships. The problem is worst among 18-25 year olds, who paradoxically use social media the most."),
  q("B2", "reading", "travel", "What does the article discuss?", ["How overtourism is ruining the places people most want to visit", "How to find cheap flights", "The best beaches in Europe", "New airline routes"],
    "How overtourism is ruining the places people most want to visit",
    "The Overtourism Crisis\nFrom Venice to Barcelona, from Machu Picchu to the Great Wall, the world's most famous destinations are being overwhelmed by visitor numbers. Venice, with just 50,000 residents, gets 30 million tourists a year, causing environmental damage, skyrocketing costs, and the erosion of local culture. Some cities have brought in tourist taxes and visitor limits, but critics say these measures aren't enough without a total rethink of how tourism works."),
  q("B2", "reading", "food", "What trend does the article highlight?", ["The rise of lab-grown meat as a sustainable alternative", "That vegetarianism is declining", "That fast food is healthier now", "That organic food is pointless"],
    "The rise of lab-grown meat as a sustainable alternative",
    "The Future of Food: Lab-Grown Meat\nCultivated meat, made by growing animal cells in bioreactors, has gone from science fiction to reality. Singapore and the US have approved several lab-grown meat products, and production costs have dropped 99% in the past decade. Supporters say it could cut farming emissions by 92% and land use by 95%. But getting people to try it is still a challenge: only 35% of Europeans say they would."),
  q("B2", "reading", "health", "What does the research reveal?", ["That gut bacteria have a big impact on mental health", "That antibiotics cure depression", "That diet doesn't affect mood", "That probiotics are dangerous"],
    "That gut bacteria have a big impact on mental health",
    "The Gut-Brain Connection\nNew research shows that the trillions of bacteria in your gut play a much bigger role in mental health than anyone thought. The gut makes about 95% of the body's serotonin, a key mood regulator. Studies show that people with a more diverse gut microbiome have lower rates of anxiety and depression. This has led to 'psychobiotics', probiotics designed specifically to improve mental health."),
  q("B2", "reading", "education", "What does the report conclude?", ["That critical thinking matters more than memorizing facts in today's economy", "That memorization is the best way to learn", "That universities are no longer needed", "That online learning is worse"],
    "That critical thinking matters more than memorizing facts in today's economy",
    "Education for the 21st Century\nThe OECD's latest report says traditional curricula, focused on memorizing facts, don't match what the modern economy needs. It pushes for a big shift toward critical thinking, creativity, and problem-solving skills. Countries that have already made this change, like Finland and Singapore, consistently outperform others and produce graduates who are better prepared for a fast-changing world."),
  q("B2", "reading", "technology", "What ethical dilemma is discussed?", ["Whether AI should make life-and-death decisions in healthcare", "How to repair old computers", "Which programming language is best", "How to speed up the internet"],
    "Whether AI should make life-and-death decisions in healthcare",
    "The Ethics of AI in Medicine\nAs AI systems become better than human doctors at diagnosing diseases, a big ethical question comes up: should algorithms be allowed to make life-and-death medical decisions? A recent case where an AI correctly found a rare cancer that three specialists missed has fired up the debate. While AI's diagnostic accuracy is impressive, critics say reducing patients to data strips medicine of its humanity and raises tough questions about who's responsible when things go wrong."),
  q("B2", "reading", "entertainment", "What does the article argue?", ["That social media algorithms are creating cultural echo chambers", "That books are more popular than ever", "That TV is dying", "That music quality has improved"],
    "That social media algorithms are creating cultural echo chambers",
    "Culture in the Algorithm Age\nSocial media algorithms, designed to keep you scrolling by showing you stuff you already like, are accidentally creating cultural echo chambers. People are only seeing music, art, movies, and opinions that match what they already think, reducing exposure to different perspectives. Critics warn this is producing a generation with narrower tastes and less ability to empathize with people who see the world differently."),
  q("B2", "reading", "sports", "What issue does the article raise?", ["The growing money gap between elite and community sports", "That soccer is getting less popular", "That athletes shouldn't be paid", "That amateur sport doesn't matter"],
    "The growing money gap between elite and community sports",
    "The Two Worlds of Sport\nWhile top soccer clubs spend hundreds of millions on player transfers, community sports facilities across Europe are falling apart due to years of underinvestment. A report by the European Sports Council found that 60% of community sports centers need major repairs, and youth sport participation has dropped 25% in the past decade. Critics say the huge wealth in professional sport should be shared more fairly to support the community foundations that produce elite athletes in the first place."),
  q("B2", "reading", "environment", "What does the report warn about?", ["That rising sea levels will displace 200 million people by 2050", "That icebergs are growing", "That pollution is going down globally", "That forests are expanding"],
    "That rising sea levels will displace 200 million people by 2050",
    "Climate Report: The Rising Tide\nThe latest IPCC report paints a grim picture: without major action, rising sea levels will force about 200 million people from their homes by 2050. Low-lying countries like Bangladesh, the Maldives, and Tuvalu face existential threats. Even wealthy nations are spending billions on flood defenses for coastal cities from Miami to Amsterdam. The report stresses that while adapting is necessary, it can't replace cutting emissions."),
  q("B2", "reading", "culture", "What phenomenon does the article explore?", ["The tension between globalization and saving minority languages", "The popularity of English worldwide", "Why everyone should learn Chinese", "How to write a dictionary"],
    "The tension between globalization and saving minority languages",
    "Losing Words: The Death of Languages\nLinguists estimate that one language dies every two weeks. Of the roughly 7,000 languages spoken today, nearly half are endangered. Globalization, urbanization, and the dominance of a few major languages like English, Mandarin, and Spanish are driving this decline. Each lost language represents not just a way of communicating, but a unique way of seeing the world. Efforts to save endangered languages are growing, but face major challenges."),

  q("C1", "reading", "daily_life", "What societal shift does the article analyse?", ["The erosion of privacy in the digital age and its impact on democracy", "How to protect your password", "The popularity of smart homes", "Tips for online shopping"],
    "The erosion of privacy in the digital age and its impact on democracy",
    "The End of Privacy?\nPrivacy as previous generations understood it is becoming obsolete. Surveillance capitalism, the monetisation of personal data by tech corporations, has created an economy where every click, purchase, and movement generates valuable information. The implications go beyond commerce: when people know they're being watched, they self-censor, and democratic discourse suffers. As philosopher Shoshana Zuboff argues, the real product in the digital economy is not data, but the modification of human behaviour itself."),
  q("C1", "reading", "travel", "What paradox does the author identify?", ["That authenticity in travel is destroyed the moment it is sought", "That planes are getting faster", "That hotels are more comfortable now", "That travel is getting cheaper"],
    "That authenticity in travel is destroyed the moment it is sought",
    "The Authenticity Trap\nThe modern traveller's quest for 'authentic' experiences reveals a fundamental paradox: the moment authenticity is consciously sought, it is inevitably turned into a product. Local communities, recognising the economic value of their 'authentic' culture, begin performing it for tourists, creating a version that satisfies visitors while gradually replacing the genuine thing. This raises deep questions about the ethics of cultural tourism and whether you can truly experience another culture without changing it."),
  q("C1", "reading", "education", "What paradigm shift does the article discuss?", ["The move from memorizing facts to navigating knowledge", "Longer school days", "More exams", "Stricter dress codes"],
    "The move from memorizing facts to navigating knowledge",
    "Beyond Knowledge: Education Reimagined\nThe old educational model, built on memorizing and retaining information, is out of step with a world where information is everywhere and professional knowledge goes out of date fast. The new approach prioritizes metacognitive skills: evaluating sources, connecting different types of information, and dealing with uncertainty. Universities that have made this shift report graduates who are more adaptable, more innovative, and paradoxically, more knowledgeable, because they have learned how to learn rather than what to learn."),
  q("C1", "reading", "health", "What does the research reveal about longevity?", ["That social connection matters as much as diet and exercise for lifespan", "That medication is the key to a long life", "That genetics alone determine how long you live", "That exercise is harmful when you're old"],
    "That social connection matters as much as diet and exercise for lifespan",
    "The Longevity Equation\nA landmark 30-year study across five continents has identified the factors most linked to living longer. While diet and exercise remain important, the strongest predictor of a long life is the quality of your social relationships. People with strong social bonds live an average of 7.5 years longer than those who are socially isolated, a bigger effect than quitting smoking. The takeaway for public health: tackling loneliness may be as important as fighting obesity."),
  q("C1", "reading", "technology", "What philosophical question does the article raise?", ["Whether artificial consciousness would deserve moral rights", "How to code faster programs", "Which smartphone brand is best", "How the internet was invented"],
    "Whether artificial consciousness would deserve moral rights",
    "The Consciousness Question\nAs AI approaches and potentially surpasses human cognitive abilities, a question once confined to philosophy departments needs a practical answer: if a machine achieves genuine consciousness, subjective experience, self-awareness, the ability to suffer, would it have moral rights? Several AI systems have already shown behaviours that, in living creatures, would look like basic emotional responses. The lack of scientific agreement on what consciousness even is makes these questions incredibly hard to resolve."),
  q("C1", "reading", "environment", "What fundamental tension does the article examine?", ["Whether economic growth and environmental sustainability can coexist", "How to recycle paper", "Tips for saving electricity", "The cost of solar panels"],
    "Whether economic growth and environmental sustainability can coexist",
    "Growth vs. The Planet\nThe dominant economic model assumes that endless growth is both possible and desirable. But growing evidence suggests that the planet's ecosystems simply cannot sustain infinite expansion. The hope that economic growth can be 'decoupled' from resource use through technology has largely failed to happen at the scale needed. A growing number of economists now advocate for post-growth models that prioritize wellbeing over GDP, but such ideas face fierce pushback from political and corporate interests invested in business as usual."),
  q("C1", "reading", "sports", "What does the analysis reveal?", ["That data analytics has fundamentally changed athletic performance and strategy", "That sports are becoming less popular", "That technology should be banned from sports", "That old-school training is always best"],
    "That data analytics has fundamentally changed athletic performance and strategy",
    "The Datafication of Sport\nAdvanced data analytics in professional sport has gone from a nice-to-have to a must-have. Teams that don't invest in data science are at a structural disadvantage. Beyond tactics, athlete monitoring systems now track sleep, stress hormones, and cognitive load in real time, enabling unprecedented training optimization. Critics warn of a dehumanizing tendency, reducing athletes to datasets, and raise privacy concerns about how much biological surveillance modern sport demands."),
  q("C1", "reading", "culture", "What does the essay explore?", ["How the idea of 'truth' has been destabilised in the post-truth era", "How to write better essays", "The history of printing", "Popular book recommendations"],
    "How the idea of 'truth' has been destabilised in the post-truth era",
    "Truth in the Post-Truth Era\nObjective truth, once the foundation of Enlightenment thinking, has been profoundly shaken. The flood of information sources, the ability of anyone to create content, and the deliberate spread of disinformation have created an environment where telling fact from fiction requires mental resources most people don't have. Philosopher Hannah Arendt's warning that the ideal subject of authoritarianism is not the true believer, but the person who can no longer tell fact from fiction, feels more relevant than ever."),
  q("C1", "reading", "entertainment", "What cultural shift does the article analyse?", ["The blurring of lines between high art and popular culture", "Why opera is dying", "How to write a screenplay", "The best movies of the year"],
    "The blurring of lines between high art and popular culture",
    "The Collapse of Cultural Hierarchies\nThe old distinction between 'high' culture and 'pop' culture, a hierarchy that dominated Western taste for centuries, is falling apart. Video games hang in modern art museums, graphic novels win literary prizes, and hip-hop is studied in university music departments. Some celebrate this as long-overdue inclusivity. Others mourn it as the death of standards. The truth, as cultural theorist Pierre Bourdieu might say, is that the hierarchy was never really about quality. It was always about social power."),
  q("C1", "reading", "food", "What does the investigation reveal?", ["That ultra-processed foods are engineered to be addictive", "That all processed food is healthy", "That home cooking doesn't matter", "That organic food has no benefits"],
    "That ultra-processed foods are engineered to be addictive",
    "Engineered to Addict\nAn investigation into the ultra-processed food industry reveals practices designed to maximize consumption through 'bliss points', precise combos of sugar, salt, and fat that trigger maximum reward in the brain. Internal documents from major food companies show that products are tested using brain imaging to optimize their addictive potential. The parallels with Big Tobacco are striking: both prioritized profit over health while lobbying hard against regulation."),
];

const listeningQuestions: QuestionDef[] = [
  q("A0", "listening", "daily_life", "Where is John from?", ["London", "Paris", "Rome", "Berlin"], "London",
    "You will hear:\nMan: Hello! My name is John. I am from London."),
  q("A0", "listening", "travel", "When does the train leave?", ["9 o'clock", "10 o'clock", "8 o'clock", "7 o'clock"], "9 o'clock",
    "You will hear:\nAnnouncement: The train to Manchester leaves at 9 o'clock from platform 3."),
  q("A0", "listening", "food", "What is the waiter asking about?", ["A drink", "A meal", "The bill", "A table"], "A drink",
    "You will hear:\nWaiter: Good morning. Would you like tea or coffee?"),
  q("A0", "listening", "health", "How often should you take the medicine?", ["Twice a day", "Once a week", "Three times a day", "Once a day"], "Twice a day",
    "You will hear:\nDoctor: Take this medicine twice a day, in the morning and in the evening."),
  q("A0", "listening", "education", "What should the students do?", ["Open the book", "Close the book", "Write in the book", "Read aloud"], "Open the book",
    "You will hear:\nTeacher: Good morning, class. Open your books to page 10, please."),
  q("A0", "listening", "technology", "Where is the password?", ["On the wall", "On the table", "In the book", "On the phone"], "On the wall",
    "You will hear:\nReceptionist: The wifi password is on the wall, next to the door."),
  q("A0", "listening", "entertainment", "When does the film start?", ["8 PM", "7 PM", "9 PM", "6 PM"], "8 PM",
    "You will hear:\nWoman: What time is the movie?\nMan: It starts at 8 PM."),
  q("A0", "listening", "sports", "What does the coach want them to do?", ["Run", "Walk", "Sit down", "Jump"], "Run",
    "You will hear:\nCoach: OK everyone, run to the other side of the field. Go!"),
  q("A0", "listening", "environment", "What is the weather like?", ["Rainy", "Sunny", "Snowy", "Windy"], "Rainy",
    "You will hear:\nWoman: Do you want to go to the park?\nMan: No, it's raining outside. Let's stay home."),
  q("A0", "listening", "culture", "How old is the building?", ["500 years", "50 years", "5 years", "5,000 years"], "500 years",
    "You will hear:\nGuide: Welcome, everyone. This building is 500 years old. It was built in 1526."),

  q("A1", "listening", "daily_life", "What time does this person wake up?", ["7 AM", "6 AM", "8 AM", "9 AM"], "7 AM",
    "You will hear:\nWoman: What's your daily routine like?\nMan: I usually get up at 7, grab some breakfast, and take the bus to work."),
  q("A1", "listening", "travel", "What happened to the flight?", ["It is delayed", "It is cancelled", "It arrived early", "It changed its destination"], "It is delayed",
    "You will hear:\nAnnouncement: Attention please. Flight 302 to Paris is delayed by two hours. We apologize for the inconvenience."),
  q("A1", "listening", "food", "What type of food does this person like?", ["Italian food", "Chinese food", "Mexican food", "Indian food"], "Italian food",
    "You will hear:\nMan: What kind of food do you like?\nWoman: I love Italian food, especially pizza and pasta. They're my favorites."),
  q("A1", "listening", "health", "When should you take the medicine?", ["After meals", "Before meals", "Before bed", "In the morning only"], "After meals",
    "You will hear:\nPharmacist: Here's your prescription. Take one pill with water after meals, three times a day."),
  q("A1", "listening", "education", "What is their favorite subject?", ["Math", "English", "Science", "Art"], "Math",
    "You will hear:\nTeacher: What's your favorite subject?\nStudent: I'd say math. I really like solving problems."),
  q("A1", "listening", "technology", "Which button starts the machine?", ["The green one", "The red one", "The blue one", "The yellow one"], "The green one",
    "You will hear:\nInstructor: To start the machine, hit the green button. The red one is to stop it."),
  q("A1", "listening", "entertainment", "How was the concert?", ["Amazing", "Boring", "Cancelled", "Disappointing"], "Amazing",
    "You will hear:\nWoman: Did you go out last night?\nMan: Yeah, I went to a concert. The band was amazing!"),
  q("A1", "listening", "sports", "Who won?", ["The home team", "The away team", "Nobody - it was a tie", "The game was cancelled"], "The home team",
    "You will hear:\nCommentator: And that's the final whistle! The score is 3-1 to the home team. What a great game!"),
  q("A1", "listening", "environment", "Why should we plant trees?", ["To clean the air", "To get fruit", "To make furniture", "To build houses"], "To clean the air",
    "You will hear:\nTeacher: Today we're talking about the environment. We should plant more trees because they help clean the air."),
  q("A1", "listening", "culture", "Who painted it?", ["Leonardo da Vinci", "Michelangelo", "Picasso", "Van Gogh"], "Leonardo da Vinci",
    "You will hear:\nGuide: If you look to your left, you'll see a famous painting. It was done by Leonardo da Vinci back in the 16th century."),

  q("A2", "listening", "daily_life", "Why was the meeting moved?", ["The room wasn't available", "The speaker was sick", "There were too many people", "The equipment was broken"], "The room wasn't available",
    "You will hear:\nManager: Hey, sorry, but the meeting's been pushed back from 2 to 4. The room wasn't free earlier.\nColleague: No worries. I'll update my calendar."),
  q("A2", "listening", "travel", "When does the agent suggest traveling?", ["Spring", "Summer", "Fall", "Winter"], "Spring",
    "You will hear:\nCustomer: When's the best time to visit?\nAgent: I'd say spring. It's way less crowded and the weather's really nice."),
  q("A2", "listening", "food", "What's important for a good risotto?", ["Fresh stock and constant stirring", "Frozen vegetables", "High heat cooking", "Adding cream first"], "Fresh stock and constant stirring",
    "You will hear:\nInterviewer: What's your top cooking tip?\nChef: For a great risotto, use fresh stock and keep stirring. Seriously, don't stop stirring!"),
  q("A2", "listening", "health", "What advice does the nurse give?", ["Cut back on salt and exercise more", "Eat more salt", "Stay in bed", "Take antibiotics"], "Cut back on salt and exercise more",
    "You will hear:\nNurse: Your blood pressure's a bit high today.\nPatient: What should I do?\nNurse: Try cutting back on salt and getting more exercise."),
  q("A2", "listening", "education", "When is the new deadline?", ["Next Friday", "This Monday", "Tomorrow", "In two weeks"], "Next Friday",
    "You will hear:\nProfessor: Good news, everyone. The essay deadline's been pushed back to next Friday because of the holiday this week."),
  q("A2", "listening", "technology", "What advice is given?", ["Back up your files regularly", "Buy a new computer", "Delete old files", "Only use the cloud"], "Back up your files regularly",
    "You will hear:\nIT guy: Make sure you back up your files regularly. If your computer crashes and you've got no backup, you could lose everything."),
  q("A2", "listening", "entertainment", "When should you visit the exhibition?", ["On a weekday", "On Saturday", "On Sunday", "At night"], "On a weekday",
    "You will hear:\nPresenter: The new exhibit at the gallery is totally worth seeing, but I'd skip the weekends. It gets super crowded on Saturdays and Sundays."),
  q("A2", "listening", "sports", "Why did the team lose?", ["Bad defense in the second half", "The ref made mistakes", "They didn't score enough", "The weather was bad"], "Bad defense in the second half",
    "You will hear:\nReporter: What went wrong today?\nCoach: Honestly, we lost because our defense fell apart in the second half. We gotta work on that."),
  q("A2", "listening", "environment", "What does the scientist predict?", ["A 2-degree temperature rise by 2050", "Temperatures will drop", "No climate change", "An ice age by 2050"], "A 2-degree temperature rise by 2050",
    "You will hear:\nScientist: Our data shows that if we keep going at this rate, global temperatures will go up by 2 degrees by 2050. That's gonna have serious consequences."),
  q("A2", "listening", "culture", "What benefit of learning languages is mentioned?", ["Understanding other cultures", "Getting a higher salary", "Traveling more cheaply", "Making more friends online"], "Understanding other cultures",
    "You will hear:\nSpeaker: Learning another language opens doors to other cultures and different ways of thinking. It really changes how you see the world."),

  q("B1", "listening", "daily_life", "What bugs the speaker about working from home?", ["Feeling cut off from people", "Too many distractions", "Bad internet", "Can't separate work and life"], "Feeling cut off from people",
    "You will hear:\nInterviewer: So how's working from home going for you?\nEmployee: It's got its perks, like not having to commute. But honestly, I really miss the social side of things. It can feel pretty isolating not having colleagues around."),
  q("B1", "listening", "travel", "What made tourism take off in this area?", ["A travel blog feature", "A new airport", "A government campaign", "A famous movie"], "A travel blog feature",
    "You will hear:\nGuide: This area was basically unknown to tourists until 2019. Then a big travel blog did a piece on it, and after that, the number of visitors tripled practically overnight."),
  q("B1", "listening", "food", "What point is being made?", ["Processed foods have way more sugar than you'd think", "Chocolate is healthier than pasta sauce", "You should never eat pasta sauce", "All sugar is the same"], "Processed foods have way more sugar than you'd think",
    "You will hear:\nNutritionist: People really don't realize how much sugar is hiding in processed foods. Like, a single jar of pasta sauce can have as much sugar as a candy bar. Pretty crazy, right?"),
  q("B1", "listening", "health", "What does the doctor say about stress?", ["A little stress is fine, but too much is bad", "All stress is dangerous", "Stress doesn't affect your body", "Long-term stress helps you perform"], "A little stress is fine, but too much is bad",
    "You will hear:\nDoctor: Stress isn't always a bad thing. In small doses, it can actually help you focus and do better. The problem is when it becomes constant. That's when it starts messing with your health."),
  q("B1", "listening", "education", "What study technique is recommended?", ["Testing yourself", "Re-reading your notes", "Just listening to lectures", "Highlighting stuff"], "Testing yourself",
    "You will hear:\nProfessor: Research shows that the best learners are the ones who quiz themselves regularly, instead of just reading their notes over and over. Testing yourself forces your brain to actually retrieve the information."),
  q("B1", "listening", "technology", "What's the real benefit of smart home gadgets?", ["Saving energy", "Entertainment", "Security", "Convenience"], "Saving energy",
    "You will hear:\nHost: So what's the real value of smart home tech?\nExpert: It's not really about convenience. The big win is the energy you save through things like automatically turning down the heat when nobody's home."),
  q("B1", "listening", "entertainment", "What does the critic like about the novel?", ["The quality of the writing", "The plot", "How long it is", "The ending"], "The quality of the writing",
    "You will hear:\nCritic: I just finished this novel, and honestly, the plot is pretty standard. But the writing? It's stunning. That's what makes this book stand out."),
  q("B1", "listening", "sports", "What made the team win?", ["Discipline and team spirit", "Better players", "More money", "Luck"], "Discipline and team spirit",
    "You will hear:\nCommentator: What a result! They had way fewer resources than the other team, but they won through sheer discipline and team spirit. Those were the difference-makers today."),
  q("B1", "listening", "environment", "What's the researcher's point about urban beekeeping?", ["It actually helps pollinators", "It's just a fad", "Rural bees are doing fine", "Cities are bad for bees"], "It actually helps pollinators",
    "You will hear:\nResearcher: Urban beekeeping isn't just some trendy hobby. Our studies show it genuinely helps pollinator populations, especially the ones that are declining in rural areas because of pesticides."),
  q("B1", "listening", "culture", "What's the historian getting at?", ["What we forget shapes history as much as what we remember", "We should forget the past", "History books are always right", "Memory is perfect"], "What we forget shapes history as much as what we remember",
    "You will hear:\nHistorian: The fascinating thing about how we remember history is that it's shaped just as much by what we choose to forget as by what we choose to remember. Our collective memory is always selective."),

  q("B2", "listening", "daily_life", "What's the criticism of the gig economy?", ["It creates insecurity without proper benefits", "It pays too well", "It's too flexible", "It requires degrees"], "It creates insecurity without proper benefits",
    "You will hear:\nSociologist: The gig economy sells you flexibility and freedom. But in reality, a lot of workers end up stuck in a cycle of insecurity with none of the benefits you'd get from a regular job, like health insurance or paid time off.\nHost: So it doesn't live up to the hype?\nSociologist: Not for most people, no."),
  q("B2", "listening", "travel", "What's the concern about voluntourism?", ["It can reinforce stereotypes and create dependency", "It costs too much", "It requires special skills", "It takes too long"], "It can reinforce stereotypes and create dependency",
    "You will hear:\nAnthropologist: Voluntourism is tricky. Even though people mean well, it can actually reinforce harmful stereotypes about the communities it's supposed to help, and it often creates dependency rather than real, lasting change."),
  q("B2", "listening", "food", "What's the point about food miles?", ["Local food isn't always greener", "Imported food is always better", "Greenhouses should be banned", "Tomatoes are bad for the planet"], "Local food isn't always greener",
    "You will hear:\nResearcher: The whole food miles thing is way too simple. Think about it: a tomato grown locally in a heated greenhouse in winter can actually have a bigger carbon footprint than one shipped in from somewhere warm where it grew outside naturally."),
  q("B2", "listening", "health", "What worries the psychiatrist?", ["Normal feelings are being treated as disorders", "People don't take enough meds", "Psychiatry is useless", "All emotions are pathological"], "Normal feelings are being treated as disorders",
    "You will hear:\nPsychiatrist: What really concerns me is how we're medicalizing perfectly normal human emotions. We're at risk of turning the whole range of human experience into something that needs a pill. Sadness, anxiety, grief... these are normal parts of life."),
  q("B2", "listening", "education", "What's wrong with standardized testing?", ["It misses skills like creativity and teamwork", "It's too easy", "It costs too much", "It takes too long"], "It misses skills like creativity and teamwork",
    "You will hear:\nPolicy maker: Standardized tests are great at measuring stuff you can put a number on: facts, formulas, procedures. But they completely miss the skills that actually matter most out in the real world, like creativity, critical thinking, and being able to work with other people."),
  q("B2", "listening", "technology", "What trade-off is being discussed?", ["Convenience vs. its effect on freedom", "Speed vs. accuracy", "Cost vs. quality", "Privacy vs. entertainment"], "Convenience vs. its effect on freedom",
    "You will hear:\nEthicist: Sure, facial recognition is super convenient. But you have to weigh that against the chilling effect it has on how people behave in public. When you know you're being watched, you act differently. And that has real consequences for freedom of assembly."),
  q("B2", "listening", "entertainment", "What happens when algorithms pick what gets made?", ["More mainstream stuff, less creative risk-taking", "Higher quality shows", "More diverse content", "Fewer shows overall"], "More mainstream stuff, less creative risk-taking",
    "You will hear:\nProducer: Here's the problem with letting algorithms decide what gets greenlit: you end up with more and more shows designed to appeal to the widest possible audience. Sounds great, right? But it means way fewer projects that actually take creative risks. Innovation gets squeezed out."),
  q("B2", "listening", "sports", "What problem is described?", ["Rich clubs getting around salary cap rules", "Players not earning enough", "Too many teams", "Fans losing interest"], "Rich clubs getting around salary cap rules",
    "You will hear:\nAnalyst: The salary cap was supposed to level the playing field across the league. But the wealthiest clubs have found all kinds of loopholes in the rules that basically defeat the whole purpose. It's still not a fair competition."),
  q("B2", "listening", "environment", "What's the big challenge?", ["Carbon pricing is good economics but political suicide", "Carbon taxes are cheap", "Everyone loves carbon pricing", "Environmental policy is simple"], "Carbon pricing is good economics but political suicide",
    "You will hear:\nEconomist: Putting a price on carbon makes total sense economically. Pretty much every economist agrees. But it's political dynamite. No politician wants to tell voters that their lifestyle actually costs way more than what they're paying for it."),
  q("B2", "listening", "culture", "What tension is identified?", ["Global communication vs. language diversity", "Grammar vs. vocabulary", "Writing vs. speaking", "Formal vs. informal English"], "Global communication vs. language diversity",
    "You will hear:\nLinguist: English as a global language makes international communication easier, and that's great. But it also comes at a cost: it's squeezing out the linguistic diversity that makes human thought so rich. Every time a language disappears, we lose a unique lens on the world."),

  q("C1", "listening", "daily_life", "What claim is made about how we make decisions?", ["Most decisions are driven by biases we don't even know about", "All decisions are perfectly rational", "We shouldn't make decisions", "Being rational always helps"], "Most decisions are driven by biases we don't even know about",
    "You will hear:\nPhilosopher: The idea that we make rational choices is basically an illusion. Decades of research show that most of our decisions are driven by cognitive biases we're completely unaware of. The stories we tell ourselves afterwards about why we did something? Those are just comforting narratives.\nHost: So free will is an illusion?\nPhilosopher: Our sense of rational deliberation certainly is, at least."),
  q("C1", "listening", "travel", "What argument is made about wilderness?", ["The idea of untouched wilderness is a cultural invention", "Nature hasn't been affected by humans", "All landscapes are artificial", "Wilderness needs more protection"], "The idea of untouched wilderness is a cultural invention",
    "You will hear:\nGeographer: This idea of wilderness as nature untouched by humans is itself a cultural construction, mostly a product of 19th-century Romanticism. Every landscape on Earth has been shaped by human activity in some way. The line between natural and artificial is basically meaningless at this point."),
  q("C1", "listening", "food", "What does the historian argue about national cuisines?", ["They're invented traditions, not authentic ones", "All food is the same everywhere", "Food was better 200 years ago", "Immigration ruined food culture"], "They're invented traditions, not authentic ones",
    "You will hear:\nFood historian: The whole idea of national cuisines is mostly a 19th-century invention, tied up with nationalism. What we think of as 'traditional' dishes are usually the result of global trade routes, colonialism, and immigrant communities bringing their food with them. Authenticity? It's a myth."),
  q("C1", "listening", "health", "What ethical issue is raised?", ["Where treatment ends and human enhancement begins", "How much genetic testing costs", "Whether exercise is good for you", "How to prescribe medication"], "Where treatment ends and human enhancement begins",
    "You will hear:\nBioethicist: Technologies like CRISPR that let us edit the human genome raise some really deep questions. Where does treating a disease end and enhancing a human being begin? And who gets to decide where that line is?\nInterviewer: Is there a clear answer?\nBioethicist: That's exactly the problem. There isn't one."),
  q("C1", "listening", "education", "What concept is being discussed?", ["The hidden curriculum and how it shapes students", "Why homework matters", "Abolishing exams", "Better school buildings"], "The hidden curriculum and how it shapes students",
    "You will hear:\nEducation theorist: What I call the hidden curriculum, the values, norms, and behaviors that schools teach without saying so, may actually have more influence on students than the actual subjects they study. We need to look at what we're teaching without realizing it."),
  q("C1", "listening", "technology", "What's the researcher's argument about the digital divide?", ["It's about way more than just access to devices", "Everyone has equal access to tech", "Digital literacy doesn't matter", "The internet should be free"], "It's about way more than just access to devices",
    "You will hear:\nResearcher: People usually think the digital divide is just about access. Do you have a phone? Can you get online? But it's so much bigger than that. It includes digital literacy, the ability to tell good information from garbage, and whether you can actually use technology to improve your life."),
  q("C1", "listening", "entertainment", "What phenomenon is being analyzed?", ["People forming one-sided relationships with media figures instead of real ones", "Why reality TV is popular", "How actors prepare for roles", "Why people watch the news"], "People forming one-sided relationships with media figures instead of real ones",
    "You will hear:\nMedia theorist: The parasocial relationships people develop with fictional characters and celebrities fill real psychological needs for connection. But they can also become a substitute for the harder, messier work of building actual human relationships."),
  q("C1", "listening", "sports", "What's the argument about doping?", ["It destroys sport by removing the very constraints that give it meaning", "It should be made legal", "Everyone does it anyway", "Athletes should choose for themselves"], "It destroys sport by removing the very constraints that give it meaning",
    "You will hear:\nPhilosopher: Sport is fundamentally about choosing to face unnecessary obstacles. You could drive to the finish line, but you choose to run. Take away the constraints and you take away the point. That's exactly why performance-enhancing drugs undermine the whole thing."),
  q("C1", "listening", "environment", "What tension exists around climate tipping points?", ["The science is real but the language of doom can make people give up", "Scientists are too optimistic", "Governments and scientists don't talk", "Economics and policy always clash"], "The science is real but the language of doom can make people give up",
    "You will hear:\nClimate scientist: Tipping points are scientifically real and crucial to understand. But here's the problem: when you use words like 'irreversible' and 'point of no return', people can actually become fatalistic rather than motivated. If they think it's already too late, they stop trying."),
  q("C1", "listening", "culture", "What's the argument about nostalgia?", ["It's really about being unhappy with the present, not missing the past", "The past was genuinely better", "Nostalgia is a mental disorder", "We should all forget the past"], "It's really about being unhappy with the present, not missing the past",
    "You will hear:\nCultural theorist: Nostalgia is never really about the past. It's a commentary on right now. It's a way of expressing dissatisfaction with how things are, projected onto some idealized version of how things used to be. The golden age people long for? It never actually existed."),
];

export function getBusinessEnglishQuestions(): InsertBeQuestion[] {
  const all = [...grammarQuestions, ...vocabularyQuestions, ...useOfEnglishQuestions, ...readingQuestions, ...listeningQuestions];
  return all.map(q => ({
    level: q.level,
    skillType: q.skillType,
    section: q.skillType,
    topic: q.topic,
    question: q.question,
    options: JSON.stringify(q.options),
    correctAnswer: q.correctAnswer,
    passage: q.passage || null,
    audioUrl: null,
    explanation: null,
    difficulty: q.difficulty,
    discrimination: q.discrimination,
    calibrationStatus: "calibrated",
    calibrationNotes: null,
  }));
}

export function getAllQuestions(): InsertBeQuestion[] {
  return getBusinessEnglishQuestions();
}
