import type { InsertBeQuestion } from "@shared/schema";

interface QuestionDef {
  level: string;
  skillType: string;
  topic: string;
  question: string;
  options: string[];
  correctAnswer: string;
  passage?: string;
  difficulty: number;
  discrimination: number;
}

function q(level: string, skillType: string, topic: string, question: string, options: string[], correctAnswer: string, passage?: string): QuestionDef {
  const difficultyMap: Record<string, number> = { A0: -250, A1: -150, A2: -50, B1: 50, B2: 150, C1: 250 };
  return {
    level, skillType, topic, question, options, correctAnswer, passage,
    difficulty: difficultyMap[level] ?? 0,
    discrimination: 100,
  };
}

const grammarQuestions: QuestionDef[] = [
  q("A0", "grammar", "business_email", "I ___ a worker.", ["am", "is", "are", "be"], "am"),
  q("A0", "grammar", "meetings", "She ___ in the office.", ["is", "am", "are", "be"], "is"),
  q("A0", "grammar", "customer_service", "They ___ happy.", ["are", "is", "am", "be"], "are"),
  q("A0", "grammar", "hr", "He ___ a manager.", ["is", "am", "are", "be"], "is"),
  q("A0", "grammar", "logistics", "We ___ at work.", ["are", "is", "am", "be"], "are"),
  q("A0", "grammar", "finance", "It ___ a good company.", ["is", "am", "are", "be"], "is"),
  q("A0", "grammar", "marketing", "I ___ not busy.", ["am", "is", "are", "be"], "am"),
  q("A0", "grammar", "reports", "The office ___ big.", ["is", "am", "are", "be"], "is"),
  q("A0", "grammar", "presentations", "You ___ my colleague.", ["are", "is", "am", "be"], "are"),
  q("A0", "grammar", "negotiations", "This ___ my desk.", ["is", "am", "are", "be"], "is"),

  q("A1", "grammar", "business_email", "She ___ to work every day.", ["goes", "go", "going", "gone"], "goes"),
  q("A1", "grammar", "meetings", "We ___ a meeting at 10 AM.", ["have", "has", "having", "had"], "have"),
  q("A1", "grammar", "customer_service", "The customer ___ help.", ["needs", "need", "needing", "needed"], "needs"),
  q("A1", "grammar", "hr", "I ___ in the HR department.", ["work", "works", "working", "worked"], "work"),
  q("A1", "grammar", "logistics", "The delivery ___ at 3 PM.", ["arrives", "arrive", "arriving", "arrived"], "arrives"),
  q("A1", "grammar", "finance", "He ___ the invoices every month.", ["checks", "check", "checking", "checked"], "checks"),
  q("A1", "grammar", "marketing", "They ___ a new campaign.", ["plan", "plans", "planning", "planned"], "plan"),
  q("A1", "grammar", "reports", "She ___ a report every week.", ["writes", "write", "writing", "written"], "writes"),
  q("A1", "grammar", "presentations", "The presentation ___ at 2 PM.", ["starts", "start", "starting", "started"], "starts"),
  q("A1", "grammar", "negotiations", "We ___ to agree on the price.", ["need", "needs", "needing", "needed"], "need"),

  q("A2", "grammar", "business_email", "I ___ an email to the client yesterday.", ["sent", "send", "sended", "sending"], "sent"),
  q("A2", "grammar", "meetings", "We ___ about the new project last week.", ["talked", "talk", "talking", "talks"], "talked"),
  q("A2", "grammar", "customer_service", "The problem ___ resolved by the team.", ["was", "is", "were", "been"], "was"),
  q("A2", "grammar", "hr", "She ___ working here for two years.", ["has been", "is been", "was been", "have been"], "has been"),
  q("A2", "grammar", "logistics", "The goods ___ delivered next Monday.", ["will be", "is", "are been", "was"], "will be"),
  q("A2", "grammar", "finance", "If you ___ the form, I will process it.", ["complete", "completed", "completing", "will complete"], "complete"),
  q("A2", "grammar", "marketing", "The brochure ___ printed last Friday.", ["was", "is", "were", "been"], "was"),
  q("A2", "grammar", "reports", "I ___ the report before the deadline.", ["finished", "finish", "finishing", "finishes"], "finished"),
  q("A2", "grammar", "presentations", "He ___ preparing the slides since morning.", ["has been", "is been", "was been", "had been"], "has been"),
  q("A2", "grammar", "negotiations", "They ___ the contract last month.", ["signed", "sign", "signing", "signs"], "signed"),

  q("B1", "grammar", "business_email", "If we ___ earlier, we could have met the deadline.", ["had started", "started", "would start", "have started"], "had started"),
  q("B1", "grammar", "meetings", "The project ___ by the time the CEO arrived.", ["had been completed", "was completing", "has completed", "completes"], "had been completed"),
  q("B1", "grammar", "customer_service", "She told me that she ___ the issue the previous day.", ["had reported", "reported", "reports", "has reported"], "had reported"),
  q("B1", "grammar", "hr", "All employees ___ to attend the training session.", ["are required", "is required", "requiring", "have requiring"], "are required"),
  q("B1", "grammar", "logistics", "The shipment, ___ was delayed, arrived this morning.", ["which", "who", "what", "where"], "which"),
  q("B1", "grammar", "finance", "The budget ___ unless additional funding is approved.", ["will not be increased", "not increases", "isn't increasing", "doesn't increase"], "will not be increased"),
  q("B1", "grammar", "marketing", "Having ___ the market research, we launched the campaign.", ["completed", "complete", "completing", "been completed"], "completed"),
  q("B1", "grammar", "reports", "The report should ___ by Friday.", ["be submitted", "submit", "submitted", "be submitting"], "be submitted"),
  q("B1", "grammar", "presentations", "Neither the manager ___ the director was available.", ["nor", "or", "and", "but"], "nor"),
  q("B1", "grammar", "negotiations", "We insisted that the supplier ___ the quality standards.", ["meet", "meets", "met", "meeting"], "meet"),

  q("B2", "grammar", "business_email", "Had the client ___ us sooner, we could have avoided the issue.", ["notified", "notify", "notifying", "been notified"], "notified"),
  q("B2", "grammar", "meetings", "The CEO, ___ tenure has been marked by innovation, announced restructuring.", ["whose", "who's", "which", "whom"], "whose"),
  q("B2", "grammar", "customer_service", "Not until we received the complaint ___ we realize the error.", ["did", "do", "have", "had"], "did"),
  q("B2", "grammar", "hr", "The policy requires that each employee ___ a performance review.", ["undergo", "undergoes", "undergoing", "underwent"], "undergo"),
  q("B2", "grammar", "logistics", "Were the shipment ___ on time, we wouldn't have lost the contract.", ["to arrive", "arriving", "arrived", "arrives"], "to arrive"),
  q("B2", "grammar", "finance", "So rapid ___ the market decline that investors panicked.", ["was", "is", "were", "has been"], "was"),
  q("B2", "grammar", "marketing", "The campaign proved ___ successful than initially projected.", ["far more", "much", "very more", "so much"], "far more"),
  q("B2", "grammar", "reports", "Only after thorough analysis ___ the board approve the merger.", ["did", "does", "has", "will"], "did"),
  q("B2", "grammar", "presentations", "The proposal, ___ merits notwithstanding, was rejected.", ["its", "it's", "whose", "which"], "its"),
  q("B2", "grammar", "negotiations", "Little ___ the negotiators know about the competitor's financial position.", ["did", "do", "have", "were"], "did"),

  q("C1", "grammar", "business_email", "Scarcely ___ the announcement been made when shareholders demanded an explanation.", ["had", "has", "was", "did"], "had"),
  q("C1", "grammar", "meetings", "The proposal, ___ ambitious in scope, failed to address key regulatory concerns.", ["albeit", "although it", "despite", "however"], "albeit"),
  q("C1", "grammar", "customer_service", "So convinced ___ the board of the strategy's efficacy that they increased the budget.", ["was", "were", "is", "has been"], "was"),
  q("C1", "grammar", "hr", "It is imperative that the organization ___ its diversity initiatives.", ["strengthen", "strengthens", "strengthened", "strengthening"], "strengthen"),
  q("C1", "grammar", "logistics", "Not only ___ the supply chain been disrupted, but costs had also escalated.", ["had", "has", "was", "did"], "had"),
  q("C1", "grammar", "finance", "The merger, ___ it to proceed, would fundamentally alter the competitive landscape.", ["were", "was", "should", "if"], "were"),
  q("C1", "grammar", "marketing", "Under no circumstances ___ confidential client data be shared externally.", ["should", "shall", "would", "could"], "should"),
  q("C1", "grammar", "reports", "The report, the implications of ___ are far-reaching, requires immediate attention.", ["which", "that", "what", "whom"], "which"),
  q("C1", "grammar", "presentations", "Notwithstanding the objections ___ by several stakeholders, the motion carried.", ["raised", "raising", "to raise", "having raised"], "raised"),
  q("C1", "grammar", "negotiations", "Had the parties been ___ to compromise, arbitration would have been unnecessary.", ["willing", "willing be", "willingly", "willed"], "willing"),
];

const vocabularyQuestions: QuestionDef[] = [
  q("A0", "vocabulary", "business_email", "An 'email' is a ___.", ["message on a computer", "type of food", "kind of car", "big building"], "message on a computer"),
  q("A0", "vocabulary", "meetings", "A 'meeting' is when people ___.", ["talk together", "eat lunch", "go home", "sleep"], "talk together"),
  q("A0", "vocabulary", "customer_service", "A 'customer' is a person who ___.", ["buys things", "makes food", "drives a car", "builds houses"], "buys things"),
  q("A0", "vocabulary", "hr", "A 'job' is ___.", ["work you do", "a place to eat", "a type of sport", "a kind of music"], "work you do"),
  q("A0", "vocabulary", "logistics", "An 'office' is a place where people ___.", ["work", "cook", "swim", "play"], "work"),
  q("A0", "vocabulary", "finance", "'Money' is used to ___.", ["buy things", "write letters", "drive cars", "grow plants"], "buy things"),
  q("A0", "vocabulary", "marketing", "A 'product' is something you can ___.", ["buy and use", "eat only", "wear only", "drink only"], "buy and use"),
  q("A0", "vocabulary", "reports", "A 'boss' is the person who ___.", ["manages the work", "cleans the office", "cooks lunch", "fixes computers"], "manages the work"),
  q("A0", "vocabulary", "presentations", "A 'colleague' is someone you ___.", ["work with", "live with", "play with", "eat with"], "work with"),
  q("A0", "vocabulary", "negotiations", "To 'agree' means to say ___.", ["yes", "no", "maybe", "goodbye"], "yes"),

  q("A1", "vocabulary", "business_email", "Please find the document ___ to this email.", ["attached", "attacking", "attracted", "attempted"], "attached"),
  q("A1", "vocabulary", "meetings", "We need to ___ a time for the meeting.", ["schedule", "scatter", "scratch", "screen"], "schedule"),
  q("A1", "vocabulary", "customer_service", "I would like to make a ___ about the service.", ["complaint", "compliment", "companion", "competition"], "complaint"),
  q("A1", "vocabulary", "hr", "She was ___ for the position of team leader.", ["promoted", "promised", "proposed", "protected"], "promoted"),
  q("A1", "vocabulary", "logistics", "The ___ will arrive by courier tomorrow.", ["package", "passage", "passenger", "pastime"], "package"),
  q("A1", "vocabulary", "finance", "Please ___ this invoice by the end of the month.", ["pay", "play", "pray", "prey"], "pay"),
  q("A1", "vocabulary", "marketing", "Our company needs to ___ its products better.", ["advertise", "adventure", "advance", "advise"], "advertise"),
  q("A1", "vocabulary", "reports", "The annual ___ shows an increase in sales.", ["report", "resort", "record", "reward"], "report"),
  q("A1", "vocabulary", "presentations", "Could you ___ the main points of your talk?", ["summarize", "supervise", "surprise", "surrender"], "summarize"),
  q("A1", "vocabulary", "negotiations", "Let's try to reach an ___ on this matter.", ["agreement", "argument", "arrangement", "assignment"], "agreement"),

  q("A2", "vocabulary", "business_email", "I am writing to ___ receipt of your order.", ["acknowledge", "accomplish", "accumulate", "accelerate"], "acknowledge"),
  q("A2", "vocabulary", "meetings", "We need to ___ the agenda before the meeting.", ["circulate", "calculate", "celebrate", "cultivate"], "circulate"),
  q("A2", "vocabulary", "customer_service", "We offer a full ___ if you are not satisfied.", ["refund", "reform", "refuge", "refusal"], "refund"),
  q("A2", "vocabulary", "hr", "The company provides ___ benefits to all employees.", ["comprehensive", "competitive", "compulsory", "controversial"], "comprehensive"),
  q("A2", "vocabulary", "logistics", "We need to ___ the warehouse inventory.", ["update", "upgrade", "upload", "uphold"], "update"),
  q("A2", "vocabulary", "finance", "The quarterly ___ exceeded expectations.", ["revenue", "review", "revival", "revision"], "revenue"),
  q("A2", "vocabulary", "marketing", "We launched a new ___ to attract younger customers.", ["campaign", "champion", "channel", "chapter"], "campaign"),
  q("A2", "vocabulary", "reports", "The data ___ a significant trend in consumer behavior.", ["indicates", "initiates", "imitates", "illustrates"], "indicates"),
  q("A2", "vocabulary", "presentations", "The speaker used ___ to support his main argument.", ["evidence", "evolution", "evaluation", "elevation"], "evidence"),
  q("A2", "vocabulary", "negotiations", "Both parties agreed to a ___.", ["compromise", "component", "complement", "commitment"], "compromise"),

  q("B1", "vocabulary", "business_email", "We would like to ___ a proposal for your consideration.", ["submit", "subject", "subtract", "substitute"], "submit"),
  q("B1", "vocabulary", "meetings", "The board will ___ the new strategy at next week's meeting.", ["deliberate", "delegate", "demonstrate", "deteriorate"], "deliberate"),
  q("B1", "vocabulary", "customer_service", "Our team is committed to ___ customer satisfaction.", ["ensuring", "enduring", "endorsing", "enriching"], "ensuring"),
  q("B1", "vocabulary", "hr", "The company implemented a ___ policy for remote working.", ["flexible", "fragile", "fertile", "futile"], "flexible"),
  q("B1", "vocabulary", "logistics", "We need to ___ the supply chain to reduce costs.", ["streamline", "strengthen", "stimulate", "standardize"], "streamline"),
  q("B1", "vocabulary", "finance", "The company's ___ has increased by 15% this quarter.", ["turnover", "takeover", "transfer", "trademark"], "turnover"),
  q("B1", "vocabulary", "marketing", "The new product ___ exceeded all expectations.", ["launch", "league", "layout", "leverage"], "launch"),
  q("B1", "vocabulary", "reports", "The findings ___ with the previous quarter's analysis.", ["align", "alter", "allege", "allocate"], "align"),
  q("B1", "vocabulary", "presentations", "The CEO's ___ speech motivated the entire workforce.", ["keynote", "keyword", "kinetic", "knockout"], "keynote"),
  q("B1", "vocabulary", "negotiations", "The parties reached a ___ beneficial agreement.", ["mutually", "manually", "marginally", "minimally"], "mutually"),

  q("B2", "vocabulary", "business_email", "I am writing to ___ our dissatisfaction with the service.", ["convey", "convert", "converge", "conserve"], "convey"),
  q("B2", "vocabulary", "meetings", "The committee decided to ___ the decision until further data was available.", ["defer", "deter", "deflect", "defuse"], "defer"),
  q("B2", "vocabulary", "customer_service", "We aim to ___ any inconvenience caused.", ["mitigate", "motivate", "moderate", "manipulate"], "mitigate"),
  q("B2", "vocabulary", "hr", "The restructuring will ___ the elimination of several positions.", ["entail", "enable", "enrich", "enforce"], "entail"),
  q("B2", "vocabulary", "logistics", "Due to ___ demand, we have increased production capacity.", ["unprecedented", "unrelated", "undecided", "underrated"], "unprecedented"),
  q("B2", "vocabulary", "finance", "The company plans to ___ its portfolio through strategic acquisitions.", ["diversify", "diminish", "distribute", "dismantle"], "diversify"),
  q("B2", "vocabulary", "marketing", "The campaign sought to ___ the brand among millennial consumers.", ["bolster", "boycott", "bypass", "benchmark"], "bolster"),
  q("B2", "vocabulary", "reports", "The data ___ a correlation between employee engagement and profitability.", ["corroborates", "contradicts", "constitutes", "consolidates"], "corroborates"),
  q("B2", "vocabulary", "presentations", "Her ___ delivery captivated the audience throughout the presentation.", ["compelling", "competing", "complying", "comparing"], "compelling"),
  q("B2", "vocabulary", "negotiations", "The contract includes a ___ clause for early termination.", ["penalty", "potential", "principal", "protocol"], "penalty"),

  q("C1", "vocabulary", "business_email", "I would like to ___ upon the points raised in our previous correspondence.", ["elaborate", "evacuate", "exonerate", "extrapolate"], "elaborate"),
  q("C1", "vocabulary", "meetings", "The board's ___ stance on regulatory compliance has drawn criticism.", ["intransigent", "intermittent", "inconsequential", "indiscriminate"], "intransigent"),
  q("C1", "vocabulary", "customer_service", "The company must ___ its service model to remain competitive.", ["overhaul", "overlook", "overcome", "overstate"], "overhaul"),
  q("C1", "vocabulary", "hr", "The organization seeks to ___ a culture of continuous improvement.", ["foster", "feign", "forge", "fortify"], "foster"),
  q("C1", "vocabulary", "logistics", "The ___ of the global supply chain necessitates robust risk management.", ["intricacy", "integrity", "intensity", "interplay"], "intricacy"),
  q("C1", "vocabulary", "finance", "Market ___ has rendered traditional forecasting models obsolete.", ["volatility", "validity", "visibility", "viability"], "volatility"),
  q("C1", "vocabulary", "marketing", "The brand's ___ in the luxury segment is unassailable.", ["pre-eminence", "predominance", "prevalence", "precedence"], "pre-eminence"),
  q("C1", "vocabulary", "reports", "The audit revealed ___ between reported figures and actual performance.", ["discrepancies", "dispositions", "digressions", "derivatives"], "discrepancies"),
  q("C1", "vocabulary", "presentations", "The presenter's ___ analysis of market trends was both thorough and insightful.", ["perspicacious", "perfunctory", "peripheral", "presumptuous"], "perspicacious"),
  q("C1", "vocabulary", "negotiations", "The counterparty's ___ demands threatened to derail negotiations.", ["exorbitant", "extraneous", "exhaustive", "exemplary"], "exorbitant"),
];

const useOfEnglishQuestions: QuestionDef[] = [
  q("A0", "use_of_english", "business_email", "'Good morning' is a way to say ___.", ["hello", "goodbye", "thank you", "sorry"], "hello"),
  q("A0", "use_of_english", "meetings", "When someone says 'Thank you', you say ___.", ["You're welcome", "I'm sorry", "Goodbye", "Good night"], "You're welcome"),
  q("A0", "use_of_english", "customer_service", "'How much?' asks about the ___.", ["price", "time", "color", "name"], "price"),
  q("A0", "use_of_english", "hr", "'What is your name?' asks for your ___.", ["name", "job", "age", "country"], "name"),
  q("A0", "use_of_english", "logistics", "'Where is it?' asks about a ___.", ["place", "time", "person", "reason"], "place"),
  q("A0", "use_of_english", "finance", "To say the time '3:00', we say ___.", ["three o'clock", "three hours", "o'clock three", "clock three"], "three o'clock"),
  q("A0", "use_of_english", "marketing", "'I like it' means you think it is ___.", ["good", "bad", "ugly", "wrong"], "good"),
  q("A0", "use_of_english", "reports", "In English, Monday is a ___.", ["day", "month", "year", "number"], "day"),
  q("A0", "use_of_english", "presentations", "'Please' is used when you ___ something.", ["ask for", "give away", "throw away", "take away"], "ask for"),
  q("A0", "use_of_english", "negotiations", "'Yes or no?' is a ___.", ["question", "answer", "name", "number"], "question"),

  q("A1", "use_of_english", "business_email", "Which is the correct way to end a formal email?", ["Kind regards", "See you later", "Bye bye", "Talk soon"], "Kind regards"),
  q("A1", "use_of_english", "meetings", "'Let's get started' means we should ___ the meeting.", ["begin", "end", "cancel", "postpone"], "begin"),
  q("A1", "use_of_english", "customer_service", "'How can I help you?' is used to ___ assistance.", ["offer", "refuse", "delay", "avoid"], "offer"),
  q("A1", "use_of_english", "hr", "A 'full-time' job means you work ___ a week.", ["about 40 hours", "about 10 hours", "only weekends", "one day"], "about 40 hours"),
  q("A1", "use_of_english", "logistics", "'Out of stock' means the item is ___.", ["not available", "very cheap", "brand new", "on sale"], "not available"),
  q("A1", "use_of_english", "finance", "An 'invoice' is a document that asks for ___.", ["payment", "permission", "promotion", "protection"], "payment"),
  q("A1", "use_of_english", "marketing", "A 'discount' means the price is ___.", ["lower", "higher", "the same", "unknown"], "lower"),
  q("A1", "use_of_english", "reports", "A 'deadline' is the ___ day to finish something.", ["last", "first", "best", "worst"], "last"),
  q("A1", "use_of_english", "presentations", "'To sum up' means to ___ the main points.", ["review", "remove", "replace", "refuse"], "review"),
  q("A1", "use_of_english", "negotiations", "'Deal' in business means an ___.", ["agreement", "argument", "advertisement", "application"], "agreement"),

  q("A2", "use_of_english", "business_email", "Which phrase is appropriate to begin a formal request?", ["I would be grateful if you could...", "You must do this now...", "Do it right away...", "I want you to..."], "I would be grateful if you could..."),
  q("A2", "use_of_english", "meetings", "'To follow up on' means to ___ a previous topic.", ["continue discussing", "forget about", "argue about", "complain about"], "continue discussing"),
  q("A2", "use_of_english", "customer_service", "'I apologize for the inconvenience' is used when ___.", ["something went wrong", "everything is perfect", "you want a raise", "you are leaving"], "something went wrong"),
  q("A2", "use_of_english", "hr", "'Probation period' refers to a ___ time for new employees.", ["trial", "vacation", "retirement", "training"], "trial"),
  q("A2", "use_of_english", "logistics", "'Lead time' in logistics refers to the time between ___ and delivery.", ["ordering", "paying", "manufacturing", "advertising"], "ordering"),
  q("A2", "use_of_english", "finance", "'Break even' means the company has ___ profit or loss.", ["neither", "only", "much", "some"], "neither"),
  q("A2", "use_of_english", "marketing", "'Target audience' refers to the group of people a company wants to ___.", ["sell to", "hire", "train", "fire"], "sell to"),
  q("A2", "use_of_english", "reports", "'Year-on-year' compares data from ___ period.", ["the same", "a different", "a random", "any"], "the same"),
  q("A2", "use_of_english", "presentations", "'Moving on to the next point' is used to ___ topics.", ["change", "repeat", "cancel", "avoid"], "change"),
  q("A2", "use_of_english", "negotiations", "'Counteroffer' means a ___ in response to a first offer.", ["new proposal", "final decision", "written complaint", "legal action"], "new proposal"),

  q("B1", "use_of_english", "business_email", "The expression 'at your earliest convenience' means ___.", ["as soon as possible for you", "immediately without delay", "whenever you feel like it", "at the end of the year"], "as soon as possible for you"),
  q("B1", "use_of_english", "meetings", "'To table a discussion' in British English means to ___.", ["propose it for discussion", "cancel the meeting", "end the argument", "reject the idea"], "propose it for discussion"),
  q("B1", "use_of_english", "customer_service", "'Escalate an issue' means to ___.", ["refer it to a higher authority", "ignore the problem", "solve it immediately", "make it worse"], "refer it to a higher authority"),
  q("B1", "use_of_english", "hr", "'Headcount' in HR refers to the ___.", ["total number of employees", "number of managers", "salary budget", "office capacity"], "total number of employees"),
  q("B1", "use_of_english", "logistics", "'Just-in-time' delivery means items arrive ___.", ["exactly when needed", "very early", "very late", "in large quantities"], "exactly when needed"),
  q("B1", "use_of_english", "finance", "'Cash flow' refers to the movement of ___ in and out of a business.", ["money", "products", "employees", "documents"], "money"),
  q("B1", "use_of_english", "marketing", "'Brand awareness' measures how well people ___ a brand.", ["recognize", "produce", "compete with", "ignore"], "recognize"),
  q("B1", "use_of_english", "reports", "'Quarter-on-quarter' growth means comparing ___.", ["three-month periods", "monthly figures", "daily data", "annual results"], "three-month periods"),
  q("B1", "use_of_english", "presentations", "A 'takeaway' from a presentation is the ___.", ["key message to remember", "food served after", "printed copy", "list of attendees"], "key message to remember"),
  q("B1", "use_of_english", "negotiations", "'Walk away from a deal' means to ___.", ["refuse and leave", "accept eagerly", "ask for more time", "sign the contract"], "refuse and leave"),

  q("B2", "use_of_english", "business_email", "'Please do not hesitate to contact us' is an example of ___.", ["formulaic business language", "informal slang", "technical jargon", "academic writing"], "formulaic business language"),
  q("B2", "use_of_english", "meetings", "'To play devil's advocate' means to ___.", ["argue the opposite position deliberately", "refuse to participate", "strongly support a position", "act dishonestly"], "argue the opposite position deliberately"),
  q("B2", "use_of_english", "customer_service", "'Service-level agreement' (SLA) defines ___.", ["expected service standards", "employee salaries", "product prices", "marketing strategies"], "expected service standards"),
  q("B2", "use_of_english", "hr", "'Golden handshake' refers to a ___.", ["generous severance package", "warm welcome for new employees", "salary increase", "company award"], "generous severance package"),
  q("B2", "use_of_english", "logistics", "'Supply chain bottleneck' refers to a ___.", ["point causing delays in the process", "successful delivery", "new supplier", "storage solution"], "point causing delays in the process"),
  q("B2", "use_of_english", "finance", "'Due diligence' in finance involves ___.", ["thorough investigation before a transaction", "quick financial review", "employee evaluation", "product testing"], "thorough investigation before a transaction"),
  q("B2", "use_of_english", "marketing", "'Market penetration' refers to ___.", ["the extent a product is recognized in a market", "advertising costs", "competitor analysis", "product development"], "the extent a product is recognized in a market"),
  q("B2", "use_of_english", "reports", "'Benchmark' in business means a ___.", ["standard for comparison", "financial penalty", "marketing strategy", "production target"], "standard for comparison"),
  q("B2", "use_of_english", "presentations", "The phrase 'That brings me to my next point' is used for ___.", ["transitioning between topics", "concluding a speech", "asking a question", "introducing yourself"], "transitioning between topics"),
  q("B2", "use_of_english", "negotiations", "'BATNA' stands for Best Alternative To a Negotiated ___.", ["Agreement", "Action", "Approach", "Assessment"], "Agreement"),

  q("C1", "use_of_english", "business_email", "'Herewith' and 'henceforth' are examples of ___ language in business correspondence.", ["archaic formal", "contemporary informal", "technical scientific", "colloquial conversational"], "archaic formal"),
  q("C1", "use_of_english", "meetings", "The expression 'to circle back' in corporate contexts means to ___.", ["return to a topic later", "avoid responsibility", "create confusion", "end the discussion"], "return to a topic later"),
  q("C1", "use_of_english", "customer_service", "'Voice of the customer' (VoC) is a methodology for ___.", ["capturing customer expectations and preferences", "recording phone calls", "training service agents", "measuring response times"], "capturing customer expectations and preferences"),
  q("C1", "use_of_english", "hr", "'Talent pipeline' refers to ___.", ["a pool of potential candidates for future roles", "the company payroll system", "the employee exit process", "the training curriculum"], "a pool of potential candidates for future roles"),
  q("C1", "use_of_english", "logistics", "'Lean manufacturing' aims to ___.", ["minimize waste while maximizing productivity", "increase storage capacity", "hire more workers", "extend delivery times"], "minimize waste while maximizing productivity"),
  q("C1", "use_of_english", "finance", "'Amortization' in accounting refers to ___.", ["gradual reduction of debt through periodic payments", "immediate full payment", "equity distribution", "tax evasion strategy"], "gradual reduction of debt through periodic payments"),
  q("C1", "use_of_english", "marketing", "'Disruptive innovation' describes a product or service that ___.", ["creates a new market and displaces established competitors", "copies existing products", "targets the luxury segment", "reduces advertising spend"], "creates a new market and displaces established competitors"),
  q("C1", "use_of_english", "reports", "A 'white paper' in business is ___.", ["an authoritative report on a complex issue", "a blank document", "an informal memo", "a financial statement"], "an authoritative report on a complex issue"),
  q("C1", "use_of_english", "presentations", "'Rhetoric' in presentations refers to ___.", ["the art of persuasive speaking", "the use of visual aids", "the time management", "the audience interaction"], "the art of persuasive speaking"),
  q("C1", "use_of_english", "negotiations", "'Quid pro quo' in negotiations means ___.", ["something given in exchange for something", "a final ultimatum", "an opening offer", "a legal requirement"], "something given in exchange for something"),
];

const readingQuestions: QuestionDef[] = [
  q("A0", "reading", "business_email", "What does the email say?", ["The office is closed today", "The meeting is at 2 PM", "You have a new job", "Please buy lunch"],
    "The office is closed today",
    "Subject: Office Closed\nDear Staff,\nThe office is closed today. Please stay home.\nThank you."),
  q("A0", "reading", "customer_service", "What does the sign say?", ["Open from 9 to 5", "Closed forever", "Free food inside", "No parking here"],
    "Open from 9 to 5",
    "SHOP HOURS\nOpen: 9:00 AM - 5:00 PM\nMonday to Friday"),
  q("A0", "reading", "hr", "What is John's job?", ["He is a driver", "He is a doctor", "He is a teacher", "He is a chef"],
    "He is a driver",
    "My name is John. I am a driver. I drive a big truck."),
  q("A0", "reading", "logistics", "When does the delivery come?", ["In the morning", "At night", "On Sunday", "Never"],
    "In the morning",
    "Your package will arrive in the morning. Please be at home."),
  q("A0", "reading", "meetings", "What time is the meeting?", ["At 10 AM", "At 3 PM", "At 8 PM", "At noon"],
    "At 10 AM",
    "MEETING\nTime: 10:00 AM\nRoom: 5\nPlease come on time."),
  q("A0", "reading", "finance", "How much is it?", ["10 euros", "100 euros", "1 euro", "1000 euros"],
    "10 euros",
    "Price: 10 euros. Please pay at the desk."),
  q("A0", "reading", "marketing", "What is on sale?", ["Shoes", "Food", "Cars", "Houses"],
    "Shoes",
    "BIG SALE!\nShoes - 50% off!\nThis week only."),
  q("A0", "reading", "reports", "How many people work here?", ["Five", "Ten", "Twenty", "One hundred"],
    "Five",
    "Our team has five people. We work together every day."),
  q("A0", "reading", "presentations", "What is the presentation about?", ["New products", "Old buildings", "Sports", "Animals"],
    "New products",
    "PRESENTATION TODAY\nTopic: New Products\nRoom 3 - 2:00 PM"),
  q("A0", "reading", "negotiations", "Who wrote this?", ["The manager", "A customer", "A student", "A doctor"],
    "The manager",
    "From: The Manager\nTo: All Staff\nPlease come to work on time."),

  q("A1", "reading", "business_email", "What is the purpose of the email?", ["To confirm a meeting time", "To cancel a project", "To announce a holiday", "To request a salary increase"],
    "To confirm a meeting time",
    "Dear Team,\nI'm writing to confirm our meeting tomorrow at 3 PM in Conference Room B. Please bring your project updates.\nBest,\nSarah"),
  q("A1", "reading", "customer_service", "What is the customer's problem?", ["The product arrived damaged", "The price was too high", "The delivery was early", "The product was the wrong color"],
    "The product arrived damaged",
    "Dear Customer Service,\nI received my order today but the box was broken and the product inside is damaged. Can I get a replacement?\nThank you,\nMark"),
  q("A1", "reading", "hr", "What benefit does the company offer?", ["Free parking", "A company car", "Daily meals", "Gym membership"],
    "Free parking",
    "Welcome to ABC Company!\nWe offer free parking for all employees. Please register your car at reception.\nHR Department"),
  q("A1", "reading", "logistics", "When will the order arrive?", ["In 3-5 business days", "Tomorrow", "In one hour", "Next month"],
    "In 3-5 business days",
    "Order Confirmation\nThank you for your order! Your items will be shipped today and will arrive in 3-5 business days.\nTracking details will follow."),
  q("A1", "reading", "meetings", "What should employees bring to the meeting?", ["Their sales numbers", "Their lunch", "Their laptops", "Their ID cards"],
    "Their sales numbers",
    "Team Meeting - Friday at 9 AM\nPlease prepare your sales numbers for this month. We will review performance.\nManager"),
  q("A1", "reading", "finance", "What does the notice say about payment?", ["Payment is due within 30 days", "Payment is not required", "Payment was already made", "Payment is due immediately"],
    "Payment is due within 30 days",
    "INVOICE #1234\nAmount: €500.00\nPayment terms: Net 30 days\nPlease pay within 30 days of this invoice date."),
  q("A1", "reading", "marketing", "What is being promoted?", ["A summer sale event", "A new office location", "A job opening", "A company merger"],
    "A summer sale event",
    "SUMMER SALE!\nAll items 20% off from June 1-15.\nVisit our store or shop online.\nDon't miss out!"),
  q("A1", "reading", "reports", "What increased this year?", ["The number of customers", "The number of offices", "The number of holidays", "The number of products"],
    "The number of customers",
    "Annual Summary: Our customer base grew by 10% this year. We now have 5,000 customers in the region. Thank you for your hard work!"),
  q("A1", "reading", "presentations", "What topic will be discussed?", ["Company goals for next year", "Employee birthdays", "Office decoration", "Travel plans"],
    "Company goals for next year",
    "All-Staff Presentation\nDate: January 15\nTopic: Company Goals for 2026\nLocation: Main Hall\nAttendance is required."),
  q("A1", "reading", "negotiations", "What does the supplier offer?", ["A 5% discount for large orders", "Free shipping worldwide", "A 50% price reduction", "Extended warranty"],
    "A 5% discount for large orders",
    "Dear Customer,\nFor orders over 1,000 units, we can offer a 5% discount. Please let us know if you'd like to proceed.\nBest regards,\nSupplier"),

  q("A2", "reading", "business_email", "What action is the sender requesting?", ["Feedback on the proposal by Thursday", "Approval to hire new staff", "Permission for a business trip", "A meeting to discuss budgets"],
    "Feedback on the proposal by Thursday",
    "Dear Colleagues,\nPlease review the attached marketing proposal and send me your feedback by Thursday. We need to finalize it before the client meeting on Friday.\nThanks,\nLucia"),
  q("A2", "reading", "customer_service", "What solution does the company offer?", ["A replacement product or full refund", "Only an apology", "A discount on future purchases", "Free shipping on the next order"],
    "A replacement product or full refund",
    "Dear Customer,\nWe apologize for the inconvenience. We can offer you either a replacement product or a full refund. Please let us know your preference and we will process it within 48 hours.\nCustomer Service Team"),
  q("A2", "reading", "hr", "What is the new policy about?", ["Working from home two days per week", "Wearing uniforms", "Mandatory overtime", "Parking restrictions"],
    "Working from home two days per week",
    "To: All Staff\nSubject: New Remote Work Policy\nEffective March 1st, employees may work from home up to two days per week with manager approval. Please submit your preferred days by February 15th.\nHR"),
  q("A2", "reading", "logistics", "Why was the delivery delayed?", ["Bad weather conditions", "Wrong address", "Product out of stock", "System error"],
    "Bad weather conditions",
    "Dear Customer,\nWe regret to inform you that your delivery has been delayed due to severe weather conditions in the region. We expect it to arrive within the next 2-3 days. We apologize for any inconvenience.\nLogistics Team"),
  q("A2", "reading", "meetings", "What was decided at the meeting?", ["To postpone the product launch by two weeks", "To cancel the project", "To hire more staff", "To reduce the budget"],
    "To postpone the product launch by two weeks",
    "Meeting Minutes - March 5\nAttendees: Marketing Team\nDecision: The product launch will be postponed by two weeks to allow for additional testing. New launch date: March 25th.\nAction: All team members to update their schedules."),
  q("A2", "reading", "finance", "What happened to company expenses?", ["They increased by 8% compared to last year", "They decreased significantly", "They stayed the same", "They doubled"],
    "They increased by 8% compared to last year",
    "Financial Update Q3\nTotal expenses this quarter: €2.1 million, an increase of 8% compared to the same period last year. The main drivers were higher energy costs and new hiring."),
  q("A2", "reading", "marketing", "Who is the target audience for the campaign?", ["Small business owners", "Teenagers", "Retirees", "Government officials"],
    "Small business owners",
    "Campaign Brief: 'Grow Your Business'\nTarget: Small business owners aged 25-45\nChannels: Social media, email marketing\nBudget: €15,000\nDuration: 4 weeks starting April 1st"),
  q("A2", "reading", "reports", "What does the report recommend?", ["Investing in employee training", "Closing the branch office", "Reducing working hours", "Changing the company name"],
    "Investing in employee training",
    "Quarterly Performance Report\nKey Finding: Customer satisfaction scores dropped 5% due to longer wait times.\nRecommendation: Invest in additional employee training to improve response efficiency and service quality."),
  q("A2", "reading", "presentations", "What was the main point of the presentation?", ["The company will expand to three new markets", "All offices will close", "Salaries will be reduced", "The CEO is retiring"],
    "The company will expand to three new markets",
    "Presentation Summary: Q4 Strategy\nThe CEO announced that the company will expand operations to three new markets in Southeast Asia by the end of next year. The expansion will be funded by recent investor contributions."),
  q("A2", "reading", "negotiations", "What terms did both parties agree on?", ["A 10% volume discount with 60-day payment terms", "Free products for a year", "Exclusive distribution rights", "Price matching with competitors"],
    "A 10% volume discount with 60-day payment terms",
    "Negotiation Summary\nParties: ABC Corp and XYZ Suppliers\nAgreed Terms: 10% volume discount on orders over 500 units, payment terms extended to 60 days. Contract valid for 12 months."),

  q("B1", "reading", "business_email", "What is the main concern expressed in the email?", ["Quality issues with the latest batch of components", "Late payment by a client", "Staff shortages during summer", "IT system failures"],
    "Quality issues with the latest batch of components",
    "Dear Procurement Team,\nI'm writing to raise concerns about the quality of the latest batch of components received from Supplier X. Our QC department identified defects in 15% of the units, which is well above our acceptable threshold of 2%. I recommend we schedule an urgent review meeting with the supplier and consider activating our backup supplier agreement.\nRegards,\nDavid Chen, Production Manager"),
  q("B1", "reading", "customer_service", "What is the company's service guarantee?", ["Response within 4 hours and resolution within 24 hours", "Immediate response to all queries", "Resolution within one week", "Monthly follow-up calls"],
    "Response within 4 hours and resolution within 24 hours",
    "Service Level Agreement - Premium Support\nOur premium service guarantee includes: initial response within 4 hours of ticket submission, full resolution within 24 hours for standard issues, dedicated account manager for escalated concerns, and monthly performance reporting. Violations of these SLAs will result in service credits."),
  q("B1", "reading", "hr", "What change is being implemented?", ["A new performance evaluation system based on OKRs", "Mandatory overtime policy", "Salary reductions across departments", "Office relocation to a smaller building"],
    "A new performance evaluation system based on OKRs",
    "To: All Managers\nSubject: New Performance Evaluation Framework\nWe are transitioning from our current annual review system to quarterly OKR-based evaluations starting Q2. Each team member will set 3-5 objectives with measurable key results. Training sessions for managers will be held in March. Please encourage your teams to attend."),
  q("B1", "reading", "logistics", "What strategy is being proposed?", ["Implementing a regional hub-and-spoke distribution model", "Outsourcing all deliveries", "Reducing the number of warehouses", "Moving to air freight exclusively"],
    "Implementing a regional hub-and-spoke distribution model",
    "Distribution Strategy Proposal\nTo reduce delivery times across Southern Europe, we propose implementing a hub-and-spoke model with regional distribution centers in Milan, Barcelona, and Marseille. Initial analysis suggests this could reduce average delivery times by 35% while maintaining cost efficiency through consolidated bulk shipments to hubs."),
  q("B1", "reading", "meetings", "What was the outcome of the board meeting?", ["Approval to proceed with the acquisition pending due diligence", "Rejection of the merger proposal", "Decision to postpone all investments", "Agreement to sell the company"],
    "Approval to proceed with the acquisition pending due diligence",
    "Board Meeting Summary - Confidential\nThe board voted 7-2 to approve proceeding with the acquisition of TechStart Ltd., subject to satisfactory completion of due diligence within 90 days. The CFO was tasked with leading the financial review team. Legal counsel will prepare preliminary acquisition documentation."),
  q("B1", "reading", "finance", "What financial risk is highlighted?", ["Currency exchange rate fluctuations affecting import costs", "Employee theft", "Building maintenance costs", "Advertising budget overruns"],
    "Currency exchange rate fluctuations affecting import costs",
    "Risk Assessment Report\nKey Financial Risk: Our increasing reliance on Asian suppliers exposes us to significant currency exchange rate fluctuations. The EUR/CNY volatility over the past quarter has added an estimated 3.5% to our import costs. We recommend implementing a hedging strategy to mitigate this exposure."),
  q("B1", "reading", "marketing", "What does the market research indicate?", ["A growing preference for sustainable products among consumers aged 25-40", "Declining interest in online shopping", "Increased demand for luxury goods", "A shift towards traditional advertising channels"],
    "A growing preference for sustainable products among consumers aged 25-40",
    "Market Research Findings - Q3\nOur survey of 2,500 consumers reveals a significant shift: 67% of respondents aged 25-40 now consider sustainability a key purchasing factor, up from 42% two years ago. This trend is particularly pronounced in the food and fashion sectors. Brands perceived as environmentally responsible saw 23% higher customer retention rates."),
  q("B1", "reading", "reports", "What does the analysis conclude?", ["Remote workers are 12% more productive but require structured communication protocols", "Office workers outperform remote workers", "Remote work should be eliminated", "All employees prefer office work"],
    "Remote workers are 12% more productive but require structured communication protocols",
    "Workplace Productivity Analysis\nOur six-month study comparing remote and office-based workers found that remote employees completed 12% more tasks per week on average. However, collaborative projects showed a 9% decline in completion speed. The data suggests that remote work is beneficial when paired with structured communication protocols and regular virtual check-ins."),
  q("B1", "reading", "presentations", "What innovation is being presented?", ["An AI-powered customer service chatbot that handles 70% of routine queries", "A new company logo", "A redesigned website", "A new employee uniform"],
    "An AI-powered customer service chatbot that handles 70% of routine queries",
    "Innovation Showcase - Customer Experience\nWe developed an AI-powered chatbot that handles approximately 70% of routine customer queries without human intervention. Since deployment three months ago, average response time has dropped from 4 hours to under 2 minutes, and customer satisfaction scores for first-contact resolution have improved by 18%."),
  q("B1", "reading", "negotiations", "What is the key negotiation point?", ["Exclusivity rights in the European market for a minimum three-year term", "Price reduction of 50%", "Same-day delivery guarantee", "Unlimited free returns"],
    "Exclusivity rights in the European market for a minimum three-year term",
    "Negotiation Brief - Partnership with GlobalTech\nOur priority is to secure exclusivity rights for the European market for a minimum three-year term. In exchange, we are prepared to commit to minimum annual purchase volumes of €2M and co-invest in localized marketing. The fallback position is non-exclusive distribution with preferential pricing."),

  q("B2", "reading", "business_email", "What strategic shift does the email announce?", ["Moving from a product-centric to a customer-centric business model", "Downsizing the workforce", "Merging with a competitor", "Relocating headquarters overseas"],
    "Moving from a product-centric to a customer-centric business model",
    "Dear Senior Leadership,\nFollowing extensive market analysis and stakeholder consultation, we have made the strategic decision to transition from our traditional product-centric approach to a customer-centric business model. This transformation will require fundamental changes to our organizational structure, including the creation of cross-functional customer journey teams, investment in CRM infrastructure, and a comprehensive retraining programme. The transition roadmap, attached herewith, outlines a phased implementation over 18 months.\nBest regards,\nThe Strategy Committee"),
  q("B2", "reading", "customer_service", "What approach is described for handling difficult customers?", ["The HEARD framework: Hear, Empathize, Apologize, Resolve, Diagnose", "Transferring all calls to management", "Offering automatic refunds", "Sending scripted responses"],
    "The HEARD framework: Hear, Empathize, Apologize, Resolve, Diagnose",
    "Advanced Customer Recovery Training - Module 3\nWhen dealing with escalated complaints, employ the HEARD framework: Hear the customer without interrupting, Empathize by acknowledging their frustration, Apologize sincerely regardless of fault attribution, Resolve by offering concrete solutions with timelines, and Diagnose root causes to prevent recurrence. Research shows this approach achieves 85% customer retention in complaint scenarios."),
  q("B2", "reading", "hr", "What HR trend does the article discuss?", ["Skills-based hiring over traditional degree requirements", "Mandatory return-to-office policies", "Reduction in employee benefits", "Increase in retirement age"],
    "Skills-based hiring over traditional degree requirements",
    "HR Trends Report 2026\nA significant shift is underway in talent acquisition: leading organizations are increasingly adopting skills-based hiring practices, deprioritizing traditional degree requirements in favour of demonstrated competencies. Companies implementing this approach report a 40% increase in candidate pool diversity and a 25% improvement in first-year retention rates. This paradigm shift requires substantial investment in assessment methodologies and hiring manager training."),
  q("B2", "reading", "logistics", "What challenge does the article describe?", ["Balancing just-in-time efficiency with supply chain resilience", "Finding warehouse space", "Recruiting delivery drivers", "Choosing software systems"],
    "Balancing just-in-time efficiency with supply chain resilience",
    "Supply Chain Strategy in a Volatile World\nThe pandemic exposed fundamental vulnerabilities in lean, just-in-time supply chains. Leading organizations now face the paradox of maintaining efficiency while building resilience. The emerging consensus favours a 'just-in-case' buffer strategy: maintaining 15-20% safety stock for critical components while applying lean principles to non-critical categories. This hybrid approach typically increases inventory costs by 8-12% but dramatically reduces supply disruption risk."),
  q("B2", "reading", "finance", "What financial strategy is recommended?", ["Diversifying revenue streams through adjacent market entry", "Cutting all research and development spending", "Borrowing heavily to fund expansion", "Focusing exclusively on the domestic market"],
    "Diversifying revenue streams through adjacent market entry",
    "CFO Advisory: Revenue Diversification\nOverreliance on a single revenue stream exposes organizations to disproportionate risk. We recommend a systematic approach to adjacent market entry, leveraging existing core competencies to develop complementary revenue channels. Analysis of our portfolio companies shows that those with three or more significant revenue streams demonstrated 60% greater resilience during economic downturns and achieved 35% higher valuations."),
  q("B2", "reading", "meetings", "What governance change was approved?", ["Establishment of a sustainability oversight committee reporting to the board", "Elimination of all committees", "Monthly board meetings instead of quarterly", "Outsourcing corporate governance"],
    "Establishment of a sustainability oversight committee reporting to the board",
    "Annual General Meeting Minutes - Extraordinary Session\nThe shareholders approved the establishment of a dedicated Sustainability Oversight Committee, reporting directly to the Board of Directors. The committee will comprise three independent directors with relevant expertise, and will be tasked with overseeing ESG compliance, setting carbon neutrality targets, and ensuring alignment with EU sustainability reporting directives."),
  q("B2", "reading", "marketing", "What is the key insight about digital marketing?", ["Personalization at scale drives 3x higher conversion than generic campaigns", "Print advertising is more effective than digital", "Social media marketing is declining", "Email marketing is no longer effective"],
    "Personalization at scale drives 3x higher conversion than generic campaigns",
    "Digital Marketing Intelligence Brief\nOur analysis of 500+ campaigns across multiple sectors reveals that personalization at scale—leveraging AI-driven customer segmentation and dynamic content generation—drives conversion rates approximately three times higher than generic campaigns. However, effectiveness is contingent upon data quality: organizations investing in first-party data infrastructure achieved 45% better personalization outcomes than those relying on third-party cookies."),
  q("B2", "reading", "reports", "What does the ESG report recommend?", ["Integrating carbon accounting into standard financial reporting processes", "Ignoring environmental concerns", "Reducing sustainability spending", "Delaying climate action until competitors act"],
    "Integrating carbon accounting into standard financial reporting processes",
    "ESG Integration Report\nAs regulatory requirements intensify and investor scrutiny of environmental metrics grows, we recommend integrating carbon accounting into standard financial reporting processes. Our analysis suggests that companies proactively adopting integrated reporting frameworks experience lower cost of capital (average reduction of 50 basis points) and stronger institutional investor interest."),
  q("B2", "reading", "presentations", "What does the case study demonstrate?", ["That organizational agility during crises is driven by decentralized decision-making", "That large companies are always more successful", "That technology is not important", "That employee satisfaction doesn't affect performance"],
    "That organizational agility during crises is driven by decentralized decision-making",
    "Case Study: Organizational Agility in Crisis\nWhen the supply chain crisis hit in 2024, companies with decentralized decision-making structures responded an average of 4.5 weeks faster than their hierarchically organized counterparts. The key differentiator was empowering middle management to make tactical adjustments within defined parameters without requiring escalation to C-suite level. This case study examines three organizations that exemplified this adaptive approach."),
  q("B2", "reading", "negotiations", "What negotiation strategy is discussed?", ["Using anchoring bias by making the first offer to frame the negotiation range", "Always accepting the first offer", "Avoiding any concessions", "Letting the other party set all terms"],
    "Using anchoring bias by making the first offer to frame the negotiation range",
    "Advanced Negotiation Tactics - Module 7: Anchoring\nResearch in behavioral economics demonstrates that the first offer in any negotiation creates a powerful cognitive anchor that influences the entire discussion range. Studies show that negotiators who make the first offer achieve outcomes approximately 15% more favorable than those who wait. The key is calibrating your anchor: aggressive enough to create favorable range, but reasonable enough to maintain credibility and avoid the counter-party walking away."),

  q("C1", "reading", "business_email", "What organizational paradox does the email address?", ["The tension between innovation agility and regulatory compliance in digital transformation", "The difficulty of scheduling meetings", "Employee parking allocation issues", "Budget constraints for office supplies"],
    "The tension between innovation agility and regulatory compliance in digital transformation",
    "Dear Board Members,\nOur digital transformation initiative has surfaced a fundamental organizational paradox: the imperative for innovation agility increasingly conflicts with our regulatory compliance obligations. Our fintech division, operating in sandbox environments, has developed several potentially market-disrupting products, yet the average time from prototype to regulatory approval is 14 months—rendering first-mover advantage largely theoretical. I propose we establish a dedicated regulatory innovation liaison function, embedded within product development teams, to harmonize these competing priorities.\nRegards,\nChief Digital Officer"),
  q("C1", "reading", "customer_service", "What paradigm shift does the article describe?", ["The evolution from reactive issue resolution to predictive customer experience orchestration", "Using chatbots for all customer interactions", "Reducing customer service staff", "Moving to email-only support"],
    "The evolution from reactive issue resolution to predictive customer experience orchestration",
    "The Next Frontier in Customer Experience\nThe customer service paradigm is undergoing a fundamental shift: from reactive issue resolution to predictive experience orchestration. By leveraging machine learning algorithms trained on interaction patterns, sentiment analysis, and behavioral signals, leading organizations now identify and address potential pain points before customers articulate dissatisfaction. Companies implementing predictive CX report a 45% reduction in churn and a 60% improvement in customer lifetime value."),
  q("C1", "reading", "hr", "What leadership model is proposed?", ["Ambidextrous leadership that simultaneously drives exploitation and exploration", "Autocratic decision-making in all situations", "Complete delegation to junior staff", "Eliminating management layers entirely"],
    "Ambidextrous leadership that simultaneously drives exploitation and exploration",
    "Leadership in the Age of Perpetual Disruption\nTraditional leadership models—whether transformational or transactional—prove insufficient in environments characterized by simultaneous disruption across multiple fronts. We propose an ambidextrous leadership framework that enables executives to simultaneously drive exploitation (optimizing existing operations) and exploration (pursuing radical innovation). Our longitudinal study of 200 organizations demonstrates that those with ambidextrous leadership capabilities achieved 70% higher total shareholder returns over a five-year period."),
  q("C1", "reading", "logistics", "What paradigm is discussed?", ["The shift from linear supply chains to circular supply networks", "Same-day delivery logistics", "Drone-based package delivery", "Traditional warehousing methods"],
    "The shift from linear supply chains to circular supply networks",
    "Reimagining Supply Chain Architecture\nThe transition from linear 'take-make-dispose' supply chains to circular supply networks represents perhaps the most consequential paradigm shift in modern logistics. Circular models—integrating reverse logistics, remanufacturing, and material recovery—require fundamentally different optimization algorithms, contract structures, and performance metrics. Organizations that successfully navigate this transition report not only reduced environmental impact but also 20-30% improvements in long-term material cost stability."),
  q("C1", "reading", "finance", "What financial concept is analyzed?", ["The limitations of traditional DCF models in valuing platform-based business models", "Basic compound interest calculations", "Standard balance sheet analysis", "Simple profit margin computation"],
    "The limitations of traditional DCF models in valuing platform-based business models",
    "Rethinking Valuation Methodologies\nTraditional discounted cash flow (DCF) models, while robust for asset-heavy businesses with predictable revenue streams, prove increasingly inadequate for valuing platform-based business models. Network effects, winner-take-most dynamics, and the option value of ecosystem expansion create valuation dimensions that linear cash flow projections cannot capture. We examine alternative frameworks incorporating real options theory and network economics to produce more nuanced valuations."),
  q("C1", "reading", "marketing", "What strategy does the article advocate?", ["Building brand equity through authentic stakeholder capitalism narratives", "Maximizing short-term sales through aggressive discounting", "Reducing marketing budget to zero", "Copying competitor strategies exactly"],
    "Building brand equity through authentic stakeholder capitalism narratives",
    "Brand Strategy in the Stakeholder Capitalism Era\nAs consumer sentiment increasingly favors purpose-driven brands, the temptation to engage in 'purpose washing' represents a significant reputational risk. Our research demonstrates that authentic stakeholder capitalism narratives—those backed by verifiable operational changes and transparent impact reporting—generate 4x the brand equity of superficial cause-marketing campaigns. The key differentiator is institutional commitment: embedding purpose into governance structures rather than treating it as a marketing tactic."),
  q("C1", "reading", "reports", "What does the analysis reveal?", ["That ESG metrics correlate more strongly with long-term financial performance than previously assumed", "That ESG is irrelevant to financial success", "That short-term profits matter most", "That environmental reporting is unnecessary"],
    "That ESG metrics correlate more strongly with long-term financial performance than previously assumed",
    "Meta-Analysis: ESG and Financial Performance\nOur meta-analysis of 2,000+ studies examining the relationship between ESG metrics and financial performance reveals a stronger correlation than previously established in literature. Companies in the top quartile of ESG performance demonstrated a 15% lower cost of equity, 25% lower earnings volatility, and 30% higher operating margins over a decade-long observation period. These findings persist even after controlling for sector, geography, and company size."),
  q("C1", "reading", "presentations", "What concept is examined?", ["Cognitive load theory applied to executive communication in information-dense environments", "Basic slide design principles", "Font size recommendations", "Color scheme selection"],
    "Cognitive load theory applied to executive communication in information-dense environments",
    "The Art of Executive Communication\nIn an era of information overload, the application of cognitive load theory to executive communication has become critical. Research demonstrates that presentations exceeding seven key data points suffer from a 40% comprehension decline. The most effective executive communicators employ 'progressive disclosure'—structuring information in hierarchical layers that allow audiences to absorb complexity incrementally while maintaining narrative coherence."),
  q("C1", "reading", "meetings", "What governance challenge is discussed?", ["Ensuring boardroom cognitive diversity while maintaining strategic coherence", "Scheduling conflicts between directors", "Catering preferences for board meetings", "Technology issues during virtual meetings"],
    "Ensuring boardroom cognitive diversity while maintaining strategic coherence",
    "Board Effectiveness in Complex Organizations\nContemporary governance research highlights a persistent tension in board composition: the imperative for cognitive diversity—incorporating varied perspectives, expertise, and thinking styles—must be balanced against the need for strategic coherence. Boards that successfully navigate this tension typically employ structured decision-making frameworks that channel diverse viewpoints into coherent strategic direction without suppressing dissent or encouraging groupthink."),
  q("C1", "reading", "negotiations", "What negotiation framework is proposed?", ["Integrative multi-party negotiation using principled interests rather than positions", "Competitive zero-sum bargaining", "Avoiding negotiation entirely", "Accepting all demands without discussion"],
    "Integrative multi-party negotiation using principled interests rather than positions",
    "Beyond Win-Win: Multi-Stakeholder Negotiation in Complex Ecosystems\nTraditional bilateral negotiation frameworks prove insufficient in modern business environments where decisions increasingly involve multiple stakeholders with interconnected interests. We propose an integrative multi-party negotiation model based on principled interests rather than positional bargaining. By mapping the full stakeholder ecosystem and identifying zones of possible agreement across all parties simultaneously, negotiators can unlock value that bilateral approaches systematically overlook."),
];

const listeningQuestions: QuestionDef[] = [
  q("A0", "listening", "business_email", "You hear someone say 'My name is Anna.' What is the person's name?", ["Anna", "Maria", "Lisa", "Sara"], "Anna"),
  q("A0", "listening", "meetings", "Someone says 'The meeting is at two o'clock.' When is the meeting?", ["At 2:00", "At 3:00", "At 4:00", "At 1:00"], "At 2:00"),
  q("A0", "listening", "customer_service", "A person says 'I need help, please.' What does the person want?", ["Help", "Food", "Money", "A car"], "Help"),
  q("A0", "listening", "hr", "You hear: 'I work in the office.' Where does the person work?", ["In the office", "At home", "In a restaurant", "In a hospital"], "In the office"),
  q("A0", "listening", "logistics", "Someone says 'The box is on the table.' Where is the box?", ["On the table", "Under the chair", "In the car", "Behind the door"], "On the table"),
  q("A0", "listening", "finance", "You hear: 'It costs ten euros.' How much is it?", ["Ten euros", "Five euros", "Twenty euros", "Fifty euros"], "Ten euros"),
  q("A0", "listening", "marketing", "Someone says: 'This is a good product.' What does the person think?", ["The product is good", "The product is bad", "The product is expensive", "The product is old"], "The product is good"),
  q("A0", "listening", "reports", "You hear: 'We have five workers.' How many workers are there?", ["Five", "Three", "Seven", "Ten"], "Five"),
  q("A0", "listening", "presentations", "Someone says: 'Please look at the screen.' What should you do?", ["Look at the screen", "Close your eyes", "Leave the room", "Write a letter"], "Look at the screen"),
  q("A0", "listening", "negotiations", "You hear: 'Yes, I agree.' Does the person agree?", ["Yes", "No", "Maybe", "They don't say"], "Yes"),

  q("A1", "listening", "business_email", "In a phone call, someone says: 'I'll send you the information by email this afternoon.' When will they send it?", ["This afternoon", "Tomorrow morning", "Next week", "Right now"], "This afternoon"),
  q("A1", "listening", "meetings", "At a meeting, the chair says: 'Let's move on to the next item on the agenda.' What does the chair want to do?", ["Discuss a new topic", "End the meeting", "Take a break", "Go back to a previous topic"], "Discuss a new topic"),
  q("A1", "listening", "customer_service", "A customer says: 'I'd like to return this item because it doesn't work.' Why does the customer want to return it?", ["It is broken", "It is too expensive", "It is the wrong size", "They don't like the color"], "It is broken"),
  q("A1", "listening", "hr", "The HR manager says: 'Your first day will be Monday, March 3rd.' When does the new employee start?", ["Monday, March 3rd", "Friday, March 7th", "Wednesday, March 5th", "Tuesday, March 4th"], "Monday, March 3rd"),
  q("A1", "listening", "logistics", "A colleague says: 'The warehouse is on the second floor.' Where is the warehouse?", ["On the second floor", "In the basement", "On the ground floor", "On the roof"], "On the second floor"),
  q("A1", "listening", "finance", "The accountant says: 'We need to pay this bill before the end of the month.' When is the deadline?", ["Before the end of the month", "Before next year", "Before Friday", "Before the end of the week"], "Before the end of the month"),
  q("A1", "listening", "marketing", "In an ad: 'Buy one, get one free!' What is the offer?", ["Buy one item and get a second one for free", "Everything is half price", "Free delivery on all orders", "10% off your first purchase"], "Buy one item and get a second one for free"),
  q("A1", "listening", "reports", "A manager says: 'Sales went up by 10% this month.' What happened to sales?", ["They increased", "They decreased", "They stayed the same", "They stopped"], "They increased"),
  q("A1", "listening", "presentations", "The presenter says: 'As you can see from the graph, costs have fallen.' What does the graph show?", ["Costs decreased", "Costs increased", "Costs stayed the same", "There is no graph"], "Costs decreased"),
  q("A1", "listening", "negotiations", "One person says: 'Can you lower the price a little?' What are they asking for?", ["A discount", "More products", "Faster delivery", "Better quality"], "A discount"),

  q("A2", "listening", "business_email", "In a voicemail: 'Please call me back regarding the contract renewal. My extension is 4521.' What is the caller asking about?", ["Contract renewal", "A new job", "A meeting", "A product order"], "Contract renewal"),
  q("A2", "listening", "meetings", "The project manager says: 'We're behind schedule by two weeks, so we need to prioritize the remaining tasks.' What is the situation?", ["The project is delayed", "The project is ahead of schedule", "The project is cancelled", "The project is on time"], "The project is delayed"),
  q("A2", "listening", "customer_service", "A supervisor tells a team: 'From now on, all complaints must be logged in the system within one hour of receipt.' What is the new rule?", ["Log complaints within one hour", "Resolve complaints within one hour", "Forward complaints to management", "Call the customer back"], "Log complaints within one hour"),
  q("A2", "listening", "hr", "During an interview: 'Could you tell me about a time when you had to work under pressure?' What type of question is this?", ["A behavioral question", "A technical question", "A salary question", "A personal question"], "A behavioral question"),
  q("A2", "listening", "logistics", "The logistics coordinator says: 'We need to consolidate the two shipments into one to reduce costs.' What is the plan?", ["Combine two shipments into one", "Cancel one shipment", "Delay both shipments", "Send the shipments separately"], "Combine two shipments into one"),
  q("A2", "listening", "finance", "An analyst says: 'The exchange rate has moved in our favor, which will improve our margins.' What is the good news?", ["Profit margins will improve", "Sales will increase", "Costs will double", "Staff will get a raise"], "Profit margins will improve"),
  q("A2", "listening", "marketing", "In a team meeting: 'We should focus our social media efforts on LinkedIn and Instagram for this B2B campaign.' Which platforms are recommended?", ["LinkedIn and Instagram", "Facebook and Twitter", "TikTok and YouTube", "Pinterest and Snapchat"], "LinkedIn and Instagram"),
  q("A2", "listening", "reports", "A colleague says: 'The data shows a clear upward trend in customer retention over the past six months.' What is improving?", ["Customer retention", "Customer acquisition", "Revenue per customer", "Customer complaints"], "Customer retention"),
  q("A2", "listening", "presentations", "After the presentation: 'Could you elaborate on the implementation timeline you mentioned?' What does the audience member want?", ["More details about the timeline", "A copy of the slides", "The presenter's contact information", "A summary of the costs"], "More details about the timeline"),
  q("A2", "listening", "negotiations", "In a negotiation: 'We can agree to your delivery terms, but we need you to hold the price for six months.' What is the condition?", ["Price must stay the same for six months", "Delivery must be faster", "Payment terms must change", "The order quantity must increase"], "Price must stay the same for six months"),

  q("B1", "listening", "business_email", "In a conference call: 'I'm going to share my screen to walk you through the quarterly figures. As you'll see, our APAC region has outperformed expectations.' Which region performed well?", ["Asia-Pacific", "Europe", "North America", "Latin America"], "Asia-Pacific"),
  q("B1", "listening", "meetings", "A director says: 'Before we approve the budget, I'd like to see a cost-benefit analysis that includes both direct and indirect costs.' What is being requested?", ["A comprehensive cost-benefit analysis", "A simple budget summary", "A list of employees", "A marketing plan"], "A comprehensive cost-benefit analysis"),
  q("B1", "listening", "customer_service", "A trainer explains: 'When a customer is angry, your first priority should be to acknowledge their feelings before trying to solve the problem.' What should you do first?", ["Acknowledge the customer's feelings", "Offer a solution immediately", "Transfer the call to a manager", "Ask for the customer's details"], "Acknowledge the customer's feelings"),
  q("B1", "listening", "hr", "The HR director explains: 'We're implementing a competency framework that maps each role to specific skills and behaviors required at each career level.' What is being introduced?", ["A competency framework for career progression", "A new payroll system", "An attendance tracking tool", "A recruitment agency partnership"], "A competency framework for career progression"),
  q("B1", "listening", "logistics", "A supply chain manager says: 'We've identified a single point of failure in our distribution network. If the Rotterdam hub goes down, we have no backup route.' What is the risk?", ["No alternative route if the main hub fails", "Too many distribution centers", "Excessive inventory levels", "High transportation costs"], "No alternative route if the main hub fails"),
  q("B1", "listening", "finance", "A CFO states: 'Our working capital ratio has improved from 1.2 to 1.8, which gives us much more breathing room for short-term obligations.' What improved?", ["The company's short-term financial health", "Long-term investment returns", "Employee productivity", "Market share"], "The company's short-term financial health"),
  q("B1", "listening", "marketing", "A marketing director says: 'Our customer acquisition cost has dropped by 30%, but customer lifetime value has only increased by 5%. We need to focus on retention.' What is the concern?", ["Customers aren't staying long enough", "Acquisition is too expensive", "There aren't enough new customers", "The product quality is declining"], "Customers aren't staying long enough"),
  q("B1", "listening", "reports", "An analyst reports: 'Year-over-year, we've seen a 15% increase in recurring revenue, which now accounts for 60% of total revenue.' What percentage of revenue is recurring?", ["60%", "15%", "40%", "75%"], "60%"),
  q("B1", "listening", "presentations", "During a Q&A: 'That's a valid concern. Let me address it by sharing some data from our pilot program, which ran for six months across three markets.' How long was the pilot?", ["Six months", "Three months", "One year", "Two weeks"], "Six months"),
  q("B1", "listening", "negotiations", "A negotiator says: 'Our position is non-negotiable on exclusivity, but we have flexibility on pricing and payment terms.' What can be discussed?", ["Pricing and payment terms", "Exclusivity arrangements", "Territory rights", "Product specifications"], "Pricing and payment terms"),

  q("B2", "listening", "business_email", "In a strategy call: 'The synergies from this merger are primarily on the cost side—we estimate €50M in savings through headcount rationalization and shared services consolidation.' What is the main benefit of the merger?", ["Cost savings of €50M", "Revenue growth", "Market expansion", "Technology acquisition"], "Cost savings of €50M"),
  q("B2", "listening", "meetings", "A board member says: 'I'm concerned about the concentration risk in our revenue mix—three clients account for 45% of our income.' What is the concern?", ["Too much dependence on a few clients", "Revenue is too low", "There are too many clients", "Client payments are late"], "Too much dependence on a few clients"),
  q("B2", "listening", "customer_service", "A CX leader explains: 'We're moving from a transactional NPS measurement to a relational model that captures the entire customer journey.' What change is being made?", ["Measuring customer satisfaction across the full journey rather than individual transactions", "Switching to a new survey platform", "Reducing the number of surveys", "Focusing only on complaint resolution"], "Measuring customer satisfaction across the full journey rather than individual transactions"),
  q("B2", "listening", "hr", "A consultant says: 'The attrition data reveals that voluntary turnover peaks at the 18-month mark, suggesting gaps in medium-term engagement and career development.' When do employees most often leave?", ["Around 18 months", "In the first week", "After 5 years", "At retirement"], "Around 18 months"),
  q("B2", "listening", "logistics", "An operations director explains: 'We're implementing a control tower approach with real-time visibility across all tiers of our supply chain.' What is being implemented?", ["A centralized real-time monitoring system for the supply chain", "A new warehouse management system", "GPS tracking for delivery trucks", "An inventory counting procedure"], "A centralized real-time monitoring system for the supply chain"),
  q("B2", "listening", "finance", "An investor says: 'The company's EBITDA multiple of 12x seems justified given its growth trajectory, but the high leverage ratio of 4.5x debt-to-EBITDA gives me pause.' What concerns the investor?", ["The company's high level of debt", "The company's growth rate", "The company's market share", "The company's product quality"], "The company's high level of debt"),
  q("B2", "listening", "marketing", "A CMO states: 'Our attribution modeling suggests that the last-click model significantly undervalues our brand awareness campaigns at the top of the funnel.' What is the problem?", ["Brand awareness efforts are not getting proper credit in the current measurement model", "Too much is being spent on brand awareness", "The marketing budget is too small", "Competitors have better campaigns"], "Brand awareness efforts are not getting proper credit in the current measurement model"),
  q("B2", "listening", "reports", "A data scientist reports: 'The regression analysis shows that employee engagement scores are the strongest predictor of customer satisfaction, with an R-squared of 0.72.' What is the key finding?", ["Employee engagement strongly predicts customer satisfaction", "Customer satisfaction predicts employee engagement", "Sales predict customer satisfaction", "Marketing spend predicts engagement"], "Employee engagement strongly predicts customer satisfaction"),
  q("B2", "listening", "presentations", "A presenter concludes: 'To summarize, our competitive advantage lies not in any single capability but in the integration of our technology stack, talent density, and customer intimacy.' What creates the competitive advantage?", ["The combination of technology, talent, and customer relationships", "The company's technology alone", "The company's pricing strategy", "The company's market position"], "The combination of technology, talent, and customer relationships"),
  q("B2", "listening", "negotiations", "A lead negotiator says: 'We've reached an impasse on territorial rights. I suggest we park this issue and return to it after we've built more consensus on the commercial terms.' What strategy is being used?", ["Setting aside a difficult issue to make progress elsewhere first", "Ending the negotiation", "Making a final offer", "Bringing in a mediator"], "Setting aside a difficult issue to make progress elsewhere first"),

  q("C1", "listening", "business_email", "In an executive briefing: 'The strategic inflection point we're approaching requires us to cannibalize our own legacy product line before competitors do it for us.' What strategy is being advocated?", ["Proactively replacing own products before competitors can disrupt them", "Keeping legacy products indefinitely", "Focusing on cost reduction in existing products", "Partnering with competitors"], "Proactively replacing own products before competitors can disrupt them"),
  q("C1", "listening", "meetings", "A chairman states: 'The fiduciary obligations of this board extend beyond mere compliance—we have a duty of care to anticipate and mitigate systemic risks that could impair long-term value creation.' What is emphasized?", ["The board's responsibility to proactively manage long-term risks", "The need for better accounting software", "Short-term profit maximization", "Reducing the number of board meetings"], "The board's responsibility to proactively manage long-term risks"),
  q("C1", "listening", "customer_service", "A strategist explains: 'We need to shift from a service recovery paradigm to one of service prevention—using predictive analytics to identify and resolve pain points before they manifest as customer complaints.' What fundamental shift is described?", ["Moving from fixing problems after they occur to preventing them proactively", "Hiring more customer service agents", "Creating a longer FAQ document", "Reducing customer service hours"], "Moving from fixing problems after they occur to preventing them proactively"),
  q("C1", "listening", "hr", "A CHRO explains: 'Our people analytics initiative has revealed that cognitive diversity in teams—not demographic diversity alone—is the strongest predictor of innovation output.' What type of diversity matters most for innovation?", ["Cognitive diversity — different thinking styles and perspectives", "Age diversity", "Gender diversity alone", "Geographic diversity"], "Cognitive diversity — different thinking styles and perspectives"),
  q("C1", "listening", "logistics", "A VP of operations says: 'The transition to autonomous logistics requires us to rethink our entire operational paradigm—from asset ownership to platform orchestration.' What fundamental change is described?", ["Moving from owning logistics assets to orchestrating them through platforms", "Buying more delivery trucks", "Building more warehouses", "Hiring more drivers"], "Moving from owning logistics assets to orchestrating them through platforms"),
  q("C1", "listening", "finance", "A risk officer states: 'The correlation between our credit portfolio segments breaks down during tail events, rendering our VaR models unreliable precisely when we need them most.' What is the problem?", ["Risk models fail in extreme market conditions when they're needed most", "The portfolio is too diversified", "Interest rates are too low", "The models work perfectly"], "Risk models fail in extreme market conditions when they're needed most"),
  q("C1", "listening", "marketing", "A brand strategist observes: 'The semiotics of luxury branding are being fundamentally disrupted—exclusivity through scarcity is being replaced by exclusivity through experience and community.' What shift in luxury marketing is described?", ["Luxury brands are moving from product scarcity to experiential exclusivity", "Luxury goods are becoming cheaper", "Advertising is becoming less important", "Print media is replacing digital"], "Luxury brands are moving from product scarcity to experiential exclusivity"),
  q("C1", "listening", "reports", "An economist presents: 'The Phillips curve relationship has broken down in the post-pandemic economy, challenging central banks' traditional monetary policy frameworks.' What economic relationship is being questioned?", ["The relationship between inflation and unemployment", "The relationship between supply and demand", "The relationship between exports and imports", "The relationship between savings and investment"], "The relationship between inflation and unemployment"),
  q("C1", "listening", "presentations", "A keynote speaker says: 'The most transformative leaders don't just navigate uncertainty—they create optionality that allows their organizations to capitalize on whatever future materializes.' What leadership quality is highlighted?", ["The ability to create strategic options for multiple possible futures", "Making quick decisions", "Following industry best practices", "Reducing organizational complexity"], "The ability to create strategic options for multiple possible futures"),
  q("C1", "listening", "negotiations", "A mediator observes: 'The negotiation has devolved into a zero-sum framing. We need to reframe the value creation potential by mapping interdependencies across all parties' portfolios.' What does the mediator suggest?", ["Identifying mutual value creation opportunities across all stakeholders", "Splitting the difference evenly", "Having one party make concessions", "Ending the negotiation"], "Identifying mutual value creation opportunities across all stakeholders"),
];

export function getAllQuestions(): InsertBeQuestion[] {
  const allDefs = [
    ...grammarQuestions,
    ...vocabularyQuestions,
    ...useOfEnglishQuestions,
    ...readingQuestions,
    ...listeningQuestions,
  ];

  return allDefs.map((def) => ({
    level: def.level,
    skillType: def.skillType,
    section: def.skillType,
    topic: def.topic,
    question: def.question,
    options: JSON.stringify(def.options),
    correctAnswer: def.correctAnswer,
    passage: def.passage || null,
    difficulty: def.difficulty,
    discrimination: def.discrimination,
    calibrationStatus: "expert_judged",
  }));
}
