export interface ShopProduct {
  slug: string;
  name: string;
  category: string;
  description: string;
  price: string;
  priceLabel: string;
  duration: string;
  features: string[];
  pageLink: string;
}

export const SHOP_PRODUCTS: ShopProduct[] = [
  {
    slug: "corsi-gruppo",
    name: "Corsi di Gruppo",
    category: "Formazione in Presenza",
    description: "Corsi di lingua in piccoli gruppi (5-8 partecipanti) a Vicenza e Thiene. Due moduli da 6 settimane ciascuno.",
    price: "340.00",
    priceLabel: "12 settimane",
    duration: "12 settimane (2 moduli da 6)",
    features: [
      "Gruppi ridotti 5-8 persone",
      "2 lezioni settimanali da 90 min",
      "Materiale didattico incluso",
      "Certificato di partecipazione",
    ],
    pageLink: "/formazione-in-presenza",
  },
  {
    slug: "individuale-blended",
    name: "Corso Individuale Blended",
    category: "Formazione in Presenza",
    description: "Formazione individuale che combina lezioni in presenza con attività online per massima flessibilità.",
    price: "645.00",
    priceLabel: "12 settimane",
    duration: "12 settimane",
    features: [
      "Lezioni 1-to-1 personalizzate",
      "Mix presenza + online",
      "Orari flessibili",
      "Piattaforma e-learning inclusa",
    ],
    pageLink: "/formazione-in-presenza",
  },
  {
    slug: "office-senza-segreti",
    name: "Office Senza Segreti",
    category: "Formazione in Presenza",
    description: "Padroneggia Excel, Word e gli strumenti AI per la produttività. Corso pratico con esercitazioni reali.",
    price: "340.00",
    priceLabel: "Corso completo",
    duration: "Corso completo",
    features: [
      "Excel avanzato",
      "Word professionale",
      "Introduzione all'AI",
      "Esercitazioni pratiche",
    ],
    pageLink: "/formazione-in-presenza",
  },
  {
    slug: "ai-senza-segreti",
    name: "AI Senza Segreti",
    category: "Formazione in Presenza",
    description: "Scopri come l'intelligenza artificiale può trasformare il tuo lavoro. ChatGPT, automazione e strumenti AI.",
    price: "340.00",
    priceLabel: "Corso completo",
    duration: "Corso completo",
    features: [
      "ChatGPT e AI generativa",
      "Automazione processi",
      "Prompt engineering",
      "Applicazioni pratiche",
    ],
    pageLink: "/formazione-in-presenza",
  },
  {
    slug: "camclass-gruppo",
    name: "Cam-Class Blended di Gruppo",
    category: "Corsi E-Learning",
    description: "Lezioni online di gruppo con tutor madrelingua via Zoom, combinate con attività sulla piattaforma e-learning.",
    price: "60.00",
    priceLabel: "al mese",
    duration: "Minimo 1 mese",
    features: [
      "Lezioni live via Zoom",
      "Tutor madrelingua",
      "Piattaforma 24/7",
      "Materiale interattivo",
    ],
    pageLink: "/corsi-e-learning",
  },
  {
    slug: "camclass-individuale",
    name: "Cam-Class Corso Individuale",
    category: "Corsi E-Learning",
    description: "Percorso individuale online con tutor dedicato. 12 lezioni personalizzate sulle tue esigenze.",
    price: "230.00",
    priceLabel: "12 lezioni",
    duration: "12 lezioni",
    features: [
      "Lezioni 1-to-1 via Zoom",
      "Orari flessibili",
      "Programma personalizzato",
      "Materiale incluso",
    ],
    pageLink: "/corsi-e-learning",
  },
  {
    slug: "preparazione-certificazione",
    name: "Preparazione Certificazione Linguistica",
    category: "Corsi E-Learning",
    description: "Percorso mirato alla preparazione degli esami di certificazione linguistica internazionale.",
    price: "230.00",
    priceLabel: "12 lezioni + e-learning",
    duration: "12 lezioni + 60h e-learning",
    features: [
      "12 lezioni con tutor",
      "60 ore piattaforma e-learning",
      "Simulazioni d'esame",
      "Strategie per il test",
    ],
    pageLink: "/corsi-e-learning",
  },
  {
    slug: "conversazione-individuale",
    name: "Cam-Class Conversazione Individuale",
    category: "Corsi E-Learning",
    description: "Sessioni di conversazione individuale con docente madrelingua per migliorare fluency e confidence.",
    price: "95.00",
    priceLabel: "5 lezioni da 30 min",
    duration: "5 lezioni da 30 minuti",
    features: [
      "5 sessioni di 30 minuti",
      "Docente madrelingua",
      "Focus sulla conversazione",
      "Feedback personalizzato",
    ],
    pageLink: "/corsi-e-learning",
  },
  {
    slug: "camclass-minigruppi",
    name: "Cam-Class Corso in Mini-Gruppi",
    category: "Corsi E-Learning",
    description: "Corso online in piccoli gruppi con tutor madrelingua. L'interazione del gruppo con la comodità dell'online.",
    price: "230.00",
    priceLabel: "12 lezioni",
    duration: "12 lezioni",
    features: [
      "Mini-gruppi 3-5 persone",
      "Lezioni live via Zoom",
      "Interazione di gruppo",
      "Materiale incluso",
    ],
    pageLink: "/corsi-e-learning",
  },
  {
    slug: "coaching-in-sede",
    name: "Coaching Individuale in Sede",
    category: "Language Coaching",
    description: "Percorso di coaching linguistico individuale nella nostra sede di Vicenza. Approccio personalizzato e risultati concreti.",
    price: "390.00",
    priceLabel: "Modulare",
    duration: "Modulare",
    features: [
      "Sessioni 1-to-1 in sede",
      "Coach dedicato",
      "Piano personalizzato",
      "Monitoraggio progressi",
    ],
    pageLink: "/language-coaching",
  },
  {
    slug: "coaching-blended",
    name: "Coaching Blended (Presenza + Online)",
    category: "Language Coaching",
    description: "Il meglio dei due mondi: sessioni in presenza combinate con coaching online per un percorso intensivo di 12 settimane.",
    price: "840.00",
    priceLabel: "12 settimane intensive",
    duration: "12 settimane",
    features: [
      "Mix presenza + online",
      "Percorso intensivo",
      "Coach dedicato",
      "Massima flessibilità",
    ],
    pageLink: "/language-coaching",
  },
  {
    slug: "coaching-online",
    name: "Coaching Individuale Online",
    category: "Language Coaching",
    description: "Coaching linguistico individuale interamente online. 12 sessioni con coach madrelingua dedicato.",
    price: "300.00",
    priceLabel: "12 sessioni",
    duration: "12 sessioni",
    features: [
      "12 sessioni online",
      "Coach madrelingua",
      "Orari flessibili",
      "Da qualsiasi luogo",
    ],
    pageLink: "/language-coaching",
  },
  {
    slug: "fluency-coaching",
    name: "Fluency Coaching Intensivo",
    category: "Language Coaching",
    description: "Pacchetto intensivo di 5 sessioni da 30 minuti focalizzate sulla fluency e la scioltezza nella conversazione.",
    price: "125.00",
    priceLabel: "5 sessioni da 30 min",
    duration: "5 sessioni da 30 minuti",
    features: [
      "5 sessioni intensive",
      "Focus sulla fluency",
      "Correzione in tempo reale",
      "Risultati rapidi",
    ],
    pageLink: "/language-coaching",
  },
  {
    slug: "italiano-intensivo-15",
    name: "Italiano Intensivo Collettivo 15",
    category: "Corsi di Italiano per Stranieri",
    description: "Corso intensivo di italiano con 15 lezioni settimanali in piccoli gruppi a Vicenza. Ideale per un'immersione rapida.",
    price: "275.00",
    priceLabel: "a settimana",
    duration: "Minimo 1 settimana",
    features: [
      "15 lezioni/settimana",
      "Gruppi ridotti",
      "Attività culturali",
      "Certificato finale",
    ],
    pageLink: "/corsi-italiano",
  },
  {
    slug: "italiano-intensivo-20",
    name: "Italiano Intensivo Collettivo 20",
    category: "Corsi di Italiano per Stranieri",
    description: "Corso super-intensivo di italiano con 20 lezioni settimanali. Massima immersione linguistica a Vicenza.",
    price: "360.00",
    priceLabel: "a settimana",
    duration: "Minimo 1 settimana",
    features: [
      "20 lezioni/settimana",
      "Gruppi ridotti",
      "Attività culturali",
      "Certificato finale",
    ],
    pageLink: "/corsi-italiano",
  },
];

export function getProductBySlug(slug: string): ShopProduct | undefined {
  return SHOP_PRODUCTS.find((p) => p.slug === slug);
}
